### ISSUE TITLE
Running the tests lets show traceback of exceptions in the logs!

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1030]
Currently, when running automatic tests, there are traceback visible in the logs. They seem not to be important but it's a bad habit to let traceback visible in logs if it is not required (ie if its not an error)

example on travis: https://travis-ci.org/tracim/tracim_v2/jobs/441690890

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/tracim/tracim_v2/backend/donotexit.ini'
[Errno 2] No such file or directory: '/home/travis/build/tracim/tracim_v2/backend/donotexit.ini'
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/cliff/app.py", line 402, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/cliff/command.py", line 184, in run
    return_code = self.take_action(parsed_args) or 0
  File "/home/travis/build/tracim/tracim_v2/backend/tracim_backend/command/database.py", line 119, in take_action
    settings = get_appsettings(config_uri)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pyramid/paster.py", line 44, in get_appsettings
    return loader.get_wsgi_app_settings(name, options)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/plaster_pastedeploy/__init__.py", line 201, in get_wsgi_app_settings
    global_conf=defaults)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 261, in appconfig
    global_conf=global_conf)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 317, in _loadconfig
    loader = ConfigLoader(path)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 393, in __init__
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/tracim/tracim_v2/backend/donotexit.ini'
DEBUG:py:clean_up DeleteDBCommand
DEBUG:py:got an error: [Errno 2] No such file or directory: '/home/travis/build/tracim/tracim_v2/backend/donotexit.ini'
DEBUG:py:initialize_app
```

Expected: catch these traceback or generate a real error.

**Comment by lebouquetin** [comment]
After discussion with @inkhey this issue is already fixed.
