### ISSUE TITLE
app file: preview problem if name of file have special character

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1048]
**At present**

If image have name like this:

Capture d’écran de 2018-10-11 17-23-45.png

Preview not working. I have this error in backend:
~~~
17:06:11 ERROR [waitress:341][waitress] Exception when serving /api/v2/workspaces/1/files/15/revisions/28/preview/jpg/1920x1080
Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/waitress/task.py", line 437, in execute
    self.write(chunk)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/waitress/task.py", line 284, in write
    rh = self.build_response_header()
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/waitress/task.py", line 261, in build_response_header
    return tobytes(res)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/waitress/compat.py", line 56, in tobytes
    return bytes(s, 'latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 65: ordinal not in range(256)
~~~

if name is like this:

testpreview.jpg

Preview working good

**Expected**

- [ ] Its possible to have preview with all naming of file

**Comment by lebouquetin** [comment]
@PhilippeAccorsi the issue iis not about special char but about encoding. How can we reproduce this issue?

**Comment by inkhey** [comment]
This issue need to be fixed on hapic side, Content-Disposition header are wrong.
see https://github.com/algoo/hapic/pull/103 .

Another part of problem with special char is dealing with restricted in url like "?","&" or other, frontend should urlencode correctly filename to avoid trouble in url

**Comment by lebouquetin** [comment]
Why should frontend url encode filenames - they are not given in url but in body (so no need to urlencode, I think)

**Comment by Skylsmoi** [comment]
I don't understand either.
The only place where theses characters can cause an issue is in the urls to display them, they now end with the filename.
But '?' and '&' are forbidden characters for filename, any os system wont allow you to have filenames containing its.

**Comment by PhilippeAccorsi** [comment]
@lebouquetin to reproduce issue:
~~~
At present

If image have name like this:

Capture d’écran de 2018-10-11 17-23-45.png

~~

**Comment by Skylsmoi** [comment]
ok, so it's for any disallowed url characters

**Comment by inkhey** [comment]
@lebouquetin @Skylsmoi Frontend should urlencode character like "?" to avoid issue when frontend do GET with specified filename in order to avoid escaping problem with "?" considered as something else than part of the filename.

**Comment by Skylsmoi** [comment]
research done:
- I have tested to create a content file with a file named like so: "illégal char: ? that sux ' _.png" and everything works fine
- The character that cause the issue here is "’" (between ") which is a quote ([source](https://www.fileformat.info/info/unicode/char/2019/index.htm)) but a different one from the one from the key 4 on azerty keyboard. The filename from philippe has been generated by some tier application.

conclusion:
- One related issue in hapic has been PRed by @inkhey 
- Since the test with the filename "llégal char: ? that sux ' _.png" didn't showed any errors, frontend doesn't have to do anything
- @inkhey still have to fix some tests in backend

**Comment by PhilippeAccorsi** [comment]
@inkhey thats not working.
Same problem.

**Comment by PhilippeAccorsi** [comment]
Error 500.

Preview not working.

**Comment by tracim** [comment]
@inkhey when you fix this kind of issue you must tell the testers they need to upgrade dependencies.

**Comment by tracim** [comment]
By the way, you implement a fix for supporting utf8 chars and your test cases test... ascii chars only. You even not test filename given in the original issue.

Could you fix this? Thanks

**Comment by PhilippeAccorsi** [comment]
For test, update backend to make sure dependencies is the new one.
