### ISSUE TITLE
add user: generate a 500 with some smtp server if the email does not exist

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1106]
At present:

With mailjet:
You can add user with not good email. Mailjet dont return error and account is correctly created in tracim.

With gandi:
You cant add user with not good email. Gandi return an error and create account is aborded.
I have this error 500:
~~~
13:48:48 INFO  [sqlalchemy.engine.base.Engine:1154][waitress] ('tracim@tracim.tracim',)
13:48:48 DEBUG [tracim:24][waitress] [EmailManager] user: None
13:48:48 INFO  [tracim:38][waitress] [EmailManager] Sending asynchronous email to 1 user (tracim@tracim.tracim)
13:48:48 INFO  [tracim:38][waitress] [EmailSender] Connecting from SMTP server mail.gandi.net
13:48:48 DEBUG [tracim:24][waitress] [EmailSender] SMTP start TLS result: (220, b'2.0.0 Ready to start TLS')
13:48:48 DEBUG [tracim:24][waitress] [EmailSender] SMTP login result: (235, b'2.7.0 Authentication successful')
13:48:48 INFO  [tracim:38][waitress] [EmailSender] Connection OK
13:48:48 INFO  [tracim:38][waitress] [EmailSender] Sending email to tracim <tracim@tracim.tracim>
13:48:48 INFO  [hapic:244][waitress] Exception NotificationSendingFailed occured, return 500 http_code : Notification for new created account can't be send (SMTP error), new account creation aborted
13:48:48 DEBUG [hapic:246][waitress] Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/core/user.py", line 436, in create_user
    password=password
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/mail_notifier/notifier.py", line 426, in notify_created_account
    message=message
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/mail_notifier/sender.py", line 29, in send_email_through
    sendmail_callable(message)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/mail_notifier/sender.py", line 107, in send_mail
    self._smtp_connection.send_message(message)
  File "/usr/lib/python3.6/smtplib.py", line 967, in send_message
    rcpt_options)
  File "/usr/lib/python3.6/smtplib.py", line 881, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'tracim@tracim.tracim': (550, b'5.1.2 <tracim@tracim.tracim>: Recipient address rejected: Domain not found')}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/hapic.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 89, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 615, in _execute_wrapped_function
    func_kwargs,
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 100, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/authorization.py", line 88, in wrapper
    return func(self, context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 89, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 100, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 89, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 100, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/views/core_api/user_controller.py", line 265, in create_user
    do_save=True
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/core/user.py", line 442, in create_user
    ) from exc
tracim_backend.exceptions.NotificationSendingFailed: Notification for new created account can't be send (SMTP error), new account creation aborted

~~~

Expected:

**@backend**

- [ ] Its possible to create account with wrong email (some user dont have email but I can use tracim).
- [ ] If smtp serveur dont accept wrong email (wrong domain) continue to create user
- [ ] add specific error code for this case

**@frontend**

- [ ] add specific message about this error code
- [ ] add translate for flash message

**Comment by inkhey** [comment]
a hack was created here : https://github.com/tracim/tracim_v2/pull/117 to allow user creation even when recipient was not accepted by smtp server. 

Solution proposed by @PhilippeAccorsi  doesn't look really nice because it created a "Ok but..." return in API. We should think about how to deal correctly with this.

**Comment by PhilippeAccorsi** [comment]
Move to tracim_v2.2 for better solution.

**Comment by tracim** [comment]
The SMTP response about an invalid email address should result in a HTTP 400 (and an error shown to the user)

**Comment by Skylsmoi** [comment]
since frontend must have an error code in the http 400 response, I'm adding "blocked by backend" label
