### ISSUE TITLE
missing delete hamburger path in index.mak

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1117]
**At present**

When you use tracim frontend we can see this error in backend log.

~~~
14:53:57 INFO  [hapic:244][waitress] Exception PageNotFound occured, return 404 http_code : /assets/hamburger/hamburgers.min.css is not a valid path
14:53:57 DEBUG [hapic:246][waitress] Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/static.py", line 123, in __call__
    raise HTTPNotFound(request.url)
pyramid.httpexceptions.HTTPNotFound: http://192.168.1.150:6543/assets/hamburger/hamburgers.min.css

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid_retry/__init__.py", line 114, in retry_policy
    response = router.invoke_request(request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/view.py", line 757, in invoke_exception_view
    request_iface=request_iface.combined,
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/views/frontend.py", line 34, in not_found_view
    raise PageNotFound('{} is not a valid path'.format(request.path)) from context  # nopep8
tracim_backend.exceptions.PageNotFound: /assets/hamburger/hamburgers.min.css is not a valid path
~~~

**Expected**

After discuss with @Skylsmoi its just a missing delete in index.mak

- [ ] delete path about hamburger in index.mak (its done in index.html)

**Comment by PhilippeAccorsi** [comment]
Verified.
