### ISSUE TITLE
preview generator: some time I have error code 500 ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1124]
**At present**

After reset of cache in firefox with file in tracim. @inkhey I send you file directly.

I try to open my file, I can see the preview, if I navigate in my previw I can see error 500 in backend log.

~~~
15:23:54 INFO  [root:30][waitress] New Preview builder of class<class 'preview_generator.preview.builder.pdf__pypdf2.PdfPreviewBuilderPyPDF2'>
15:23:54 INFO  [hapic:244][waitress] Exception ValueError occured, return 500 http_code : invalid literal for int() with base 10: ''
15:23:54 DEBUG [hapic:246][waitress] Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/hapic.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/authorization.py", line 142, in wrapper
    return func(self, context, request)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/authorization.py", line 184, in wrapper
    return func(self, context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 89, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 615, in _execute_wrapped_function
    func_kwargs,
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 100, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 89, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 615, in _execute_wrapped_function
    func_kwargs,
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 100, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 89, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 615, in _execute_wrapped_function
    func_kwargs,
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 100, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 89, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 100, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 89, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 100, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 89, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 100, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/views/contents_api/file_controller.py", line 567, in sized_preview_jpg_revision
    file_extension=revision.file_extension,
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/core/content.py", line 1016, in get_jpg_preview_path
    if page_number >= self.preview_manager.get_page_nb(file_path, file_ext=file_extension):  # nopep8
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/preview_generator/manager.py", line 134, in get_page_nb
    mimetype
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/preview_generator/preview/builder/pdf__pypdf2.py", line 120, in get_page_number
    return int(count.read())
ValueError: invalid literal for int() with base 10: ''
~~~

**Expected**

- [ ]  preview work good also after reset internet browser caching.

**Comment by inkhey** [comment]
should be fixed in preview_generator_0.9 (https://github.com/algoo/preview-generator/issues/57), update in tracim in https://github.com/tracim/tracim_v2/pull/125

**Comment by PhilippeAccorsi** [comment]
Verified.
