### ISSUE TITLE
app-file: if preview_generator have an error, tracim failed. No encapsulation for preview error

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1125]
**At present**

file application broken by error in preview.

~~~
15:45:11 INFO  [hapic:244][waitress] Exception PdfReadError occured, return 500 http_code : File has not been decrypted
15:45:11 DEBUG [hapic:246][waitress] Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/marshmallow/utils.py", line 334, in _get_value_for_key
    return obj[key]
TypeError: 'RevisionInContext' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1147, in getNumPages
    self.decrypt('')
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1987, in decrypt
    return self._decrypt(password)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1996, in _decrypt
    raise NotImplementedError("only algorithm code 1 and 2 are supported")
NotImplementedError: only algorithm code 1 and 2 are supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/hapic.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/authorization.py", line 142, in wrapper
    return func(self, context, request)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/authorization.py", line 184, in wrapper
    return func(self, context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 89, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 100, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 90, in wrapper
    new_response = self.after_wrapped_function(response)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 280, in after_wrapped_function
    processed_response = self.processor.process(response)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/processor.py", line 147, in process
    dump_data = self.schema.dump(clean_data).data
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/marshmallow/schema.py", line 504, in dump
    **kwargs
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/marshmallow/marshalling.py", line 115, in serialize
    for idx, d in enumerate(obj)]
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/marshmallow/marshalling.py", line 115, in <listcomp>
    for idx, d in enumerate(obj)]
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/marshmallow/marshalling.py", line 138, in serialize
    index=(index if index_errors else None)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/marshmallow/marshalling.py", line 62, in call_and_store
    value = getter_func(data)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/marshmallow/marshalling.py", line 132, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/marshmallow/fields.py", line 242, in serialize
    value = self.get_value(attr, obj, accessor=accessor)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/marshmallow/fields.py", line 185, in get_value
    return accessor_func(check_key, obj, default)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/marshmallow/schema.py", line 398, in get_attribute
    return utils.get_value(attr, obj, default)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/marshmallow/utils.py", line 321, in get_value
    return _get_value_for_keys(key.split('.'), obj, default)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/marshmallow/utils.py", line 326, in _get_value_for_keys
    return _get_value_for_key(keys[0], obj, default)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/marshmallow/utils.py", line 337, in _get_value_for_key
    attr = getattr(obj, key)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/models/context_models.py", line 1171, in page_nb
    file_extension=self.revision.file_extension
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/core/content.py", line 1584, in get_preview_page_nb
    file_ext=file_extension
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/preview_generator/manager.py", line 134, in get_page_nb
    mimetype
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/preview_generator/preview/builder/pdf__pypdf2.py", line 117, in get_page_number
    count.write(str(inputpdf.numPages))
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1158, in <lambda>
    numPages = property(lambda self: self.getNumPages(), None, None)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1150, in getNumPages
    raise utils.PdfReadError("File has not been decrypted")
PyPDF2.utils.PdfReadError: File has not been decrypted
~~~

**Expected**

- [ ] encapsulate preview_generator error

- [ ] Its possible to use tracim with all type or file.

**Comment by PhilippeAccorsi** [comment]
Related to https://github.com/tracim/tracim/issues/1112

**Comment by PhilippeAccorsi** [comment]
Verified.
