### ISSUE TITLE
Error when install backend with README instructions

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1182]
**Describe the bug**

Errors when follow backend README install instructions (install with `setup_default_backend.sh` produce no errors).

**To Reproduce**

Install indicated packages, create a virtual env, execute (with venv activated) `pip install -r requirements.txt`. Error is:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zxnrfuwl/pyexifinfo/setup.py", line 95, in <module>
        result = check_if_exiftool_is_already_installed()
      File "/tmp/pip-install-zxnrfuwl/pyexifinfo/setup.py", line 51, in check_if_exiftool_is_already_installed
        stderr = fnull
      File "/usr/lib/python3.5/subprocess.py", line 557, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'exiftool'
```

If do a `python setup.py develop` an other error:

```
zip_safe flag not set; analyzing archive contents...
No eggs found in /tmp/easy_install-2nj9kn87/xvfbwrapper-0.2.9/egg-dist-tmp-1jd211b5 (setup script problem?)
error: The 'xvfbwrapper' distribution was not found and is required by preview-generator
```

**Comment by tracim** [comment]
What OS are you using?

**Comment by Sarah-Pelle** [comment]
Fixed
