### ISSUE TITLE
webdav: some issues

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1187]
**At present**

- All user can create folder with webdav (no verification about role)
- ~~all user cant create share space with webdav~~ => this is the normal behavior
- authorized user can copy file from local to tracim but an error appears (and if you refresh the screen, the file has been copied)
~~~
11:43:28 ERROR [waitress:341][waitress] Exception when serving /'fr'/test1/bug2.jpg
Traceback (most recent call last):
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/waitress/task.py", line 421, in execute
    for chunk in app_iter:
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/wsgidav/wsgidav_app.py", line 428, in __call__
    for v in app_iter:
  File "/home/algoo/repo/tracim/backend/tracim_backend/lib/webdav/middlewares.py", line 130, in __call__
    for v in app_iter:
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/wsgidav/error_printer.py", line 47, in __call__
    for v in app_iter:
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/wsgidav/request_resolver.py", line 199, in __call__
    for v in app_iter:
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/wsgidav/request_server.py", line 125, in __call__
    app_iter = provider.customRequestHandler(environ, start_response, method)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/wsgidav/dav_provider.py", line 1471, in customRequestHandler
    return defaultHandler(environ, start_response)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/wsgidav/request_server.py", line 781, in doPUT
    if res.supportEtag():
AttributeError: 'FakeFileStream' object has no attribute 'supportEtag'
~~~
~~~
Message => erreur lors de la copie dav://192.168.1.150:3030/'fr'/test1
internal error
~~~

- copy file from tracim to local is not working (html-document)
~~~
erreur: "erreur lors de l'obtention d'information concerant 'test webdav.document.html'"

erreur http: not found
~~~

- On windows: Its not possible to copy file normally, but you can if you try to copy, and after you try copy and replace. At this moment the copy start correctly. Same traceback that we have with linux

**Expected**

- [x] allow to create folders and files from local system to webdav server
- [x] user with specific role can create folder or content with webdav
- [x] user with profil admin can create shared space with webdav
- [x] user with profil trusted user can create shared space with webdav
- [x] copy file from local to tracim works without error (on linux)
- [x] copy file from local to tracim works without error (on windows)
- [x] user with specific role can copy file from local to tracim
- [x] its possible to copy file (created in tracim) from tracim to local without error

**Comment by PhilippeAccorsi** [comment]
Related to https://github.com/tracim/tracim/issues/1165

**Comment by PhilippeAccorsi** [comment]
@inkhey its possible to create folder or sharedspace with this kind of character but its normally not authorized because is not working with webdav. Specific code exist in tracim, and need debug:

character => `\ / : * ? " < > | `

**Comment by PhilippeAccorsi** [comment]
@inkhey FYI => dockertracim=# update users set auth_type='INTERNAL' where auth_type='UNKNOWN';

**Comment by PhilippeAccorsi** [comment]
- user with role contributor cant rename file with webdav (its possible with frontend interface) because rename its a move + add new name.

**Comment by PhilippeAccorsi** [comment]
Folder with not possibility (config make in frontend):

its not possible to copy-paste file directly in this folder (if this folder is open)
Its possible to copy file in this folder if this folder is not open (paste on folder and not in folder).

**Comment by PhilippeAccorsi** [comment]
If I tried to delete something with webdav, I can see its working good but after refresh all file is visible.

In backend log I can see:
~~~
<139673531901696> --- DELETE Response(403 Forbidden): ---
Content-Type: 'text/html'
Date: 'Tue, 11 Dec 2018 10:13:44 GMT'
Content-Length: '419'

b"<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01//EN' 'http://www.w3.org/TR/html4/strict.dtd'>\n<html><head>\n  <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>\n  <title>403 Forbidden</title>\n</head><body>\n  <h1>403 Forbidden</h1>\n  <p>403 Forbidden: Access denied to the specified resource</p>\n<hr/>\n<a href='https://github.com/mar10/wsgidav/'>WsgiDAV/2.4.1</a> - 2018-12-11 11:13:44.190828\n</body></html>"

<139673531901696> --- End of DELETE Response (419 bytes) ---
~~~

We need to find solution to prohibit delete if its not autorized. If its impossible to create folder or moving file I can see error message very quickly, We need the same for delete.

**Comment by PhilippeAccorsi** [comment]
For delete:

Its a normal way with wsgidav. We have tested this with cheroot and we can see same workflow that we have with tracimcli or with apache and uwsgi.

We need to investiguate on this if its really necessary.

**Comment by PhilippeAccorsi** [comment]
@inkhey for me: webdav is working: you can demand review about your MR

**Comment by PhilippeAccorsi** [comment]
Verified.
