### ISSUE TITLE
app: archive or delete content show flash message about an error

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1192]
At present

If I try to archive or delete one content I can see message in content "This content is archived." but in the same time the flash message "Warning Error while loading content list" appear.

In network I can seen: error 1003
~~~
Traceback (most recent call last): File "/home/algoo/repo/tracim/backend/tracim_backend/lib/core/content.py", line 679, in get_one content = base_request.one() File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2960, in one raise orm_exc.NoResultFound("No row was found for one()") sqlalchemy.orm.exc.NoResultFound: No row was found for one() The above exception was the direct cause of the following exception: Traceback (most recent call last): …l, order_by_properties, complete_path_to_id).all() File "/home/algoo/repo/tracim/backend/tracim_backend/lib/core/content.py", line 1156, in _get_all_query content = self.get_one(complete_path_to_id, content_type_list.Any_SLUG) File "/home/algoo/repo/tracim/backend/tracim_backend/lib/core/content.py", line 686, in get_one raise ContentNotFound('Content "{}" not found in database'.format(content_id)) from exc # nopep8 tracim_backend.exceptions.ContentNotFound: Content "74" not found in database 
~~~

Expected

- [ ] Its possible to archive or delete content without error.

**Comment by lebouquetin** [comment]
The error comes from `/api/v2/workspaces/1/contents?complete_path_to_id=4&parent_ids=0` which uses the complete_path_to_id of an archived (or deleted) content.

Here is the stacktrace:

```
{"code": 1003, "details": {"traceback": "Traceback (most recent call last):
  File \"/opt/tracim/latest/tracim/backend/tracim_backend/lib/core/content.py\", line 679, in get_one
    content = base_request.one()
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py\", line 2960, in one
    raise orm_exc.NoResultFound(\"No row was found for one()\")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/pyramid/tweens.py\", line 41, in excview_tween
    response = handler(request)
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/pyramid/router.py\", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/pyramid/view.py\", line 657, in _call_view
    response = view_callable(context, request)
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/pyramid/viewderivers.py\", line 325, in secured_view
    return view(context, request)
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/pyramid/viewderivers.py\", line 401, in viewresult_to_response
    result = view(context, request)
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/pyramid/viewderivers.py\", line 95, in mapped_view
    return _mapped_view(context, request)
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/hapic/hapic.py\", line 128, in wrapper
    return func(*args, **kwargs)
  File \"/opt/tracim/latest/tracim/backend/tracim_backend/lib/utils/authorization.py\", line 142, in wrapper
    return func(self, context, request)
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/hapic/decorator.py\", line 89, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/hapic/decorator.py\", line 100, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/hapic/decorator.py\", line 89, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/hapic/decorator.py\", line 100, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/hapic/decorator.py\", line 89, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File \"/opt/tracim/latest/tracim/backend/env/lib/python3.5/site-packages/hapic/decorator.py\", line 100, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File \"/opt/tracim/latest/tracim/backend/tracim_backend/views/core_api/workspace_controller.py\", line 482, in workspace_content
    order_by_properties=[Content.label]
  File \"/opt/tracim/latest/tracim/backend/tracim_backend/lib/core/content.py\", line 1223, in get_all
    return self._get_all_query(parent_ids, content_type, workspace, label, order_by_properties, complete_path_to_id).all()
  File \"/opt/tracim/latest/tracim/backend/tracim_backend/lib/core/content.py\", line 1156, in _get_all_query
    content = self.get_one(complete_path_to_id, content_type_list.Any_SLUG)
  File \"/opt/tracim/latest/tracim/backend/tracim_backend/lib/core/content.py\", line 686, in get_one
    raise ContentNotFound('Content \"{}\" not found in database'.format(content_id)) from exc  # nopep8
tracim_backend.exceptions.ContentNotFound: Content \"4\" not found in database
", "error_detail": {}}, "message": "Content \"4\" not found in database"}
```
