### ISSUE TITLE
Repair cypress test : userstatus_notification not found

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1204]
**Describe the bug**
Some change in frontend mak eone  cypress test to fail

```
  1) content :: workspace > dashbord dashboard__workspace > userstatus:
     CypressError: Timed out retrying: Expected to find element: '.userstatus .userstatus__notification', but never found it.
      at Object.cypressErr (http://localhost:6543/__cypress/runner/cypress_runner.js:63719:11)
      at Object.throwErr (http://localhost:6543/__cypress/runner/cypress_runner.js:63684:18)
      at Object.throwErrByPath (http://localhost:6543/__cypress/runner/cypress_runner.js:63711:17)
      at retry (http://localhost:6543/__cypress/runner/cypress_runner.js:57322:16)
      at http://localhost:6543/__cypress/runner/cypress_runner.js:49432:18
      at tryCatcher (http://localhost:6543/__cypress/runner/cypress_runner.js:124960:23)
      at Promise._settlePromiseFromHandler (http://localhost:6543/__cypress/runner/cypress_runner.js:122978:31)
      at Promise._settlePromise (http://localhost:6543/__cypress/runner/cypress_runner.js:123035:18)
      at Promise._settlePromise0 (http://localhost:6543/__cypress/runner/cypress_runner.js:123080:10)
      at Promise._settlePromises (http://localhost:6543/__cypress/runner/cypress_runner.js:123155:18)
      at Async._drainQueue (http://localhost:6543/__cypress/runner/cypress_runner.js:119884:16)
      at Async._drainQueues (http://localhost:6543/__cypress/runner/cypress_runner.js:119894:10)
      at Async.drainQueues (http://localhost:6543/__cypress/runner/cypress_runner.js:119768:14)
      at <anonymous>
```

see also this test job in PR about ldap feature (backend) : https://travis-ci.org/tracim/tracim/jobs/460722995

**Comment by PhilippeAccorsi** [comment]
Fixed with https://github.com/tracim/tracim/commit/1c1c45d52289b6f7a0ff5e97b622b0db5bcd1454

**Comment by PhilippeAccorsi** [comment]
Verified.
