### ISSUE TITLE
migration of bdd not working

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1249]
At present:

~~~
Traceback (most recent call last):
  File "/home/come/repo/tracim/backend/env/bin/alembic", line 11, in <module>
    load_entry_point('alembic==1.0.5', 'console_scripts', 'alembic')()
  File "/home/come/repo/tracim/backend/env/lib/python3.5/site-packages/alembic/config.py", line 503, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/come/repo/tracim/backend/env/lib/python3.5/site-packages/alembic/config.py", line 497, in main
    self.run_cmd(cfg, options)
  File "/home/come/repo/tracim/backend/env/lib/python3.5/site-packages/alembic/config.py", line 480, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/home/come/repo/tracim/backend/env/lib/python3.5/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/home/come/repo/tracim/backend/env/lib/python3.5/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/come/repo/tracim/backend/env/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/come/repo/tracim/backend/env/lib/python3.5/site-packages/alembic/util/compat.py", line 145, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "tracim_backend/migration/env.py", line 80, in <module>
    run_migrations_online()
  File "tracim_backend/migration/env.py", line 71, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/come/repo/tracim/backend/env/lib/python3.5/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/come/repo/tracim/backend/env/lib/python3.5/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/home/come/repo/tracim/backend/tracim_backend/migration/versions/2b4043fa2502_remove_webdav_right_digest_response_.py", line 19, in upgrade
    batch_op.drop_column('webdav_left_digest_response_hash')
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/come/repo/tracim/backend/env/lib/python3.5/site-packages/alembic/operations/base.py", line 300, in batch_alter_table
    impl.flush()
  File "/home/come/repo/tracim/backend/env/lib/python3.5/site-packages/alembic/operations/batch.py", line 76, in flush
    fn(*arg, **kw)
  File "/home/come/repo/tracim/backend/env/lib/python3.5/site-packages/alembic/operations/batch.py", line 338, in drop_column
    del self.columns[column.name]
  File "/home/come/repo/tracim/backend/env/lib/python3.5/site-packages/sqlalchemy/util/_collections.py", line 343, in __delitem__
    dict.__delitem__(self, key)
KeyError: 'webdav_left_digest_response_hash'
~~~

I have also this message if I start pserve
~~~
19:00:44 DEBUG [hapic:72][MainThread] Create new Hapic instance
19:00:44 DEBUG [hapic:72][MainThread] Create new Hapic instance
19:00:44 DEBUG [hapic:170][MainThread] Collect description of "<function AccountController.account at 0x7f77447af620>" and mark it with token "cdbe4cc549a14f1f8f44ea6f77a8ce4b"
19:00:44 DEBUG [hapic:170][MainThread] Collect description of "<function AccountController.set_account_infos at 0x7f7744633f28>" and mark it with token "ad53e3b86ce44997bae3214cbc887687"
19:00:44 DEBUG [hapic:170][MainThread] Collect description of "<function AccountController.account_known_members at 0x7f7744632378>" and mark it with token "487668d2fb9741eca662ca4e054d945a"
19:00:44 DEBUG [hapic:170][MainThread] Collect description of "<function AccountController.set_account_email at 0x7f77446326a8>" and mark it with token "29ee65371f8143bcb8e4f1889dfc10b5"
19:00:44 DEBUG [hapic:170][MainThread] Collect description of "<function AccountController.set_account_password at 0x7f7744632b70>" and mark it with token "ec4ae0bae1824ef8bd68bad1aa61bc8b"
19:00:44 DEBUG [hapic:170][MainThread] Collect description of "<function AccountController.account_workspace at 0x7f77446ca158>" and mark it with token "08c3fbbc37264960b8e6e26c20cffb17"
19:00:44 DEBUG [hapic:170][MainThread] Collect description of "<function AccountController.account_last_active_content at 0x7f77446ca400>" and mark it with token "c6365839671543db9f47e6aea8496cf0"
19:00:44 DEBUG [hapic:170][MainThread] Collect description of "<function AccountController.account_contents_read_status at 0x7f77446ca8c8>" and mark it with token "9d362dd365d048cbaef8241b04c92407"
19:00:44 DEBUG [hapic:170][MainThread] Collect description of "<function AccountController.set_account_content_as_read at 0x7f77446cad90>" and mark it with token "086acea57099435283bf3d8390da9a09"
19:00:44 DEBUG [hapic:170][MainThread] Collect description of "<function AccountController.set_account_content_as_unread at 0x7f77447541e0>" and mark it with token "2876db6b658645f7beb1f8623531e6aa"
19:00:44 DEBUG [hapic:170][MainThread] Collect description of "<function AccountController.set_account_workspace_as_read at 0x7f7744754598>" and mark it with token "2f5bafbc53634a67bec8c8233796e88f"
19:00:44 DEBUG [hapic:170][MainThread] Collect description of "<function AccountController.enable_account_workspace_notification at 0x7f7744754950>" and mark it with token "20e5df13dc4e492c9f61d444b8539636"
19:00:44 DEBUG [hapic:170][MainThread] Collect description of "<function AccountController.disable_account_workspace_notification at 0x7f7744754d08>" and mark it with token "2027448803fc47f992e910675c3de7cf"
Traceback (most recent call last):
  File "/home/algoo/repo/tracim/backend/env/bin/pserve", line 11, in <module>
    sys.exit(main())
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/pyramid/scripts/pserve.py", line 253, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 277, in loadobj
    global_conf=global_conf)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 302, in loadcontext
    global_conf=global_conf)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 326, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 455, in get_context
    global_additions=global_additions)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 564, in _pipeline_app_context
    APP, pipeline[-1], global_conf)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 459, in get_context
    section)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 481, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 412, in get_context
    global_conf=global_conf)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 302, in loadcontext
    global_conf=global_conf)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 334, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 625, in get_context
    object_type, name=name)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 651, in find_egg_entry_point
    possible.append((entry.load(), protocol, entry.name))
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/algoo/repo/tracim/backend/tracim_backend/__init__.py", line 19, in <module>
    from tracim_backend.lib.utils.authentification import CookieSessionAuthentificationPolicy
  File "/home/algoo/repo/tracim/backend/tracim_backend/lib/utils/authentification.py", line 10, in <module>
    from pyramid_ldap3 import get_ldap_connector
ModuleNotFoundError: No module named 'pyramid_ldap3'
~~~

And this one if I start setup_default_backend.sh

~~~
/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/alembic/util/messaging.py:70: UserWarning: Skipping unsupported ALTER for creation of implicit constraint
  warnings.warn(msg)
~~~

Expected

Migration working correctly from tracim_v2 to tracim_v2 or from tracim_v1 to tracim_v2

**Comment by PhilippeAccorsi** [comment]
Verified.
