### ISSUE TITLE
Webdav: error http proxy when you want to see content in folder

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1312]
**At present**

When you used webdav, sometime when you try to see some content in folder, you have an error "http proxy". We see this error in tracim-webdav.log:
~~~
17:18:20 INFO  [sqlalchemy.engine.base.Engine:1154][b'uWSGIWorker1Core0'] {'workspace_id_17': 78, 'workspace_id_3': 51, 'type_6': 'comment', 'workspace_id_12': 73, 'type_3': 'html-document', 'parent_id_1': 3530, 'workspace_id_5': 59, 'param_1': 1, 'type_5': 'folder', 'workspace_id_4': 49, 'type_1': 'thread', 'workspace_id_9': 66, 'type_8': 'comment', 'workspace_id_7': 11, 'workspace_id_15': 30, 'workspace_id_14': 17, 'workspace_id_13': 74, 'workspace_id_1': 1, 'workspace_id_11': 70, 'workspace_id_16': 76, 'workspace_id_2': 53, 'type_7': 'any', 'type_4': 'page', 'type_2': 'file', 'owner_id_1': 233, 'workspace_id_8': 65, 'workspace_id_6': 52, 'workspace_id_10': 67, 'workspace_id_18': 22}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/wsgidav/wsgidav_app.py", line 428, in __call__
    for v in app_iter:
  File "./tracim_backend/lib/webdav/middlewares.py", line 141, in __call__
    for v in app_iter:
  File "/usr/local/lib/python3.5/dist-packages/wsgidav/error_printer.py", line 47, in __call__
    for v in app_iter:
  File "/usr/local/lib/python3.5/dist-packages/wsgidav/request_resolver.py", line 199, in __call__
    for v in app_iter:
  File "/usr/local/lib/python3.5/dist-packages/wsgidav/request_server.py", line 125, in __call__
    app_iter = provider.customRequestHandler(environ, start_response, method)
  File "/usr/local/lib/python3.5/dist-packages/wsgidav/dav_provider.py", line 1471, in customRequestHandler
    return defaultHandler(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/wsgidav/request_server.py", line 317, in doPROPFIND
    reslist = res.getDescendants(depth=environ["HTTP_DEPTH"], addSelf=True)
  File "/usr/local/lib/python3.5/dist-packages/wsgidav/dav_provider.py", line 453, in getDescendants
    for child in self.getMemberList():
  File "./tracim_backend/lib/webdav/resources.py", line 71, in wrapper
    return func(self, *arg, **kwarg)
  File "./tracim_backend/lib/webdav/resources.py", line 641, in getMemberList
    tracim_context=self.tracim_context
  File "./tracim_backend/lib/webdav/resources.py", line 935, in __init__
    self.content_designed = self.design()
  File "./tracim_backend/lib/webdav/resources.py", line 983, in design
    self.content_api.get_all([self.content.content_id], content_type_list.Comment.slug)
  File "./tracim_backend/lib/webdav/design.py", line 179, in designThread
    first_comment = comments[0]
IndexError: list index out of range
[pid: 991|app: 0|req: 8/8] 127.0.0.1 () {44 vars in 783 bytes} [Mon Jan 14 17:18:20 2019] PROPFIND /webdav/Intranet/Documentation%20g%C3%A9n%C3%A9rale/ => generated 0 bytes in 115 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
~~~

We have tried to change this file"./tracim_backend/lib/webdav/design.py" by adding code on line 177:
~~~
if len(comments) <= 0:
return ' '
~~~

With this, we can see all data in folder. But this is not a good solution.

**Expected**

Its possible to see correctly the content of folder.

**Comment by PhilippeAccorsi** [comment]
@inkhey @basilelegal I don't know which of you can solved this issue.
