### ISSUE TITLE
running an API call twice (fast) result in creating same content twice

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1361]
Currently: if I execute 2 api calls fast for creating a thread entitled "discussion", it results in 2 threads entitled "discussion" in the same folder.

The backend MUST avoid this case. This should be already resolved (we talked about this several times for months now).

This is even the case if I click twice on a button (this is not a matter of nanoseconds between api calls)

**Comment by lebouquetin** [comment]
I see the problem. Maybe information must be stored in `contents` table and then, when creating a new revision, we start by updating the `content` table (which would have a unique key).

Let think about it for a few days...

**Comment by inkhey** [comment]
to do this and have a true lock we need to force uniqueness of  combination of  `workspace_id`,`parent_id` , `label` and `file_extension` in parent. Those should coordinate to last revision of content value.

Ps: we have to think about adding is_deleted and is_archived later in this unique if we decide to change the way we deal with deleted/archive (if we find an other solution than renaming).

**Comment by PhilippeAccorsi** [comment]
@inkhey 
~~~
> Traceback (most recent call last):
>   File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
>     context)
>   File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.IntegrityError: ERREUR:  n'a pas pu créer l'index unique « uq__content__workspace_id »
> DETAIL:  La clé (workspace_id, parent_id, label, file_extension)=(28, 2639, note_de_frais_10.2016, .ods) est dupliquée.
~~~

This is normal because its possible to have same content_id with same labe if you have created and deleted this file. two line in database.

**Comment by PhilippeAccorsi** [comment]
Idea to solve that:
Use sql command to add "deleted" or something like that at end of label for content deleted on bdd (bdd from tracim_v1).

**Comment by inkhey** [comment]
@PhilippeAccorsi 
For issue with dump of old content :
1 - Be sure to have save of dump file.
2 - Launch sql query like "update from content_revisions when is_deleted = True set label = label || '_del' ; " to fix issue with 2 content same label on same folder/workspace.
3 - Redo migration upgrade and inspect if some other file failed.

**Comment by inkhey** [comment]
Another issue with this PR is mariadb/mysql compatibility. Some version doesn't accept more than 7.. char for unique/key . This should be check one more time as this work on automatic test but not during local test.

**Comment by buxx** [comment]
Please note deletion process is currently (see [this](https://github.com/tracim/tracim/blob/develop/backend/tracim_backend/lib/core/content.py) file):

```python
    def delete(self, content: Content):
        content.owner = self._user
        content.is_deleted = True
        # TODO - G.M - 12-03-2018 - Inspect possible label conflict problem
        # INFO - G.M - 12-03-2018 - Set label name to avoid trouble when
        # un-deleting file.
        label = '{label}-{action}-{date}'.format(
            label=content.label,
            action='deleted',
            date=current_date_for_filename()
        )
        filename = self._prepare_filename(label, content.file_extension)
        self._is_filename_available_or_raise(
            filename,
            content.workspace,
            content.parent,
            exclude_content_id=content.content_id
        )
        content.file_name = filename
content.revision_type = ActionDescription.DELETION
```

**Comment by lebouquetin** [comment]
@inkhey in you add the label unclear, you should explain what is not clear. Could you do that, please ?

**Comment by inkhey** [comment]
@lebouquetin 
I set to "unclear" because i wanted to specify that this issue is somehow blocked. Probably "need discussion" is probably more appropriate than "unclear".

Problems are:
- Old fix https://github.com/tracim/tracim/pull/1440 work in new env but cause many troubles with old dataset tested.
- there is also some issue with mysql on some version : https://github.com/tracim/tracim/issues/1361#issuecomment-462665801
- last but not least, it's style not clear if we should add some other field to primary key as those tested in  https://github.com/tracim/tracim/pull/1440.

**Comment by raphj** [comment]
Should this be put in a project? @lebouquetin

**Comment by lebouquetin** [comment]
@raphj : I think this can be added in v3.3.x

**Comment by inkhey** [comment]
A clever way to deal with both having a strict database based naming rule for most content and at the same time permitting content without name for comment and news seems to be allowing content with NULL label in some specific case, as NULL != NULL in SQL.
