### ISSUE TITLE
exception found in uwsgi logs...

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1386]
On my instance, I see regularly the following traceback in uwsgi logs:

```
==> /data/tracimv2/11_algoo/var/logs/tracim_web.log <==
21:48:35 INFO  [hapic:244][b'uWSGIWorker2Core0'] Exception PageNotFound occured, return 404 http_code : / is not a valid path
21:48:35 DEBUG [hapic:246][b'uWSGIWorker2Core0'] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 173, in handle_request
    raise HTTPNotFound(msg)
pyramid.httpexceptions.HTTPNotFound: /

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyramid_retry/__init__.py", line 114, in retry_policy
    response = router.invoke_request(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 757, in invoke_exception_view
    request_iface=request_iface.combined,
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "./tracim_backend/views/frontend.py", line 32, in not_found_view
    raise PageNotFound('{} is not a valid path'.format(request.path)) from context  # nopep8
tracim_backend.exceptions.PageNotFound: / is not a valid path
```

**Comment by inkhey** [comment]
I need more context to understand the issue. 
This kind of error happened when you set hapic log to low level (debug or info) and tried to access to not valid path, like for example http://localhost:6543/ap/v2/thispathisnotavalidone .
In this case tracim api return 404 with a json with some info (like any other tracim exception).
What seems very curious is that it give the exception for "/".
Is frontend working and properly installed ?

**Comment by lebouquetin** [comment]
@inkhey it's not the frontend which must manager `/` route, I think, it's backend.
