### ISSUE TITLE
add socket-timeout in uwsgi conf for docker image

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1438]
At present

Sometime when I upload file to tracim with docker, I have an timeout error.
exemple of log:
~~~
==> var/logs/tracim_web.log <==
Mon Feb 11 14:23:33 2019 - [uwsgi-body-read] Timeout reading 41600 bytes. Content-Length: 12122850 consumed: 8207744 left: 3915106
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 270, in call
    response = self.execution_policy(environ, self)
  File "/usr/local/lib/python3.5/dist-packages/pyramid_retry/init.py", line 92, in retry_policy
    request.make_body_seekable()
  File "/usr/local/lib/python3.5/dist-packages/webob/request.py", line 929, in make_body_seekable
    self.copy_body()
  File "/usr/local/lib/python3.5/dist-packages/webob/request.py", line 953, in copy_body
    data = input.read(min(todo, 65535))
  File "/usr/local/lib/python3.5/dist-packages/webob/request.py", line 1538, in readinto
    data = self.file.read(sz0)
OSError: timeout during read(57344) on wsgi.input
[pid: 502|app: 0|req: 10289/15500] 127.0.0.1 () {44 vars in 1068 bytes} [Mon Feb 11 14:21:59 2019] PUT /api/v2/workspaces/85/files/8321/raw/VisionCollect-v2.3.4.debug1.apk => generated 0 bytes in 93631 msecs (HTTP/1.1 500) 0 headers in 0 bytes (485 switches on core 0)
~~~

Expected

- [x] add `socket-timeout = 360`
- [x] create an issue for next release to find good solution. #1437

**Comment by PhilippeAccorsi** [comment]
Verified.

**Comment by PhilippeAccorsi** [comment]
The problem here is: uwsgi use default apache timeout if no socket-timeout is defined in uwsgi config. Default value is 15sec.
