### ISSUE TITLE
Preview of file (*.jpg) is not working after import with webdav. 

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1456]
## At present

I have imported some file and folder with webdav, If I tried to see one jpg file, frontend says "No preview available". If I upload this file in one other folder with webbrowser interface, the preview is working good. Now I try to see preview of the first file => preview working.

Preview is working good with png file for exemple (with same process to put this file in tracim)

###To reproduce:
- use webdav to copy one jpg file to tracim
- try to see preview with web-browser => "no preview available"
- Now, upload this file with web-interface in one other folder
- try to see preview with web-browser => preview working
- Now, try to see preview of the first file => preview working

Here is the traceback when I tried to see preview with the first file in first ime.

~~~
08:38:31 WARNI [tracim:43][b'uWSGIWorker2Core0'] [ContentApi] Unknown Preview_Generator Exception Occured : join() argument must be str or bytes, not 'NoneType'
08:38:31 WARNI [tracim:43][b'uWSGIWorker2Core0'] [ContentApi] Traceback (most recent call last):
  File "./tracim_backend/lib/core/content.py", line 1082, in get_jpg_preview_path
    file_ext=file_extension,
  File "/usr/local/lib/python3.5/dist-packages/preview_generator/manager.py", line 186, in get_jpeg_preview
    mimetype=mimetype
  File "/usr/local/lib/python3.5/dist-packages/preview_generator/preview/builder/image__imconvert.py", line 82, in build_jpeg_preview
    tmp_filepath = os.path.join(tempfolder, tmp_filename)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

08:38:31 INFO  [hapic:691][b'uWSGIWorker2Core0'] Exception UnavailablePreview occured, return 400 http_code : No preview available for content 52, revision 52
08:38:31 DEBUG [hapic:695][b'uWSGIWorker2Core0'] Traceback (most recent call last):
  File "./tracim_backend/lib/core/content.py", line 1082, in get_jpg_preview_path
    file_ext=file_extension,
  File "/usr/local/lib/python3.5/dist-packages/preview_generator/manager.py", line 186, in get_jpeg_preview
    mimetype=mimetype
  File "/usr/local/lib/python3.5/dist-packages/preview_generator/preview/builder/image__imconvert.py", line 82, in build_jpeg_preview
    tmp_filepath = os.path.join(tempfolder, tmp_filename)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    func_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 101, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 90, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    func_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 101, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 90, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    func_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 101, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 90, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 101, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 90, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 101, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 90, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 101, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "./tracim_backend/views/contents_api/file_controller.py", line 586, in sized_preview_jpg_revision
    file_extension=revision.file_extension,
  File "./tracim_backend/lib/core/content.py", line 1109, in get_jpg_preview_path
    ) from exc
tracim_backend.exceptions.UnavailablePreview: No preview available for content 52, revision 52

[pid: 440|app: 0|req: 58/101] 127.0.0.1 () {44 vars in 1023 bytes} [Thu Feb 21 08:38:31 2019] GET /api/v2/workspaces/1/files/52/revisions/52/preview/jpg/500x500/Livre-3D2.jpg?page=1 => generated 110 bytes in 104 msecs (HTTP/1.1 400) 1 headers in 60 bytes (1 switches on core 0)
08:38:31 INFO  [root:30][b'uWSGIWorker1Core0'] New Preview builder of class<class 'preview_generator.preview.builder.image__imconvert.ImagePreviewBuilderIMConvert'>
08:38:31 INFO  [root:30][b'uWSGIWorker1Core0'] New Preview builder of class<class 'preview_generator.preview.builder.image__imconvert.ImagePreviewBuilderIMConvert'>
08:38:31 INFO  [root:30][b'uWSGIWorker1Core0'] New Preview builder of class<class 'preview_generator.preview.builder.image__imconvert.ImagePreviewBuilderIMConvert'>
[pid: 439|app: 0|req: 44/102] 127.0.0.1 () {42 vars in 917 bytes} [Thu Feb 21 08:38:31 2019] GET /api/v2/workspaces/1/files/52/revisions => generated 655 bytes in 108 msecs (HTTP/1.1 200) 1 headers in 51 bytes (1 switches on core 0)
[pid: 440|app: 0|req: 59/103] 127.0.0.1 () {42 vars in 1000 bytes} [Thu Feb 21 08:38:31 2019] GET /api/v2/workspaces/1/contents?complete_path_to_id=52&parent_ids=0,1,2,2,1,2,1,2,1 => generated 36220 bytes in 267 msecs (HTTP/1.1 200) 1 headers in 51 bytes (1 switches on core 0)
[pid: 440|app: 0|req: 60/104] 127.0.0.1 () {42 vars in 895 bytes} [Thu Feb 21 08:38:32 2019] GET /api/v2/workspaces/1/members => generated 281 bytes in 21 msecs (HTTP/1.1 200) 1 headers in 51 bytes (1 switches on core 0)
[pid: 440|app: 0|req: 61/105] 127.0.0.1 () {42 vars in 939 bytes} [Thu Feb 21 08:38:32 2019] GET /api/v2/users/me/workspaces/1/contents/read_status => generated 10083 bytes in 2039 msecs (HTTP/1.1 200) 1 headers in 51 bytes (1 switches on core 0)
~~~

File: 
![animal-pieds-tte](https://user-images.githubusercontent.com/25848257/53155373-32453c00-35bd-11e9-9c98-85ff251c52cb.jpg)
Other file: 
![hqdefault](https://user-images.githubusercontent.com/25848257/53155870-4ccbe500-35be-11e9-8101-254c0404931a.jpg)

## Expected

- [ ] Its possible to see preview of jpg file also if this file is imported with webdav.

**Comment by Quiwy** [comment]
I have no problem neither on build_088
