### ISSUE TITLE
error log visible after dismiss alerte message in thunderbird about event

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1579]
## Bug description & symptom

If I create event in tracim with alerte, I can see this alerte in thunderbird but when I click on dismiss I can see in radicale log, some error:
~~~
Successful login: 'notaname'
13:52:05 INFO  [radicale:387][waitress] REPORT response status for '/calendar/workspace/2/' in 0.002 seconds: 207 Multi-Status
13:52:34 INFO  [radicale:409][waitress] GET request for '/calendar/workspace/2/' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.6.1 Lightning/6.2.6.1'
13:52:34 INFO  [radicale:471][waitress] Successful login: 'admin@admin.admin'
13:52:34 INFO  [radicale:387][waitress] GET response status for '/calendar/workspace/2/' in 0.003 seconds: 200 OK
13:52:40 INFO  [radicale:409][waitress] GET request for '/calendar/workspace/2/' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.6.1 Lightning/6.2.6.1'
13:52:40 INFO  [radicale:471][waitress] Successful login: 'admin@admin.admin'
13:52:40 INFO  [radicale:387][waitress] GET response status for '/calendar/workspace/2/' in 0.002 seconds: 200 OK
13:52:40 INFO  [radicale:409][waitress] PUT request for '/calendar/workspace/2/' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.6.1 Lightning/6.2.6.1'
13:52:40 INFO  [radicale:471][waitress] Successful login: 'admin@admin.admin'
13:52:40 INFO  [radicale:387][waitress] PUT response status for '/calendar/workspace/2/' in 0.209 seconds: 201 Created
13:54:06 INFO  [radicale:409][waitress] PROPFIND request for '/calendar/user/1/' with depth '0' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
13:54:06 INFO  [radicale:471][waitress] Successful login: 'notaname'
13:54:06 INFO  [radicale:387][waitress] PROPFIND response status for '/calendar/user/1/' with depth '0' in 0.004 seconds: 207 Multi-Status
13:54:06 INFO  [radicale:409][waitress] PROPFIND request for '/calendar/user/1/' with depth '1' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
13:54:06 INFO  [radicale:471][waitress] Successful login: 'notaname'
13:54:06 INFO  [radicale:387][waitress] PROPFIND response status for '/calendar/user/1/' with depth '1' in 0.005 seconds: 207 Multi-Status
13:54:06 INFO  [radicale:409][waitress] PROPFIND request for '/calendar/workspace/13/' with depth '0' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
13:54:06 INFO  [radicale:471][waitress] Successful login: 'notaname'
13:54:06 INFO  [radicale:387][waitress] PROPFIND response status for '/calendar/workspace/13/' with depth '0' in 0.002 seconds: 207 Multi-Status
13:54:06 INFO  [radicale:409][waitress] PROPFIND request for '/calendar/workspace/13/' with depth '1' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
13:54:06 INFO  [radicale:471][waitress] Successful login: 'notaname'
13:54:06 INFO  [radicale:387][waitress] PROPFIND response status for '/calendar/workspace/13/' with depth '1' in 0.003 seconds: 207 Multi-Status
13:54:06 INFO  [radicale:409][waitress] PROPFIND request for '/calendar/workspace/2/' with depth '0' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
13:54:06 INFO  [radicale:471][waitress] Successful login: 'notaname'
13:54:06 INFO  [radicale:387][waitress] PROPFIND response status for '/calendar/workspace/2/' with depth '0' in 0.002 seconds: 207 Multi-Status
13:54:06 INFO  [radicale:409][waitress] PROPFIND request for '/calendar/workspace/2/' with depth '1' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
13:54:06 INFO  [radicale:471][waitress] Successful login: 'notaname'
13:54:07 INFO  [radicale:387][waitress] PROPFIND response status for '/calendar/workspace/2/' with depth '1' in 0.153 seconds: 207 Multi-Status
13:54:07 INFO  [radicale:409][waitress] REPORT request for '/calendar/workspace/2/' with depth '1' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
13:54:07 INFO  [radicale:471][waitress] Successful login: 'notaname'
13:54:07 WARNI [radicale:1189][waitress] Client provided invalid sync token 'http://radicale.org/ns/sync/08b7f3f4bd60023ee05c9f050cfdcfc4': Token not found: 'http://radicale.org/ns/sync/08b7f3f4bd60023ee05c9f050cfdcfc4'
Traceback (most recent call last):
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/radicale/storage.py", line 1223, in sync
    with open(old_token_path, "rb") as f:
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/algoo/repo/tracim/backend/radicale_storage/collection-root/calendar/workspace/2/.Radicale.cache/sync-token/08b7f3f4bd60023ee05c9f050cfdcfc4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/radicale/xmlutils.py", line 1185, in report
    sync_token, names = collection.sync(old_sync_token)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/radicale/storage.py", line 1236, in sync
    raise ValueError("Token not found: %r" % old_token)
ValueError: Token not found: 'http://radicale.org/ns/sync/08b7f3f4bd60023ee05c9f050cfdcfc4'
13:54:07 INFO  [radicale:387][waitress] REPORT response status for '/calendar/workspace/2/' with depth '1' in 0.002 seconds: 409 Conflict
13:54:27 INFO  [radicale:409][waitress] PROPFIND request for '/calendar/user/1/' with depth '0' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
13:54:27 INFO  [radicale:471][waitress] Successful login: 'notaname'
~~~

## Diagnostic

Need to try with radicale without proxy
- [ ] same error log
- [ ] no error log

## Expected

- [ ] no error appear if I just dismiss alerte in thunderbird

## Context and version information

thunderbird 60.6.1

## Prerequisites

- Create event in calendar with one alerte
- your calendar need to be visible in thunderbird

## How to reproduce

Click on dismiss message in thunderbird when alert exist

**Comment by PhilippeAccorsi** [comment]
More information after testing when make sure I use caldav and not ics.
After click on dismiss
~~~
14:17:18 INFO  [radicale:409][waitress] PUT request for '/calendar/workspace/2/bd6aa16d41388813821c7b267a567dbdf3a56b00dc1eae8b333d81e741ee0989.ics' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.6.1 Lightning/6.2.6.1'
14:17:18 INFO  [radicale:471][waitress] Successful login: 'admin@admin.admin'
14:17:18 INFO  [radicale:387][waitress] PUT response status for '/calendar/workspace/2/bd6aa16d41388813821c7b267a567dbdf3a56b00dc1eae8b333d81e741ee0989.ics' in 0.073 seconds: 201 Created
14:17:18 INFO  [radicale:409][waitress] REPORT request for '/calendar/workspace/2/' with depth '1' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.6.1 Lightning/6.2.6.1'
14:17:18 INFO  [radicale:471][waitress] Successful login: 'admin@admin.admin'
14:17:18 INFO  [radicale:387][waitress] REPORT response status for '/calendar/workspace/2/' with depth '1' in 0.002 seconds: 207 Multi-Status
~~~

After automatic refresh of radicale
~~~
14:18:31 INFO  [radicale:409][waitress] PROPFIND request for '/calendar/user/1/' with depth '0' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
14:18:31 INFO  [radicale:471][waitress] Successful login: 'notaname'
14:18:31 INFO  [radicale:387][waitress] PROPFIND response status for '/calendar/user/1/' with depth '0' in 0.002 seconds: 207 Multi-Status
14:18:31 INFO  [radicale:409][waitress] PROPFIND request for '/calendar/user/1/' with depth '1' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
14:18:31 INFO  [radicale:471][waitress] Successful login: 'notaname'
14:18:31 INFO  [radicale:387][waitress] PROPFIND response status for '/calendar/user/1/' with depth '1' in 0.004 seconds: 207 Multi-Status
14:18:31 INFO  [radicale:409][waitress] PROPFIND request for '/calendar/workspace/13/' with depth '0' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
14:18:31 INFO  [radicale:471][waitress] Successful login: 'notaname'
14:18:31 INFO  [radicale:387][waitress] PROPFIND response status for '/calendar/workspace/13/' with depth '0' in 0.002 seconds: 207 Multi-Status
14:18:31 INFO  [radicale:409][waitress] PROPFIND request for '/calendar/workspace/13/' with depth '1' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
14:18:31 INFO  [radicale:471][waitress] Successful login: 'notaname'
14:18:31 INFO  [radicale:387][waitress] PROPFIND response status for '/calendar/workspace/13/' with depth '1' in 0.006 seconds: 207 Multi-Status
14:18:31 INFO  [radicale:409][waitress] PROPFIND request for '/calendar/workspace/2/' with depth '0' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
14:18:31 INFO  [radicale:471][waitress] Successful login: 'notaname'
14:18:31 INFO  [radicale:387][waitress] PROPFIND response status for '/calendar/workspace/2/' with depth '0' in 0.005 seconds: 207 Multi-Status
14:18:31 INFO  [radicale:409][waitress] PROPFIND request for '/calendar/workspace/2/' with depth '1' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
14:18:31 INFO  [radicale:471][waitress] Successful login: 'notaname'
14:18:31 INFO  [radicale:387][waitress] PROPFIND response status for '/calendar/workspace/2/' with depth '1' in 0.021 seconds: 207 Multi-Status
14:18:31 INFO  [radicale:409][waitress] REPORT request for '/calendar/workspace/2/' with depth '1' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
14:18:31 INFO  [radicale:471][waitress] Successful login: 'notaname'
14:18:31 INFO  [radicale:387][waitress] REPORT response status for '/calendar/workspace/2/' with depth '1' in 0.004 seconds: 207 Multi-Status
14:18:31 INFO  [radicale:409][waitress] REPORT request for '/calendar/workspace/2/' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
14:18:31 INFO  [radicale:471][waitress] Successful login: 'notaname'
14:18:31 INFO  [radicale:387][waitress] REPORT response status for '/calendar/workspace/2/' in 0.002 seconds: 207 Multi-Status
~~~

After refresh of thunerbird
~~~
14:19:14 INFO  [radicale:409][waitress] REPORT request for '/calendar/workspace/2/' with depth '1' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.6.1 Lightning/6.2.6.1'
14:19:14 INFO  [radicale:471][waitress] Successful login: 'admin@admin.admin'
14:19:14 INFO  [radicale:387][waitress] REPORT response status for '/calendar/workspace/2/' with depth '1' in 0.004 seconds: 207 Multi-Status
~~~

I think the error appear if we not use caldav correctly with thunderbird.
