### ISSUE TITLE
cypress test workspace/content_dashboard_headerdetail.js failed on travis (just yesterday night)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1685]
## Bug description & symptom

Yesterday (2019/05/06) this cypress test `workspace/content_dashboard_headerdetail.js` failed with travis with different build.

## Diagnostic

"unknown"

## Expected

- [ ] cypress test working correctly

## How to reproduce

I don't know because I can reproduce this error on local machine and with travis.

## Impacted components

- *backend*
- *frontend*

## Extra information

all log available in travis:
~~~
Running: workspace/content_dashboard_headerdetail.js...                                (48 of 55) 
  content :: workspace > dashbord
  ✓ part of dashbord (10861ms)
  1) "before each" hook for "dashboard__header__title"
  1 passing (11s)
  1 failing
  1) content :: workspace > dashbord "before each" hook for "dashboard__header__title":
     CypressError: cy.request() failed on:
http://localhost:1337/api/v2/users/1
The response we received from your web server was:
  > 401: Unauthorized
This was considered a failure because the status code was not '2xx' or '3xx'.
If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'
-----------------------------------------------------------
The request we sent was:
Method: PUT
URL: http://localhost:1337/api/v2/users/1
Headers: {
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/3.2.0 Chrome/59.0.3071.115 Electron/1.8.2 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate",
  "content-type": "application/json",
  "content-length": 70
}
Body: {"lang":"en","public_name":"Global manager","timezone":"Europe/Paris"}
-----------------------------------------------------------
The response we got was:
Status: 401 - Unauthorized
Headers: {
  "connection": "close",
  "content-length": "3155",
  "content-type": "application/json",
  "date": "Mon, 06 May 2019 23:17:29 GMT",
  "server": "waitress",
  "set-cookie": [
    "session_key=818dc991a2d96d4b0f974c85f76672b83c9a080e73fce54bc8114bafa1822a9ce4cb0ae4; expires=Sun, 06-May-2018 23:17:29 GMT; Path=/; SameSite=Lax"
  ]
}
Body: {
  "message": "User not found",
  "details": {
    "error_detail": {},
    "traceback": "Traceback (most recent call last):\n  File \"/home/travis/build/tracim/tracim/backend/tracim_backend/lib/utils/request.py\", line 320, in _get_current_user_id\n    \"You request a current user \" \"but the context not permit to found one\"\ntracim_backend.exceptions.UserNotFoundInTracimRequest: You request a current user but the context not permit to found one\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pyramid/tweens.py\", line 41, in excview_tween\n    response = handler(request)\n  File \"/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pyramid/router.py\", line 148, in handle_request\n    registry, request, context, context_iface, view_name\n  File \"/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pyramid/view.py\", line 657, in _call_view\n    response = view_callable(context, request)\n  File \"/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pyramid/viewderivers.py\", line 325, in secured_view\n    return view(context, request)\n  File \"/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pyramid/viewderivers.py\", line 401, in viewresult_to_response\n    result = view(context, request)\n  File \"/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pyramid/viewderivers.py\", line 95, in mapped_view\n    return _mapped_view(context, request)\n  File \"/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/hapic/hapic.py\", line 173, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/travis/build/tracim/tracim/backend/tracim_backend/lib/utils/authorization.py\", line 287, in wrapper\n    authorization_checker.check(tracim_context=request)\n  File \"/home/travis/build/tracim/tracim/backend/tracim_backend/lib/utils/authorization.py\", line 224, in check\n    raise exception_to_raise\n  File \"/home/travis/build/tracim/tracim/backend/tracim_backend/lib/utils/authorization.py\", line 219, in check\n    authorization_checker.check(tracim_context=tracim_context)\n  File \"/home/travis/build/tracim/tracim/backend/tracim_backend/lib/utils/authorization.py\", line 89, in check\n    if tracim_context.current_user.profile.id >= self.profile_level:\n  File \"/home/travis/build/tracim/tracim/backend/tracim_backend/lib/utils/request.py\", line 55, in current_user\n    return self._generate_if_none(self._current_user, self._get_user, self._get_current_user_id)\n  File \"/home/travis/build/tracim/tracim/backend/tracim_backend/lib/utils/request.py\", line 136, in _generate_if_none\n    return generator(id_fetcher)\n  File \"/home/travis/build/tracim/tracim/backend/tracim_backend/lib/utils/request.py\", line 140, in _get_user\n    user_id = user_id_fetcher()\n  File \"/home/travis/build/tracim/tracim/backend/tracim_backend/lib/utils/request.py\", line 323, in _get_current_user_id\n    raise NotAuthenticated(\"User not found\") from exc\ntracim_backend.exceptions.NotAuthenticated: User not found\n"
  },
  "code": null
}
Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'content :: workspace > dash...'
      at Object.cypressErr (http://localhost:1337/__cypress/runner/cypress_runner.js:65727:11)
      at Object.throwErr (http://localhost:1337/__cypress/runner/cypress_runner.js:65692:18)
      at Object.throwErrByPath (http://localhost:1337/__cypress/runner/cypress_runner.js:65719:17)
      at http://localhost:1337/__cypress/runner/cypress_runner.js:56990:20
      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:131273:23)
      at Promise._settlePromiseFromHandler (http://localhost:1337/__cypress/runner/cypress_runner.js:129291:31)
      at Promise._settlePromise (http://localhost:1337/__cypress/runner/cypress_runner.js:129348:18)
      at Promise._settlePromise0 (http://localhost:1337/__cypress/runner/cypress_runner.js:129393:10)
      at Promise._settlePromises (http://localhost:1337/__cypress/runner/cypress_runner.js:129472:18)
      at Async._drainQueue (http://localhost:1337/__cypress/runner/cypress_runner.js:126197:16)
      at Async._drainQueues (http://localhost:1337/__cypress/runner/cypress_runner.js:126207:10)
      at Async.drainQueues (http://localhost:1337/__cypress/runner/cypress_runner.js:126081:14)
      at <anonymous>
  (Results)
  ┌───────────────────────────────────────────────────────────┐
  │ Tests:        3                                           │
  │ Passing:      1                                           │
  │ Failing:      1                                           │
  │ Pending:      0                                           │
  │ Skipped:      1                                           │
  │ Screenshots:  0                                           │
  │ Video:        false                                       │
  │ Duration:     11 seconds                                  │
  │ Spec Ran:     workspace/content_dashboard_headerdetail.js │
  └───────────────────────────────────────────────────────────┘

~~~

**Comment by PhilippeAccorsi** [comment]
I have tested in local and I don't see any error for this test. After restarting travis job (just for the cypress job), everything is ok.

We need to investiguate to find why sometime test failed.

**Comment by inkhey** [comment]
Some investigation in code: 
seems that's beforeEach function which break code is here:

`
  beforeEach(function () {
    cy.loginAs('administrators')
    cy.visit('/ui/workspaces/1/dashboard')
  })
`
As loginAs function doesn't seems to call put method, it's seems that problem come from 
`
 cy.visit('/ui/workspaces/1/dashboard')
`
Behaviour may be something like:
- /ui/workspaces/1/dashboard page is called
- this page call a put to set user information
- this "PUT" is done with wrong/outdated/empty cookie
- test fail

I do not know why test fail sometime but not some other.

@Skylsmoi have you any idea why this test does a put on user ? Thats seems very strange.

**Comment by inkhey** [comment]
As discussed with @Skylsmoi, origin of the error come probably from mechanism who save automatically user lang.

**Comment by PhilippeAccorsi** [comment]
This problem arrived sometime. we need to find solution very quickly.

**Comment by lebouquetin** [comment]
interesting. https://stackoverflow.com/questions/54732818/how-do-i-wait-until-a-cookie-is-set

**Comment by lebouquetin** [comment]
@Skylsmoi could you update the tests by using the `cypress-wait-until` plugin and we'll see if it fixes the random error

**Comment by PhilippeAccorsi** [comment]
The fix for this is in this PR https://github.com/tracim/tracim/pull/1720

**Comment by PhilippeAccorsi** [comment]
Wait MR 1720

**Comment by PhilippeAccorsi** [comment]
This test working good.
I close this issue.

**Comment by PhilippeAccorsi** [comment]
Finally this test failed again.
I reopen this issue.

**Comment by Skylsmoi** [comment]
Let's wait for the Cypress' fixes from @basilelegal

**Comment by raphj** [comment]
No longer relevant, our cypress tests pass nowadays.
