### ISSUE TITLE
Worker threads fail in case of uwsgi reload

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#179]
When reloading uwsgi, we get in logs the following exception:

```
Exception in thread mail_sender:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/data/tracim/releases/0.0.8/tracim/tracim/lib/daemons.py", line 173, in run
    self.worker.work()
  File "/usr/share/tracim/0.0.8/venv3.4/lib/python3.4/site-packages/rq-0.7.1-py3.4.egg/rq/worker.py", line 433, in work
    self.register_birth()
  File "/usr/share/tracim/0.0.8/venv3.4/lib/python3.4/site-packages/rq-0.7.1-py3.4.egg/rq/worker.py", line 253, in register_birth
    raise ValueError(msg.format(self.name))
ValueError: There exists an active worker named 'tracim.16004' already
```

Worker threads are probably not killed properly, so new workers fail to start.

Bypass this problem by running `service uwsgi restart` instead of `service uwsgi reload`.

TODO: fix this by killing properly workers

**Comment by algooapy** [comment]
Is this issue still relevant if `Tracim` doesn't start internal daemons anymore but instead connects to system services?

**Comment by tracim** [comment]
Yes ; for the moment services are still executed as internal daemons

**Comment by lebouquetin** [comment]
Actually, the bug will disappear in future version because processes will be separated instead of being run as threads.

TODO: document the workaround we are using in production (with kill of the process)

**Comment by lebouquetin** [comment]
Wont fix: we'll split service threads into several processes
