### ISSUE TITLE
user not see all agenda of all shared space where user is a member

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1853]
## Bug description & symptom
One user is member of 27 shared space. Agenda is activated in this all sharedpsace but this user not see all agenda when he click on agenda (en header).

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] you can see all agendas of workspace where you are a member

## How to reproduce

I don't know. Its possible to have more information by @lebouquetin 

## Impacted components

*"unknown"*

**Comment by inkhey** [comment]
problem is related to https://github.com/Kozea/Radicale/issues/715

```
14:28:45 ERROR [radicale:343][waitress] An exception occurred during PROPFIND request on '/agenda/workspace/2/': Failed to load item '040000008200E00074C5B7101A82E00800000000A0D8A8C223FFD3010000000000000000100000003EF0AC058206634E935150DCB6F1D158.ics' in 'agenda/workspace/2': Main component missing
Traceback (most recent call last):
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/radicale/storage.py", line 1426, in _get_with_metadata
    href, vobject_item, input_hash)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/radicale/storage.py", line 1304, in _store_item_cache
    content = self._item_cache_content(vobject_item, cache_hash)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/radicale/storage.py", line 1298, in _item_cache_content
    tag, start, end = xmlutils.find_tag_and_time_range(vobject_item)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/radicale/xmlutils.py", line 688, in find_tag_and_time_range
    _visit_time_ranges(vobject_item, tag, range_fn, infinity_fn)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/radicale/xmlutils.py", line 338, in _visit_time_ranges
    vobject_item.vevent_list):
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/radicale/xmlutils.py", line 332, in get_children
    raise ValueError("Main component missing")
ValueError: Main component missing
```

**Comment by inkhey** [comment]
This is related to `RECURRENCE-ID` in ics file. This happened for content who are migrated from radicale v1 version to v2, but may happened in other case (we need to investigate goal of  `RECURRENCE-ID` )

This issue happened in last stable version of radicale (2.1.11) and this was not patched explictly (issue is already opened) for upstream version. As there is huge refactor in last dev version, we cannot test it easily in tracim (radicale app launcher is broken) and check if issue is fixed here. Anyway, it's still unclear when a new version of radicale will be available.

**Comment by inkhey** [comment]
As issue happened on generic propfind endpoint and we do not have a working stable version of radicale available with fixed, we should consider:
- fixing one by one broken ics as we know what cause trouble, we need just to understand better `RECURRENCE-ID to be sure there is no reason issue happened again.
- using a patched version of radicale with the fix proposed in https://github.com/Kozea/Radicale/issues/715

**Comment by inkhey** [comment]
Broken ics fil content (`040000008200E00074C5B7101A82E00800000000A0D8A8C223FFD3010000000000000000100000003EF0AC058206634E935150DCB6F1D158.ics`)
```
BEGIN:VCALENDAR
PRODID:-//Radicale//NONSGML Radicale Server//EN
VERSION:2.0
BEGIN:VEVENT
LAST-MODIFIED:20180913T140903Z
DTSTAMP:20180913T140903Z
UID:040000008200E00074C5B7101A82E00800000000A0D8A8C223FFD3010000000000000000100000003EF0AC058206634E935150DCB6F1D158
SUMMARY:Sujet
PRIORITY:5
RECURRENCE-ID;TZID=Europe/Paris:20180913T160000
STATUS:CONFIRMED
ORGANIZER;CN=tata- externe:mailto:tata@tata.tata
ATTENDEE;RSVP=TRUE;CN=toto;PARTSTAT=NEEDS-ACTION;ROLE=OPT-PARTICIPANT:mailto:toto@toto.toto
ATTENDEE;RSVP=TRUE;CN=titi;PARTSTAT=NEEDS-ACTION;ROLE=OPT-PARTICIPANT:mailto:titi@titi.titi
DTSTART;TZID=Europe/Paris:20180913T160000
DTEND;TZID=Europe/Paris:20180913T170000
DESCRIPTION;LANGUAGE=fr-FR: Juste du texte
CLASS:PUBLIC
TRANSP:OPAQUE
SEQUENCE:1286
LOCATION;LANGUAGE=fr-FR:Groenland
X-MICROSOFT-CDO-APPT-SEQUENCE:1286
X-MICROSOFT-CDO-OWNERAPPTID:-1658296350
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MOZ-RECEIVED-SEQUENCE:1286
X-MOZ-RECEIVED-DTSTAMP:20180913T140141Z
X-RADICALE-NAME:040000008200E00074C5B7101A82E00800000000A0D8A8C223FFD3010000000000000000100000003EF0AC058206634E935150DCB6F1D158.ics
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
X-RADICALE-NAME:Europe/Berlin
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
X-RADICALE-NAME:Europe/Berlin
END:STANDARD
X-RADICALE-NAME:Europe/Berlin
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Europe/Paris
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
X-RADICALE-NAME:Europe/Paris
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
X-RADICALE-NAME:Europe/Paris
END:STANDARD
X-RADICALE-NAME:Europe/Paris
END:VTIMEZONE
END:VCALENDAR
```

**Comment by inkhey** [comment]
in fact issue is related to invalid content according to
https://github.com/Kozea/Radicale/issues/700#issuecomment-328366104
> The files `1.ics` and `2.ics` fail because of the line `RECURRENCE-ID;...`. It's used to specify a specific instance of a recurring event (and override it). The problem is that the event itself is the recurring event.

`040000008200E00074C5B7101A82E00800000000A0D8A8C223FFD3010000000000000000100000003EF0AC058206634E935150DCB6F1D158.ics` is in same case, it as recurrence_id but no recurrent event exist, so that's incorrect. In other case where we have in production recurrence_id, we do have recurrent event so syntax is correct and it work correctly.

**Comment by PhilippeAccorsi** [comment]
On production we just have one file with this problem.
