### ISSUE TITLE
Check how to avoid send b64 file for ingesting document in elasticsearch

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1877]
## Bug description & symptom

Origin:

Can you open an issue to investigate about send attachment in bytes format ? Important: note this issue as performance problematic (add label if required) because file is put in RAM as b64.

_Originally posted by @buxx in https://github.com/tracim/tracim/pull/1717_

## Expected

?

**Comment by inkhey** [comment]
this trouble cause issue related to in memory b64:

```
11:09:10 INFO  [tracim:32][b'uWSGIWorker2Core0'] [ESSearchApi] Indexing content 209
11:12:07 ERROR [tracim:41][b'uWSGIWorker2Core0'] [ContentApi] Something goes wrong during indexing of new content
Traceback (most recent call last):
  File "./tracim_backend/lib/core/content.py", line 600, in execute_created_content_actions
    search_api.index_content(content_in_context)
  File "./tracim_backend/lib/search/search.py", line 370, in index_content
    using=self.es, pipeline="attachment", index=self.index_document_alias
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch_dsl/document.py", line 448, in save
    **doc_meta
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/__init__.py", line 364, in index
    "POST", _make_path(index, doc_type, id), params=params, body=body
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 308, in perform_request
    body = self.serializer.dumps(body)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/serializer.py", line 51, in dumps
    data, default=self.default, ensure_ascii=False, separators=(",", ":")
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
MemoryError
```

**Comment by inkhey** [comment]
using apache tikka instead of ingest may be a solution for this issue.
