### ISSUE TITLE
Unexpected api error with http status 500

### ISSUE THREAD

**Issue by ecureuilfourbe** [tracim/tracim#2090]
## Bug description & symptom
When I create a new users, i get the following error message:

Erreur
Erreur inconnue, veuillez contacter un administrateur
Détail de l'erreur
Unexpected api error with http status 500

## Diagnostic

unknown

## Expected

A new user is created

## Context and version information

The tracim server run on a Ubuntu server 18.04.2 behind a corporate proxy

- Desktop environment (if applicable)
    - Windows 7
    - Firefox
    - *Version [e.g. 22]*

## How to reproduce

In my case:

1. *Go to 'my_ip:6543'*
2. *Log on as "Global manager"*
3. *Click on 'Administration' -> 'User'*
4. *Click on 'add user'*
5. *Add a user*
6. *Click on 'Create User'*
7. *See error*

## Screenshots

[url=http://zupimages.net/viewer.php?id=19/28/o9bg.png][img]https://zupimages.net/up/19/28/o9bg.png[/img][/url] 

## Impacted components

unknown

**Comment by inkhey** [comment]
Hello @ecureuilfourbe , thank for you feedback.

We have detected a similar issue in frontend( https://github.com/tracim/tracim/issues/2091). A workaround exist is by doing ctrl+F5, can you try this ?

**Comment by inkhey** [comment]
Can you provided some complementary informations in order to help us ?
1. How did you install tracim : Debian script, docker ?
2. Which version are you using : Latest, 2.3.1, 2.3 , etc... :  
you can see last stable version of tracim in ui:
![Sélection_008](https://user-images.githubusercontent.com/7851652/61056450-ac068680-a3f3-11e9-87e1-cd20b8887963.png)
3. Can you return result of request as har file:
![Sélection_002](https://user-images.githubusercontent.com/7851652/61057183-09e79e00-a3f5-11e9-88ee-58d5e7e1b72b.png)
![Sélection_003](https://user-images.githubusercontent.com/7851652/61057203-110eac00-a3f5-11e9-9af0-829900b05c73.png)
![Sélection_007](https://user-images.githubusercontent.com/7851652/61057207-153ac980-a3f5-11e9-8cdb-1a747f1104a2.png)
![Menu_005](https://user-images.githubusercontent.com/7851652/61057212-179d2380-a3f5-11e9-888e-1b52c58e36c3.png)

**Comment by ecureuilfourbe** [comment]
Hi, thank's for your reply !

How did you install tracim : Debian script, docker ? : I use Debian script
(on ubuntu server 18.04.2)
Which version are you using : Latest, 2.3.1, 2.3 , etc... : I use the
version V2.3.1

CTRL+F5 didn't help

Note: I have already create 2 users without any issues before.

**Comment by tracim** [comment]
@ecureuilfourbe you successfully created 2 users before to get the Http 500 error... What was the difference on parameters?

- Did you fill a password? 
- Which profile dis you choose?
- Was the name filled?
- Was the email valid?

Do you have configured notifications and email related parameters ?

Could you share server logs showing the error?

**Comment by inkhey** [comment]
Just some informations:
- if you return HAR as requested, don't field form with sensitive information ;-)

- if you are running tracim with pserve. Log are directly returned to standard console (stdout/stderr)
- if you are using uwsgi. Log file depend on uwsgi configuration

**Comment by ecureuilfourbe** [comment]
Hello,

   - Did you fill a password? A generic password
   - Which profile dis you choose? I choose user
   - Was the name filled? A generic name like "bob"
   - Was the email valid? The email was valid, same kind of email for other
   users

I did activate email notifications:

> ####
> # EMAIL-NOTIFICATION
> ####
>
> ## available choice: True or False
> email.notification.activated = True
>
And the last log i get just after the error:

   File
> "/home/glope/tracim/backend/tracim_backend/lib/mail_notifier/sender.py",
> line 29, in send_email_through
>     sendmail_callable(message)
>   File
> "/home/glope/tracim/backend/tracim_backend/lib/mail_notifier/sender.py",
> line 130, in send_mail
>     self.connect()  # Actually, this connects to SMTP only if required
>   File
> "/home/glope/tracim/backend/tracim_backend/lib/mail_notifier/sender.py",
> line 68, in connect
>     self._smtp_connection = smtplib.SMTP(self._smtp_config.server,
> self._smtp_config.port)
>   File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
>     (code, msg) = self.connect(host, port)
>   File "/usr/lib/python3.6/smtplib.py", line 336, in connect
>     self.sock = self._get_socket(host, port, self.timeout)
>   File "/usr/lib/python3.6/smtplib.py", line 307, in _get_socket
>     self.source_address)
>   File "/usr/lib/python3.6/socket.py", line 704, in create_connection
>     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
>   File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -3] Temporary failure in name resolution
>
> 07:32:59 INFO  [sqlalchemy.engine.base.Engine:737][waitress] ROLLBACK
>

**Comment by inkhey** [comment]
@ecureuilfourbe 
When configuring email notification, you need to setup properly `email.notification.smtp.server` and `email.notification.smtp.port` to an existing smtp server (and of course `email.notification.smtp.user` and `email.notification.smtp.password`) 

> [Errno -3] Temporary failure in name resolution

Error here mean that for the value of "email.notification.smtp.server" you set, system was not able to associated ip address (dns issue).

Thats could means:
- That the value of `email.notification.smtp.server` is incorrect
- That server in your environnement is not set properly to allow tracim doing properly dns resolution (converting mysupersite.com to 127.0.0.1 ip for example).

Can you check `email.notification.smtp.server` and/or dns resolution in you system (you should be able to ping `email.notification.smtp.server` value) ?

**Comment by ecureuilfourbe** [comment]
Ok thank's for the response, i will try this

**Comment by Skylsmoi** [comment]
I got the same error on our preprod server on this endpoint:
`/api/workspaces/24/folders/794`

and I have the following related logs (tracim_web.log):

```bash
2024-07-11 15:08:53 INFO  [tracim:44][uWSGIWorker3Core0] [TracimRequest] GET /api/workspaces/24/folders/794 from authenticated user 2
2024-07-11 15:08:53 INFO  [tracim:44][uWSGIWorker1Core0] [TracimRequest] GET /api/workspaces/45/contents from authenticated user 4
2024-07-11 15:08:53 INFO  [PreviewGenerator:22][uWSGIWorker1Core2] New Preview builder of class<class 'preview_generator.preview.builder.image__wand.ImagePreviewBuilderWand'>
2024-07-11 15:08:53 INFO  [tracim:44][uWSGIWorker3Core0] [TracimRequest] GET /api/workspaces/24/folders/794 from authenticated user 2
2024-07-11 15:08:53 INFO  [tracim:44][uWSGIWorker2Core1] [TracimRequest] GET /api/workspaces/39/files/677 from authenticated user 35
[pid: 3396|app: 0|req: 5252/32360] 10.91.231.98 () {76 vars in 1489 bytes} [Thu Jul 11 15:08:52 2024] GET /api/workspaces/1/threads/96 => generated 1168 bytes in 197 msecs (HTTP/1.1 200) 2 headers in 76 bytes (1 switches on core 0)
2024-07-11 15:08:53 INFO  [PreviewGenerator:22][uWSGIWorker1Core2] New Preview builder of class<class 'preview_generator.preview.builder.image__wand.ImagePreviewBuilderWand'>
[pid: 3404|app: 0|req: 10810/32361] 10.91.231.98 () {82 vars in 1535 bytes} [Thu Jul 11 15:08:52 2024] GET /api/contents/794 => generated 155 bytes in 158 msecs (HTTP/1.1 302) 4 headers in 168 bytes (1 switches on core 1)
2024-07-11 15:08:53 WARNI [tracim:47][uWSGIWorker1Core2] [StorageLib] Unknown Preview_Generator Exception Occured
Traceback (most recent call last):
  File "./tracim_backend/lib/core/storage.py", line 132, in preview_generator_filepath_context
    yield from self.get_filepath(
  File "./tracim_backend/lib/core/storage.py", line 105, in get_filepath
    yield from self._get_valid_content_filepath_legacy(depot_stored_file)
  File "./tracim_backend/lib/core/storage.py", line 362, in _get_valid_content_filepath_legacy
    yield depot_stored_file._file_path
  File "./tracim_backend/lib/core/storage.py", line 178, in get_jpeg_preview
    jpg_preview_path = self.preview_manager.get_jpeg_preview(
  File "/usr/local/lib/python3.9/dist-packages/preview_generator/manager.py", line 202, in get_jpeg_preview
    preview_context.builder.build_jpeg_preview(
  File "/usr/local/lib/python3.9/dist-packages/preview_generator/preview/builder/image__wand.py", line 137, in build_jpeg_preview
    self.image_to_jpeg_wand(file_path, size, dest_path, mimetype=mimetype)
  File "/usr/local/lib/python3.9/dist-packages/preview_generator/preview/builder/image__wand.py", line 143, in image_to_jpeg_wand
    with self._convert_image(file_path, preview_dims) as img:
  File "/usr/local/lib/python3.9/dist-packages/preview_generator/preview/builder/image__wand.py", line 162, in _convert_image
    img = Image(filename=file_path)
  File "/usr/local/lib/python3.9/dist-packages/wand/image.py", line 9110, in __init__
    self.read(filename=filename)
  File "/usr/local/lib/python3.9/dist-packages/wand/image.py", line 9705, in read
    self.raise_exception()
  File "/usr/local/lib/python3.9/dist-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.MissingDelegateError: no decode delegate for this image format `' @ error/constitute.c/ReadImage/587
```

First line of log is the call from frontend.

I'm not 100% sure that the right information is in this log. I don't have anything else.
