### ISSUE TITLE
Unable to connect to tracim with ldap user/password

### ISSUE THREAD

**Issue by ecureuilfourbe** [tracim/tracim#2094]
## Bug description & symptom

When i try to log in to tracim with my ldap user and password, tracim return the error:
-email invalid
## Diagnostic

Unknown

## Expected

The log is succesful 

## Context and version information

The tracim server run on a Ubuntu server 18.04.2 behind a corporate proxy

    Desktop environment (if applicable)
        Windows 7
        Firefox
        Version 52.6.0 (64 bits) 

## How to reproduce

In my case

1. *Go to tracim login page*
2. *Enter my ldap user* (So without @something.thing)
3. *Enter my ldap password*
4. *See error*

## Screenshots

*Please consider sharing a [animated GIF screencast generated with peek](https://github.com/phw/peek)* 

## Impacted components

unknown

## Extra information

```
## auth_type 'remote' is not allowed there, set remote_auth_header.
auth_types = ldap
# If auth_type is ldap, uncomment following ldap_* parameters
## LDAP server address
ldap_url = ldap://XXX.XXX:389
## Base dn to make queries
ldap_base_dn = dc=XXX,dc=XXXX,dc=XX
## Bind dn to identify the search
ldap_bind_dn = cn=XXXX,cn=users,dc=XXXX,dc=XXXXX,dc=fr
## The bind password
ldap_bind_pass = XXxXXxXX
## Base dn to make queries of users
ldap_user_base_dn = cn=users,dc=XXXXX,dc=XXXXX,dc=fr
## Attribute name of user record who contain user login (email)
ldap_login_attribute = mail=email
## Attribute for default name of new user from ldap
ldap_name_attributes = givenName
## TLS usage to communicate with your LDAP server
; ldap_tls = False

```

**Comment by inkhey** [comment]
Thank for feedback,

If i understood your situation:
- you have set auth of tracim to ldap-only.
- you have configured ldap with an existing and working ldap server according to part of config given.
- you have in ldap schema for user a field "mail" containing email adress of user.
- you have also in ldap schema for user a field "givenName" containing name of user.
- you don't use tls for ldap connection (default value is false).
- you have an ldap user like "Toto" (givenName) with mail "toto@toto.toto" .
- you tried to login with something like "Toto" in first field and associated ldap password like this image:

![Capture du 2019-07-15 17-35-23](https://user-images.githubusercontent.com/7851652/61228814-48e45f00-a727-11e9-853c-a3cf2360fdf3.png)

If all this is correct, did you try put full email_adress instead of only GivenName: like "toto@toto.toto"  in my example ? Is it working ?

**Comment by ecureuilfourbe** [comment]
So I may not have a email field for each user I'm not sure, I need to ask to the admin. Is there another way to log in without an email address? 

⁣Envoyé par BlueMail ​

Le 15 juil. 2019 à 17:41, à 17:41, inkhey <notifications@github.com> a écrit:

**Comment by ecureuilfourbe** [comment]
So, we have email field for ldap user.

**Comment by ecureuilfourbe** [comment]
So, we have email field for ldap user.

**Comment by ecureuilfourbe** [comment]
So, we have email field for ldap user.
And I can't edit my previous post

**Comment by inkhey** [comment]
> So I may not have a email field for each user I'm not sure, I need to ask to the admin. Is there another way to log in without an email address? 

Auth mecanism of tracim rely on email address as login, so, that's not possible to log in without them.
If you really need to have account without true email, you can, if you disable email notification, put account with fake email address like "fake@fake.fake" ( web UI doesn't allow to do this if email notification is enabled and that's not recommanded to do this if you enable email notification as this mean that you will cause trouble to email server by asking them to send email to an unknown domain).


> So, we have email field for ldap user.
> And I can't edit my previous post

Does authentification work with email field ?

**Comment by ecureuilfourbe** [comment]
Hey, I try with the email (as login) and the password of an ldap user but it return the same error. So i don't know.

**Comment by inkhey** [comment]
@ecureuilfourbe 
Can you set to English version and check if the error message you receive is  
`Not a valid email` or `Email or password invalid`  or something else ?

If you get `Not a valid email`, check if you password is 6+ characters long. We expect in all case a password from 6 to 512 character, error message is clearly unclear in this case, that's a bug.

If you get `Email or password invalid`, you should have a big backend log about the issue, please post it entirely here (you can, of course, change email showed in log to something else for security concern).

**Comment by ecureuilfourbe** [comment]
I'm pretty sure the error message says "Email or password invalid", and I can't find your "big backend log"

**Comment by inkhey** [comment]
> I'm pretty sure the error message says "Email or password invalid", and I can't find your "big backend log"

not sure what you mean about "can't find". Backend log are returned by default on stdout/sderr with pserve.

You should get something similar to this:

```
15:08:42 INFO  [hapic:203][waitress] Exception AuthenticationFailed occured, return 403 http_code : User "test@test.test" authentication failed
15:08:42 DEBUG [hapic:206][waitress] Traceback (most recent call last):
  File "/home/user/Public/tracim/backend/tracim_backend/lib/core/user.py", line 486, in _authenticate
    return self._internal_db_authenticate(user, email, password)
  File "/home/user/Public/tracim/backend/tracim_backend/lib/core/user.py", line 335, in _internal_db_authenticate
    raise UserDoesNotExist("User {} not found in database".format(email))
tracim_backend.exceptions.UserDoesNotExist: User test@test.test not found in database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/hapic.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/user/Public/tracim/backend/tracim_backend/views/core_api/session_controller.py", line 43, in login
    user = uapi.authenticate(login.email, login.password, ldap_connector)
  File "/home/user/Public/tracim/backend/tracim_backend/lib/core/user.py", line 452, in authenticate
    raise exc
  File "/home/user/Public/tracim/backend/tracim_backend/lib/core/user.py", line 450, in authenticate
    return self._authenticate(email, password, ldap_connector, auth_type=auth_type)
  File "/home/user/Public/tracim/backend/tracim_backend/lib/core/user.py", line 497, in _authenticate
    raise AuthenticationFailed('User "{}" authentication failed'.format(email)) from exc
tracim_backend.exceptions.AuthenticationFailed: User "test@test.test" authentication failed
```

Did you get something ?

**Comment by inkhey** [comment]
Another thing: 
In tracim, account are linked to a specific auth type. If you have activated an account "test@test.test" with normal auth mecanism (you need to create account and login one time with it)
If you tried to authentificate to the same account with ldap, it will not work because account is hard-linked to database authentification instead of ldap.

**Comment by ecureuilfourbe** [comment]
Oh ! so it's not a .log file, my bad.
that's the log:
12:59:49 INFO  [sqlalchemy.engine.base.Engine:737][waitress] ROLLBACK
12:59:58 INFO  [sqlalchemy.engine.base.Engine:717][waitress] BEGIN (implicit)
12:59:58 INFO  [sqlalchemy.engine.base.Engine:1209][waitress] SELECT users.password AS users_password, users.user_id AS users_user_id, users.email AS users_email, users.display_name AS users_display_name, users.created AS users_created, users.is_active AS users_is_active, users.is_deleted AS users_is_deleted, users.imported_from AS users_imported_from, users.timezone AS users_timezone, users.auth_type AS users_auth_type, users.lang AS users_lang, users.auth_token AS users_auth_token, users.auth_token_created AS users_auth_token_created, users.reset_password_token_hash AS users_reset_password_token_hash, users.reset_password_token_created AS users_reset_password_token_created
FROM users
WHERE users.is_deleted = 0 AND users.email = ?
12:59:58 INFO  [sqlalchemy.engine.base.Engine:1211][waitress] ('fabienne.yver@ch-avranches-granville.fr',)
12:59:58 INFO  [hapic:203][waitress] Exception AuthenticationFailed occured, return 403 http_code : User "fabienne.yver@ch-avranches-granville.fr" authentication failed
12:59:58 DEBUG [hapic:206][waitress] Traceback (most recent call last):
  File "/home/glope/tracim/backend/tracim_backend/lib/core/user.py", line 483, in _authenticate
    return self._ldap_authenticate(user, email, password, ldap_connector)
  File "/home/glope/tracim/backend/tracim_backend/lib/core/user.py", line 268, in _ldap_authenticate
    raise WrongLDAPCredentials("LDAP credentials are not correct")
tracim_backend.exceptions.WrongLDAPCredentials: LDAP credentials are not correct

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/glope/tracim/backend/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/glope/tracim/backend/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/home/glope/tracim/backend/env/lib/python3.6/site-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/home/glope/tracim/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/home/glope/tracim/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/home/glope/tracim/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/home/glope/tracim/backend/env/lib/python3.6/site-packages/hapic/hapic.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/home/glope/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/glope/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/glope/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/glope/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/glope/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/glope/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/glope/tracim/backend/tracim_backend/views/core_api/session_controller.py", line 43, in login
    user = uapi.authenticate(login.email, login.password, ldap_connector)
  File "/home/glope/tracim/backend/tracim_backend/lib/core/user.py", line 452, in authenticate
    raise exc
  File "/home/glope/tracim/backend/tracim_backend/lib/core/user.py", line 450, in authenticate
    return self._authenticate(email, password, ldap_connector, auth_type=auth_type)
  File "/home/glope/tracim/backend/tracim_backend/lib/core/user.py", line 497, in _authenticate
    raise AuthenticationFailed('User "{}" authentication failed'.format(email)) from exc
tracim_backend.exceptions.AuthenticationFailed: User "fabienne.yver@ch-avranches-granville.fr" authentication failed

12:59:58 INFO  [sqlalchemy.engine.base.Engine:737][waitress] ROLLBACK

**Comment by inkhey** [comment]
>  tracim_backend.exceptions.WrongLDAPCredentials: LDAP credentials are not correct

Look like ldap authentification failed. This may mean:
- email does not match. Are you sure there is no uppercase in mail field of user in ldap ?
- password does not match. Are you sure password is setted in userPassword field ?

By the way, which ldap server did you use ? We did test with openldap.

**Comment by ecureuilfourbe** [comment]
Nevermind, thank you for your help, we don't use tracim anymore, but love i do realy like Tracim, have a nice day.

**Comment by lebouquetin** [comment]
@ecureuilfourbe could you explain why you tried to use tracim and why you gave up? Thanks for your feedback

**Comment by ecureuilfourbe** [comment]
@lebouquetin It was just a test and at the end Tracim didn't match our needs, but i'll not hesitate to talk about it around me.
Have a nice day

ecureuilfourbe

**Comment by lebouquetin** [comment]
@ecureuilfourbe I understand what you write, my question more precisely was actually: "what are your needs and why tracim did not match them?". Example: you want to create a knowledge database but feature xxx is missing (and bonus: what software did you choose).

Have a good day.

Lebouquetin

**Comment by ecureuilfourbe** [comment]
Honestly i'm just a trainee and my supervisor takes the decision without any explanation, but i guess he was looking for a kind of "intra-chat" solution or something like that. I told him for the different chat system in tracim, like the threads, but meh, you never know.
