### ISSUE TITLE
3.5 and 3.6 versions of Python induce the authentication logout test to fail

### ISSUE THREAD

**Issue by algooapy** [tracim/tracim#221]
here is the corresponding output:

```
======================================================================
FAIL: tracim.tests.functional.test_authentication.TestAuthentication.test_logout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "[...]/tracim/3.6_venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "[...]/tracim/tracim/tracim/tests/functional/test_authentication.py", line 92, in test_logout
    'Session cookie was not deleted: %s' % home_page.request.cookies)
AssertionError: Session cookie was not deleted: <RequestCookies (dict-like) with values {'authtkt': 'a12d01707072de7e96ac0630c6b8cf8a5922ff0aadmin%40admin.admin!', 'webflash': '%7B%22message%22%3A%20%22Welcome%2$back%2C%20Global%20manager%21%22%2C%20%22status%22%3A%20%22ok%22%7D'}>
```

**Comment by lebouquetin** [comment]
Maybe the reason is that genshi is not supporting python 3.5/3.6 ? - https://groups.google.com/forum/#!topic/turbogears/00TDjv_x28U

**Comment by algooapy** [comment]
Well, doesn't seem that genshi is involved because mako is the default renderer. In fact we are completely able to drop genshi as is, it is no longer required to run/test tracim.
