### ISSUE TITLE
no preview available for svg file

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2492]
## Bug description & symptom

When I upload svg file (ex with this file [img_accueil.zip](https://github.com/tracim/tracim/files/3756662/img_accueil.zip ), tracim does not show preview. I can see this log:

~~~
2019-10-22 15:04:41 INFO  [PreviewGenerator:24][waitress] New Preview builder of class<class 'preview_generator.preview.builder.image__inkscape.ImagePreviewBuilderInkscape'>
2019-10-22 15:04:41 INFO  [PreviewGenerator:24][waitress] New Preview builder of class<class 'preview_generator.preview.builder.image__inkscape.ImagePreviewBuilderInkscape'>
2019-10-22 15:04:41 INFO  [PreviewGenerator:24][waitress] New Preview builder of class<class 'preview_generator.preview.builder.image__inkscape.ImagePreviewBuilderInkscape'>
2019-10-22 15:04:41 INFO  [PreviewGenerator:24][waitress] New Preview builder of class<class 'preview_generator.preview.builder.image__inkscape.ImagePreviewBuilderInkscape'>
2019-10-22 15:04:41 INFO  [PreviewGenerator:24][waitress] New Preview builder of class<class 'preview_generator.preview.builder.image__inkscape.ImagePreviewBuilderInkscape'>
2019-10-22 15:04:41 INFO  [hapic:679][waitress] Exception UnavailablePreview occured, return 400 http_code : No preview available for content 36, revision 130
2019-10-22 15:04:41 DEBUG [hapic:684][waitress] Traceback (most recent call last):
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/preview_generator/preview/builder_factory.py", line 47, in get_preview_builder
    return self._builder_classes[mimetype]()  # nopep8 get class and instantiate it
KeyError: 'image/svg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/algoo/repo/tracim/backend/tracim_backend/lib/core/content.py", line 1061, in get_jpg_preview_path
    file_path, page=page_number, width=width, height=height, file_ext=file_extension
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/preview_generator/manager.py", line 164, in get_jpeg_preview
    builder = self._factory.get_preview_builder(mimetype)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/preview_generator/preview/builder_factory.py", line 49, in get_preview_builder
    raise UnsupportedMimeType("Unsupported mimetype: {}".format(mimetype))
preview_generator.exception.UnsupportedMimeType: Unsupported mimetype: image/svg

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 657, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 657, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 657, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/algoo/repo/tracim/backend/env/lib/python3.6/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/algoo/repo/tracim/backend/tracim_backend/views/contents_api/file_controller.py", line 565, in sized_preview_jpg_revision
    file_extension=revision.file_extension,
  File "/home/algoo/repo/tracim/backend/tracim_backend/lib/core/content.py", line 1070, in get_jpg_preview_path
    ) from exc
tracim_backend.exceptions.UnavailablePreview: No preview available for content 36, revision 130

2019-10-22 15:04:41 INFO  [PreviewGenerator:24][waitress] New Preview builder of class<class 'preview_generator.preview.builder.image__inkscape.ImagePreviewBuilderInkscape'>
2019-10-22 15:04:41 INFO  [PreviewGenerator:24][waitress] New Preview builder of class<class 'preview_generator.preview.builder.image__inkscape.ImagePreviewBuilderInkscape'>
2019-10-22 15:04:41 INFO  [PreviewGenerator:24][waitress] New Preview builder of class<class 'preview_generator.preview.builder.image__inkscape.ImagePreviewBuilderInkscape'>
~~~

## Diagnostic

The detected mimetype is `image/svg`; preview-generator is expecting `image/svg+xml` for SVG preview (preview-generator 0.11 is packaged with this version of tracim)

## Expected

- [ ] preview working also for svg file.

## Context and version information

- tested on local installation of tracim (starting with pserve)
- tested on docker image (with image 2.4.3)
- tracim 2.4.3 is based on preview-generator 0.11

## How to reproduce

run tracim with docker image 2.4.3, import a svg file.

## Impacted components

- preview-generator

Note: this may be related to OS configuration of MIME type detection. To be discussed with @inkhey who worked on this subject.

**Comment by PhilippeAccorsi** [comment]
Need test with new preview-generator version 0.12

**Comment by inkhey** [comment]
This work correctly with fix https://github.com/tracim/tracim/pull/2509 .

**Comment by PhilippeAccorsi** [comment]
Verified on 2.4.4
