### ISSUE TITLE
this test share/new_share_download_spec.js failed randomly

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2522]
## Bug description & symptom

This test `share/new_share_download_spec.js` failed randomly, and I seen we have adding wait(1000) in this test. We need to find better solution or make bigger value in this `wait()`.

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] test not failed randomly

## Context and version information

Test running in travis.

## Impacted components

- cypress test

## Extra information
Travis log
~~~
Running:  share/new_share_download_spec.js                                              (53 of 80)

  New share download form

  ✓ nominal case (9359ms)

  1) separating emails by space then pressing Enter, should separate the emails by new line

  ✓ separating emails by commas then pressing Enter, should separate the emails by new line (8800ms)

    protected by password

  ✓ Should include the input (5903ms)

  ✓ Should be possible to unhide the password (7198ms)

  4 passing (1m)

  1 failing

  1) New share download form separating emails by space then pressing Enter, should separate the emails by new line:

     CypressError: Timed out retrying: Expected to find content: 'email1@email1.email1

email2@email2.email2

email1@email3.email3' within the element: <textarea.shareDownload__email__input.form-control> but never did.

      at Object.cypressErr (http://localhost:1337/__cypress/runner/cypress_runner.js:104968:11)

      at Object.throwErr (http://localhost:1337/__cypress/runner/cypress_runner.js:104923:18)

      at Object.throwErrByPath (http://localhost:1337/__cypress/runner/cypress_runner.js:104955:17)

      at retry (http://localhost:1337/__cypress/runner/cypress_runner.js:96290:16)

      at onFailFn (http://localhost:1337/__cypress/runner/cypress_runner.js:85359:16)

      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:139045:23)

      at Promise._settlePromiseFromHandler (http://localhost:1337/__cypress/runner/cypress_runner.js:136981:31)

      at Promise._settlePromise (http://localhost:1337/__cypress/runner/cypress_runner.js:137038:18)

      at Promise._settlePromise0 (http://localhost:1337/__cypress/runner/cypress_runner.js:137083:10)

      at Promise._settlePromises (http://localhost:1337/__cypress/runner/cypress_runner.js:137158:18)

      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:1337/__cypress/runner/cypress_runner.js:133770:16)

      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:1337/__cypress/runner/cypress_runner.js:133780:10)

      at Async.drainQueues (http://localhost:1337/__cypress/runner/cypress_runner.js:133654:14)
~~~

**Comment by inkhey** [comment]
@MariePrandstetter @Haskaris Is this issue about random failing test still up to date ?

**Comment by Haskaris** [comment]
The test doesn't seem to fail anymore.
But, it should be nice to remove the `cy.wait(1000)` from the test.

**Comment by raphj** [comment]
Let's close this anyway.
