### ISSUE TITLE
CALDAV not working on IOS 13.3.2, error ssl or account verification (tracim run with docker container)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2581]
## Bug description & symptom

Its not possible to connect agenda to IOS, if I save configuration on phone, I can see the naming of config used my username but `@` is changed to `%40` (maybe ios send username with this and tracim not understand this.

## Diagnostic

When ios request is send to tracim, we can seen this error log on serveur:
~~~
==> /{log container tracim}/tracim_web.log <==
2019-12-10 15:01:06 INFO  [hapic:203][b'uWSGIWorker1Core0'] Exception CaldavNotAuthenticated occured, return 401 http_code : 
2019-12-10 15:01:06 DEBUG [hapic:206][b'uWSGIWorker1Core0'] Traceback (most recent call last):
  File "./tracim_backend/lib/utils/request.py", line 339, in _get_current_user_id
    "You request a current user " "but the context not permit to found one"
tracim_backend.exceptions.UserNotFoundInTracimRequest: You request a current user but the context not permit to found one

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./tracim_backend/lib/agenda/authorization.py", line 130, in check
    return self.checker.check(tracim_context)
  File "./tracim_backend/lib/agenda/authorization.py", line 62, in check
    if not tracim_context.current_workspace.agenda_enabled:
  File "./tracim_backend/lib/utils/request.py", line 66, in current_workspace
    self._current_workspace, self._get_workspace, self._get_current_workspace_id
  File "./tracim_backend/lib/utils/request.py", line 137, in _generate_if_none
    return generator(id_fetcher)
  File "./tracim_backend/lib/utils/request.py", line 148, in _get_workspace
    current_user=self.current_user,
  File "./tracim_backend/lib/utils/request.py", line 56, in current_user
    return self._generate_if_none(self._current_user, self._get_user, self._get_current_user_id)
  File "./tracim_backend/lib/utils/request.py", line 137, in _generate_if_none
    return generator(id_fetcher)
  File "./tracim_backend/lib/utils/request.py", line 141, in _get_user
    user_id = user_id_fetcher()
  File "./tracim_backend/lib/utils/request.py", line 342, in _get_current_user_id
    raise NotAuthenticated("User not found") from exc
tracim_backend.exceptions.NotAuthenticated: User not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/hapic/hapic.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 657, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "./tracim_backend/lib/utils/authorization.py", line 306, in wrapper
    authorization_checker.check(tracim_context=request)
  File "./tracim_backend/lib/agenda/authorization.py", line 132, in check
    raise CaldavNotAuthenticated() from exc
tracim_backend.exceptions.CaldavNotAuthenticated

[pid: 681|app: 0|req: 25428/87965] 127.0.0.1 () {46 vars in 684 bytes} [Tue Dec 10 15:01:06 2019] PROPFIND /agenda/workspace/94/ => generated 84 bytes in 5 msecs (HTTP/1.1 401) 3 headers in 273 bytes (1 switches on core 0)

==> /{log container tracim}/apache2-access.log <==
172.18.0.1 - - [10/Dec/2019:15:01:06 +0000] "PROPFIND /agenda/workspace/94/ HTTP/1.1" 401 520 "-" "iOS/13.2.3 (17B111) accountsd/1.0"

==> /{log proxy apache}/apache2-access.log <==
81.185.174.150 - - [10/Dec/2019:16:01:06 +0100] "PROPFIND /agenda/workspace/94/ HTTP/1.1" 401 6080 "-" "iOS/13.2.3 (17B111) accountsd/1.0"

==> /{log container tracim}/tracim_caldav.log <==
2019-12-10 15:01:06 INFO  [radicale:409][b'uWSGIWorker2Core7'] PROPFIND request for '/agenda/workspace/94/' with depth '0' received from '81.185.174.150, 172.18.0.1' (forwarded by 127.0.0.1) using 'iOS/13.2.3 (17B111) accountsd/1.0'
2019-12-10 15:01:06 INFO  [radicale:471][b'uWSGIWorker2Core7'] Successful login: 'tracim'
2019-12-10 15:01:06 INFO  [radicale:387][b'uWSGIWorker2Core7'] PROPFIND response status for '/agenda/workspace/94/' with depth '0' in 0.002 seconds: 207 Multi-Status
[pid: 672|app: 0|req: 57951/69410] 127.0.0.1 () {48 vars in 732 bytes} [Tue Dec 10 15:01:06 2019] PROPFIND /agenda/workspace/94/ => generated 277 bytes in 2 msecs (HTTP/1.1 207) 8 headers in 538 bytes (1 switches on core 7)

==> /{log container tracim}/tracim_web.log <==
[pid: 681|app: 0|req: 25429/87966] 127.0.0.1 () {48 vars in 752 bytes} [Tue Dec 10 15:01:06 2019] PROPFIND /agenda/workspace/94/ => generated 457 bytes in 48 msecs (HTTP/1.1 207) 7 headers in 653 bytes (1 switches on core 0)

==> /{log container tracim}/apache2-access.log <==
172.18.0.1 - - [10/Dec/2019:15:01:06 +0000] "PROPFIND /agenda/workspace/94/ HTTP/1.1" 207 1274 "-" "iOS/13.2.3 (17B111) accountsd/1.0"

==> /{log proxy apache}/apache2-access.log <==
81.185.174.150 - - [10/Dec/2019:16:01:06 +0100] "PROPFIND /agenda/workspace/94/ HTTP/1.1" 207 1509 "-" "iOS/13.2.3 (17B111) accountsd/1.0"

==> /{log container tracim}/apache2-access.log <==
172.18.0.1 - - [10/Dec/2019:15:01:06 +0000] "OPTIONS /tracim/ HTTP/1.1" 200 266 "-" "iOS/13.2.3 (17B111) accountsd/1.0"

==> /{log proxy apache}/apache2-access.log <==
81.185.174.150 - - [10/Dec/2019:16:01:06 +0100] "OPTIONS /tracim/ HTTP/1.1" 200 349 "-" "iOS/13.2.3 (17B111) accountsd/1.0"

==> /{log container tracim}/tracim_web.log <==
2019-12-10 15:01:09 INFO  [hapic:203][b'uWSGIWorker2Core0'] Exception CaldavNotAuthenticated occured, return 401 http_code : 
2019-12-10 15:01:09 DEBUG [hapic:206][b'uWSGIWorker2Core0'] Traceback (most recent call last):
  File "./tracim_backend/lib/utils/request.py", line 339, in _get_current_user_id
    "You request a current user " "but the context not permit to found one"
tracim_backend.exceptions.UserNotFoundInTracimRequest: You request a current user but the context not permit to found one

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./tracim_backend/lib/agenda/authorization.py", line 130, in check
    return self.checker.check(tracim_context)
  File "./tracim_backend/lib/agenda/authorization.py", line 62, in check
    if not tracim_context.current_workspace.agenda_enabled:
  File "./tracim_backend/lib/utils/request.py", line 66, in current_workspace
    self._current_workspace, self._get_workspace, self._get_current_workspace_id
  File "./tracim_backend/lib/utils/request.py", line 137, in _generate_if_none
    return generator(id_fetcher)
  File "./tracim_backend/lib/utils/request.py", line 148, in _get_workspace
    current_user=self.current_user,
  File "./tracim_backend/lib/utils/request.py", line 56, in current_user
    return self._generate_if_none(self._current_user, self._get_user, self._get_current_user_id)
  File "./tracim_backend/lib/utils/request.py", line 137, in _generate_if_none
    return generator(id_fetcher)
  File "./tracim_backend/lib/utils/request.py", line 141, in _get_user
    user_id = user_id_fetcher()
  File "./tracim_backend/lib/utils/request.py", line 342, in _get_current_user_id
    raise NotAuthenticated("User not found") from exc
tracim_backend.exceptions.NotAuthenticated: User not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/hapic/hapic.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 657, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "./tracim_backend/lib/utils/authorization.py", line 306, in wrapper
    authorization_checker.check(tracim_context=request)
  File "./tracim_backend/lib/agenda/authorization.py", line 132, in check
    raise CaldavNotAuthenticated() from exc
tracim_backend.exceptions.CaldavNotAuthenticated

[pid: 682|app: 0|req: 62538/87967] 127.0.0.1 () {46 vars in 680 bytes} [Tue Dec 10 15:01:09 2019] PROPFIND /agenda/workspace/94/ => generated 84 bytes in 6 msecs (HTTP/1.1 401) 3 headers in 273 bytes (1 switches on core 0)

==> /{log container tracim}/apache2-access.log <==
172.18.0.1 - - [10/Dec/2019:15:01:09 +0000] "PROPFIND /agenda/workspace/94/ HTTP/1.1" 401 519 "-" "iOS/13.2.3 (17B111) accountsd/1.0"

==> /{log proxy apache}/apache2-access.log <==
81.185.174.150 - - [10/Dec/2019:16:01:09 +0100] "PROPFIND /agenda/workspace/94/ HTTP/1.1" 401 6080 "-" "iOS/13.2.3 (17B111) accountsd/1.0"
~~~

## Expected

- [ ] its possible to connect tracim agenda to ios.

## Context and version information

- Smartphone/Tablet (if applicable)
    - *Device: iPhone*
    - *OS: IOS 13.3.2*

## How to reproduce

Add caldav account on ios.

## Impacted components

*If unsure, write "unknown"*

## Extra information

**Comment by lebouquetin** [comment]
@PhilippeAccorsi @inkhey you should add tracking about user name / user id in order to be able to understand.
