### ISSUE TITLE
Solve database schema creation with newer versions of MySQL/MariaDB

### ISSUE THREAD

**Issue by algooapy** [tracim/tracim#290]
This should be as simple as adding the following line to `MySQL` section of `doc/database.md`:
```
ALTER SCHEMA tracimdb DEFAULT CHARACTER SET utf8 ;
```

**Comment by algooapy** [comment]
Not that simple...
The default MySQL character set in Debian is `utf8mb4`. The corresponding setting in `development.ini` is:
```
sqlalchemy.url = mysql+pymysql://tracimuser:tracimpassword@127.0.0.1/tracimdb?charset=utf8mb4
```
With this setting, the `gearbox setup-app` command returns the following error:
```
12:26:58,463 ERROR [gearbox] (pymysql.err.InternalError)
(1071, 'Specified key was too long; max key length is 767 bytes')
[SQL:
"\nCREATE TABLE users (
    \n\tuser_id INTEGER NOT NULL AUTO_INCREMENT,
    \n\temail VARCHAR(255) NOT NULL,
    \n\tdisplay_name VARCHAR(255),
    \n\tpassword VARCHAR(128),
    \n\tcreated DATETIME,
    \n\tis_active BOOL NOT NULL,
    \n\timported_from VARCHAR(32),
    \n\ttimezone VARCHAR(255) NOT NULL DEFAULT '',
    \n\twebdav_left_digest_response_hash VARCHAR(128),
    \n\tauth_token VARCHAR(255),
    \n\tauth_token_created DATETIME,
    \n\tCONSTRAINT pk__users PRIMARY KEY (user_id),
    \n\tCONSTRAINT uq__users__email UNIQUE (email),
    \n\tCHECK (is_active IN (0, 1))\n)\n\n"
]
```
If switching to `utf8` as default MySQL character set by modifying:
- `development.ini`:
  ```sqlalchemy.url = mysql+pymysql://tracimuser:tracimpassword@127.0.0.1/tracimdb?charset=utf8```
- `/etc/mysql/mariadb.conf.d/50-mysql-clients.cnf`:
  ```default-character-set = utf8```
- `/etc/mysql/mariadb.conf.d/50-client.cnf`:
  ```default-character-set = utf8```
- `/etc/mysql/mariadb.conf.d/50-server.cnf`:
  ```
  init-connect='SET NAMES utf8'
  character-set-server = utf8
  collation-server = utf8_unicode_ci
  ```
The `gearbox setup-app` command runs fine but when creating a user or a workspace, we get this error:
```
13:02:57,889 INFO  [requests.packages.urllib3.connectionpool] Starting new HTTP connection (1): 127.0.0.1                                                                                                           
13:02:57,890 INFO  [root] PUT request at /workspace/4.ics/4FAKEEVENT.ics received                                                                                                                                   
13:02:57,943 INFO  [root] Anonymous user refused                                                                                                                                                                    
13:02:57,949 INFO  [requests.packages.urllib3.connectionpool] Starting new HTTP connection (1): 127.0.0.1                                                                                                           
13:02:57,951 INFO  [root] PUT request at /workspace/4.ics/4FAKEEVENT.ics received                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                  
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/wsgiapp.py", line 122, in __call__                                                                 
    response = self.wrapped_dispatch(controller, environ, context)
  File "/home/algooapy/Documents/dev/py/tracim/tracim/tracim/lib/utils.py", line 99, in __call__
    return super().__call__(controller, environ, context)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/errorpage.py", line 56, in __call__
    resp = self.next_handler(controller, environ, context)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/transaction_manager.py", line 107, in __call__
    reraise(*exc_info)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/_compat.py", line 81, in reraise
    raise value
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/transaction_manager.py", line 83, in __call__
    response = self.next_handler(controller, environ, context)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/caching.py", line 54, in __call__
    return self.next_handler(controller, environ, context)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/session.py", line 71, in __call__
    response = self.next_handler(controller, environ, context)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/identity.py", line 75, in __call__
    return self.next_handler(controller, environ, context)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/i18n.py", line 71, in __call__
    return self.next_handler(controller, environ, context)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/wsgiapp.py", line 295, in dispatch
    return controller(environ, context)
  File "/home/algooapy/Documents/dev/py/tracim/tracim/tracim/lib/base.py", line 32, in __call__
    return TGController.__call__(self, environ, context)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/controllers/dispatcher.py", line 128, in __call__
    response = self._perform_call(context)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/controllers/dispatcher.py", line 109, in _perform_call
    r = self._call(func, params, remainder=remainder, context=context)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/controllers/decoratedcontroller.py", line 121, in _call
    output = controller_caller(context_config, bound_controller_callable, remainder, params)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/decorators.py", line 44, in _decorated_controller_caller
    return application_controller_caller(tg_config, controller, remainder, params)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/tgext/pluggable/i18n.py", line 22, in _add_pluggable_translations
    return next_caller(config, controller, remainder, params)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/configuration/app_config.py", line 127, in call_controller
    return controller(*remainder, **params)
  File "/home/algooapy/Documents/dev/py/tracim/tracim/tracim/controllers/admin/workspace.py", line 221, in post
    save_now=True,
  File "/home/algooapy/Documents/dev/py/tracim/tracim/tracim/lib/workspace.py", line 68, in create_workspace
    self.ensure_calendar_exist(workspace)
  File "/home/algooapy/Documents/dev/py/tracim/tracim/tracim/lib/workspace.py", line 184, in ensure_calendar_exist
    related_object_id=workspace.workspace_id,
  File "/home/algooapy/Documents/dev/py/tracim/tracim/tracim/lib/calendar.py", line 389, in create_then_remove_fake_event
    event = user_calendar.add_event(event_ics)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/caldav/objects.py", line 422, in add_event
    return Event(self.client, data = ical, parent = self).save()
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/caldav/objects.py", line 718, in save
    self._create(self._instance.serialize(), self.id, path)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/caldav/objects.py", line 699, in _create
    {"Content-Type": 'text/calendar; charset="utf-8"'})
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/caldav/davclient.py", line 191, in put
    return self.request(url, "PUT", body, headers)
  File "/home/algooapy/Documents/dev/py/tracim/tg2env/lib/python3.5/site-packages/caldav/davclient.py", line 242, in request
    raise ex
caldav.lib.error.AuthorizationError: AuthorizationError at 'http://127.0.0.1:5232/workspace/4.ics/4FAKEEVENT.ics', reason 'Forbidden'
```

Pointers:
http://docs.sqlalchemy.org/en/rel_1_0/dialects/mysql.html?highlight=charset%20selection#unicode
https://mariadb.com/kb/en/library/setting-character-sets-and-collations
https://mariadb.com/kb/en/library/create-database/
