### ISSUE TITLE
Bug: migration not working from 2.6.3 to 2.7.1

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2962]
## Bug description & symptom

After migrate tracim from 2.6.3 to 2.7.1, I can't create new content and I see error 500:
~~~
2020-04-30 14:49:49 INFO  [hapic:203][b'uWSGIWorker2Core0'] Exception IntegrityError occured, return 500 http_code : (psycopg2.errors.NotNullViolation) null value in column "cached_revision_id" violates not-null constraint
DETAIL:  Failing row contains (12933, null).

[SQL: INSERT INTO content (cached_revision_id) VALUES (%(cached_revision_id)s) RETURNING content.id]
[parameters: {'cached_revision_id': None}]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-04-30 14:49:49 DEBUG [hapic:206][b'uWSGIWorker2Core0'] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "cached_revision_id" violates not-null constraint
DETAIL:  Failing row contains (12933, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/hapic/hapic.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 657, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 657, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 657, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 657, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "./tracim_backend/lib/utils/authorization.py", line 310, in wrapper
    return func(self, context, request)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "./tracim_backend/views/core_api/workspace_controller.py", line 475, in create_generic_empty_content
    api.save(content, ActionDescription.CREATION)
  File "./tracim_backend/lib/core/content.py", line 2164, in save
    self._session.flush()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2451, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2549, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/persistence.py", line 1120, in _emit_insert_statements
    statement, params
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)*Explain the bug and what is going wrong.*
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "cached_revision_id" violates not-null constraint
DETAIL:  Failing row contains (12933, null).

[SQL: INSERT INTO content (cached_revision_id) VALUES (%(cached_revision_id)s) RETURNING content.id]
[parameters: {'cached_revision_id': None}]
(Background on this error at: http://sqlalche.me/e/gkpj)

[pid: 738|app: 0|req: 1312/2036] 127.0.0.1 () {46 vars in 1000 bytes} [Thu Apr 30 14:49:49 2020] POST /api/v2/workspaces/65/contents => generated 421 bytes in 26 msecs (HTTP/1.1 500) 6 headers in 430 bytes (1 switches on core 0)
~~~

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] migration work correctly

## Context and version information

2.7.0 and 2.7.1

## How to reproduce

Migrate from existing database (example from 2.6.3 with migrate_version `ce074202abb2`)

## Impacted components

- *backend*

## Implemented solution:
- Removing non null constraint in migration script (no not null constraint in normal schema)
see https://github.com/tracim/tracim/pull/2963

**Comment by inkhey** [comment]
After some search with @grignards , issue is due to the fact:
- We are trying to create a Content with a null but there is non null constraint, after search, sqlalchemy has to do this to make things work.
- There was a difference between new created database (no not null constraint) and migration script based databas.

**Comment by PhilippeAccorsi** [comment]
@inkhey what is necessary to done if user tried Tracim 2.7.0 or 2.7.1 on existing installation before we made this 2.7.2 ?

Is it necessary to downgrade database first and to re-start migration to 2.7.2 ?

**Comment by inkhey** [comment]
> @inkhey what is necessary to done if user tried Tracim 2.7.0 or 2.7.1 on existing installation before we made this 2.7.2 ?
> 
> Is it necessary to downgrade database first and to re-start migration to 2.7.2 ?

Yes downgrade first and upgrade only with new 2.7.2 migration.

**Comment by PhilippeAccorsi** [comment]
Ok. I add some information in changelog.

**Comment by PhilippeAccorsi** [comment]
Tested and verified on branch.
