### ISSUE TITLE
Crash on an office document 

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#314]
The url is http://algoo.trac.im/workspaces/50/folders/3323/files/3324

When damien (owner of the document) is going to this url, the page shows ok. When bastien is going to the url, he gets a 500 with the following traceback:

`
Traceback (most recent call last):
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/_compat.py", line 81, in reraise
    raise value
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/appwrappers/transaction_manager.py", line 83, in __call__
    response = self.next_handler(controller, environ, context)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/appwrappers/caching.py", line 54, in __call__
    return self.next_handler(controller, environ, context)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/appwrappers/session.py", line 71, in __call__
    response = self.next_handler(controller, environ, context)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/appwrappers/identity.py", line 75, in __call__
    return self.next_handler(controller, environ, context)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/appwrappers/i18n.py", line 71, in __call__
    return self.next_handler(controller, environ, context)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/wsgiapp.py", line 295, in dispatch
    return controller(environ, context)
  File "/data/tracim/releases/0.0.12/tracim/tracim/lib/base.py", line 32, in __call__
    return TGController.__call__(self, environ, context)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/controllers/dispatcher.py", line 128, in __call__
    response = self._perform_call(context)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/controllers/dispatcher.py", line 109, in _perform_call
    r = self._call(func, params, remainder=remainder, context=context)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/controllers/decoratedcontroller.py", line 127, in _call
    response = self._render_response(context, controller, output)
  File "/data/tracim/releases/0.0.12/tracim/tracim/controllers/root.py", line 70, in _render_response
    return super()._render_response(tgl, controller, response)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/controllers/decoratedcontroller.py", line 237, in _render_response
    template_name=template_name, **render_params)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/render.py", line 212, in render
    kwargs['result'] = render_function(template_name, tg_vars, **kwargs)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/renderers/mako.py", line 126, in __call__
    cache_type=cache_type, cache_expire=cache_expire)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/render.py", line 278, in cached_template
    return render_func()
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/TurboGears2-2.3.7-py3.4.egg/tg/renderers/mako.py", line 123, in render_template
    return Markup(template.render_unicode(**template_vars))
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/mako/template.py", line 454, in render_unicode
    as_unicode=True)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/data/tracim/releases/0.0.12/venv3.4/lib/python3.4/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/data/tracim/var/instances/algoo.trac.im/cache_data/mako/data/tracim/releases/0.0.12/tracim/tracim/templates/master_authenticated.mak.py", line 59, in render_body
    __M_writer(escape(self.content_wrapper()))
  File "/data/tracim/var/instances/algoo.trac.im/cache_data/mako/data/tracim/releases/0.0.12/tracim/tracim/templates/master_authenticated_left_treeview_right_toolbar.mak.py", line 66, in render_content_wrapper
    __M_writer(escape(self.body()))
  File "/data/tracim/var/instances/algoo.trac.im/cache_data/mako/data/tracim/releases/0.0.12/tracim/tracim/templates/file/getone.mak.py", line 204, in render_body
    __M_writer(escape(_('This file contains {} revision(s)').format(sum(1 for revision in result.file.revisions if revision.action.id=='revision'))))
KeyError: 'revisions'
`

**Comment by tracim** [comment]
Fixed through https://github.com/tracim/tracim/pull/319 PR
