### ISSUE TITLE
Bug: postgres database migration from 2.7.6 to 3.0.0_rc1 not working

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3343]
## Bug description & symptom

I have tried to install tracim 3.0.0_rci on existing database (tracim 2.7.6, but its a tracimv1 database from beggining)
I use docker and I seen this error

~~~
Starting 0011_algoo
Attaching to 0011_algoo
0011_algoo                   | Traceback (most recent call last):
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
0011_algoo                   |     cursor, statement, parameters, context
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
0011_algoo                   |     cursor.execute(statement, parameters)
0011_algoo                   | psycopg2.errors.UndefinedObject: constraint "fk_content_revisions_content_id_content" of relation "content_revisions" does not exist
0011_algoo                   | 
0011_algoo                   | 
0011_algoo                   | The above exception was the direct cause of the following exception:
0011_algoo                   | 
0011_algoo                   | Traceback (most recent call last):
0011_algoo                   |   File "/usr/local/bin/alembic", line 8, in <module>
0011_algoo                   |     sys.exit(main())
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/alembic/config.py", line 503, in main
0011_algoo                   |     CommandLine(prog=prog).main(argv=argv)
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/alembic/config.py", line 497, in main
0011_algoo                   |     self.run_cmd(cfg, options)
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/alembic/config.py", line 480, in run_cmd
0011_algoo                   |     **dict((k, getattr(options, k, None)) for k in kwarg)
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/alembic/command.py", line 254, in upgrade
0011_algoo                   |     script.run_env()
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/alembic/script/base.py", line 427, in run_env
0011_algoo                   |     util.load_python_file(self.dir, 'env.py')
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/alembic/util/pyfiles.py", line 81, in load_python_file
0011_algoo                   |     module = load_module_py(module_id, path)
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/alembic/util/compat.py", line 145, in load_module_py
0011_algoo                   |     spec.loader.exec_module(module)
0011_algoo                   |   File "<frozen importlib._bootstrap_external>", line 673, in exec_module
0011_algoo                   |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
0011_algoo                   |   File "tracim_backend/migration/env.py", line 90, in <module>
0011_algoo                   |     run_migrations_online()
0011_algoo                   |   File "tracim_backend/migration/env.py", line 81, in run_migrations_online
0011_algoo                   |     context.run_migrations()
0011_algoo                   |   File "<string>", line 8, in run_migrations
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/alembic/runtime/environment.py", line 836, in run_migrations
0011_algoo                   |     self.get_context().run_migrations(**kw)
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/alembic/runtime/migration.py", line 330, in run_migrations
0011_algoo                   |     step.migration_fn(**kw)
0011_algoo                   |   File "/tracim/backend/tracim_backend/migration/versions/3c92f57c52b2_added_events_and_messages_tables.py", line 54, in upgrade
0011_algoo                   |     ondelete="CASCADE",
0011_algoo                   |   File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
0011_algoo                   |     next(self.gen)
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/alembic/operations/base.py", line 300, in batch_alter_table
0011_algoo                   |     impl.flush()
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/alembic/operations/batch.py", line 53, in flush
0011_algoo                   |     fn(*arg, **kw)
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/alembic/ddl/impl.py", line 180, in drop_constraint
0011_algoo                   |     self._exec(schema.DropConstraint(const))
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/alembic/ddl/impl.py", line 115, in _exec
0011_algoo                   |     return conn.execute(construct, *multiparams, **params)
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 988, in execute
0011_algoo                   |     return meth(self, multiparams, params)
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
0011_algoo                   |     return connection._execute_ddl(self, multiparams, params)
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
0011_algoo                   |     compiled,
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
0011_algoo                   |     e, statement, parameters, cursor, context
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
0011_algoo                   |     util.raise_from_cause(sqlalchemy_exception, exc_info)
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
0011_algoo                   |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 128, in reraise
0011_algoo                   |     raise value.with_traceback(tb)
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
0011_algoo                   |     cursor, statement, parameters, context
0011_algoo                   |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
0011_algoo                   |     cursor.execute(statement, parameters)
0011_algoo                   | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) constraint "fk_content_revisions_content_id_content" of relation "content_revisions" does not exist
0011_algoo                   | 
0011_algoo                   | [SQL: ALTER TABLE content_revisions DROP CONSTRAINT fk_content_revisions_content_id_content]
0011_algoo                   | (Background on this error at: http://sqlalche.me/e/f405)
0011_algoo exited with code 1
~~~

Example of old naming convention

~~~
Indexes:
    "pk__content_revisions__revision_id" PRIMARY KEY, btree (revision_id)
    "idx__content_revisions__content_id" btree (content_id)
    "idx__content_revisions__owner_id" btree (owner_id)
    "idx__content_revisions__parent_id" btree (parent_id)
    "idx__content_revisions__workspace_id" btree (workspace_id)
Foreign-key constraints:
    "fk__content_revisions__content_id__content" FOREIGN KEY (content_id) REFERENCES content(id)
    "fk__content_revisions__owner_id" FOREIGN KEY (owner_id) REFERENCES users(user_id)
    "fk__content_revisions__parent_id__content" FOREIGN KEY (parent_id) REFERENCES content(id)
    "fk__content_revisions__workspace_id__workspaces" FOREIGN KEY (workspace_id) REFERENCES workspaces(workspace_id)
Referenced by:
    TABLE "content" CONSTRAINT "fk_content_cached_revision_id_content_revisions" FOREIGN KEY (cached_revision_id) REFERENCES content_revisions(revision_id) ON DELETE RESTRICT
    TABLE "revision_read_status" CONSTRAINT "revision_read_status_revision_id_fkey" FOREIGN KEY (revision_id) REFERENCES content_revisions(revision_id) ON UPDATE CASCADE ON DELETE CASCADE
~~~

## Diagnostic

- This script `3c92f57c52b2_added_events_and_messages_tables.py` make some change and failed.
- Database naming conventions are here meta.py

## Expected

- [x] Migration work correctly
- [x] For database come from tracimv1, maybe add a script use new naming convention everywhere

## Context and version information

Tracim 2.7.6 (if database come from tracimv1)

## How to reproduce

- Use database come from tracimv1
- Try to migrate to 3.0.0_rc1

## Impacted components

- *backend*

**Comment by PhilippeAccorsi** [comment]
To use tracimcli command to migrate old Tracim V1 database to new database, if you use Tracim with docker-compose.yml file, you can do:

- add this in your docker-compose.yml file
~~~
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        entrypoint: /bin/bash
~~~
Whis this you can start your Tracim container with this command `docker-compose run {name_of_your_service}` with all parameter visible in your file.

- After that you need to execute this command `ln -s /etc/tracim/color.json /tracim/color.json` (normaly its done when container start correctly). This is necessary because tracimcli check all necessary file exists.

- Now you can go to `/tracim/backend/` and execute this command `tracimcli db update-naming-conventions -c /etc/tracim/development.ini` (tracimcli documentation is visible [here](https://github.com/tracim/tracim/blob/develop/backend/doc/cli.md#update-naming-conventions-for-database-coming-from-tracim-v1-only-works-with-postgresql))

If no error are visible you can quit the container and remove the old container with this command `docker container rm {id_of_the_container}`.

- Comment line you add in docker-compose.yml and start tracim normally.
