### ISSUE TITLE
Bug: Lock timeout for preview of some file

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3459]
## Description and expectations

We get in production timeout for preview of some file. This should not happened unless the file is very big.
This is a bug in **preview_generator**.

## Relevant Logs
~~~
[pid: 4993|app: 0|req: 3308/13191] 127.0.0.1 () {42 vars in 1014 bytes} [Fri Jul 31 07:58:20 2020] GET /api/workspaces/49/files/13945/revisions/42140/preview/jpg/500x500/Process%20s%C3%A9curit%C3%A9.jpg?page=2 => generated 29843 bytes in 24 msecs (HTTP/1.1 200) 5 headers in 250 bytes (1 switches on core 0)
[pid: 4993|app: 0|req: 3309/13192] 127.0.0.1 () {46 vars in 1063 bytes} [Fri Jul 31 07:58:20 2020] GET /api/users/me/workspaces/30/contents/read_status => generated 226 bytes in 3 msecs (HTTP/1.1 307) 3 headers in 170 bytes (1 switches on core 0)
2020-07-31 07:58:20 INFO  [tracim:45][b'uWSGIWorker1Core0'] [TracimRequest] GET /api/users/233/workspaces/30/contents/read_status from authenticated user 233
2020-07-31 07:58:20 WARNI [tracim:48][b'uWSGIWorker2Core0'] [ContentApi] Unknown Preview_Generator Exception Occured
Traceback (most recent call last):
  File "./tracim_backend/lib/core/content.py", line 1045, in get_jpg_preview_path
    file_path, page=page_number, width=width, height=height, file_ext=file_extension
  File "/usr/local/lib/python3.5/dist-packages/preview_generator/manager.py", line 177, in get_jpeg_preview
    with preview_context.filelock:
  File "/usr/local/lib/python3.5/dist-packages/filelock.py", line 323, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.5/dist-packages/filelock.py", line 278, in acquire
    raise Timeout(self._lock_file)
filelock.Timeout: The file lock '/var/tracim/data/preview/92d3a61a71b3082933276bc4b4c8c4dd.lock' could not be acquired.
2020-07-31 07:58:20 INFO  [hapic:684][b'uWSGIWorker2Core0'] Exception UnavailablePreview occured, return 400 http_code : No preview available for content 10707, revision 31417
2020-07-31 07:58:20 DEBUG [hapic:689][b'uWSGIWorker2Core0'] Traceback (most recent call last):
  File "./tracim_backend/lib/core/content.py", line 1045, in get_jpg_preview_path
    file_path, page=page_number, width=width, height=height, file_ext=file_extension
  File "/usr/local/lib/python3.5/dist-packages/preview_generator/manager.py", line 177, in get_jpeg_preview
    with preview_context.filelock:
  File "/usr/local/lib/python3.5/dist-packages/filelock.py", line 323, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.5/dist-packages/filelock.py", line 278, in acquire
    raise Timeout(self._lock_file)
filelock.Timeout: The file lock '/var/tracim/data/preview/92d3a61a71b3082933276bc4b4c8c4dd.lock' could not be acquired.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "./tracim_backend/applications/content_file/controller.py", line 568, in sized_preview_jpg_revision
    file_extension=revision.file_extension,
  File "./tracim_backend/lib/core/content.py", line 1066, in get_jpg_preview_path
    ) from exc
tracim_backend.exceptions.UnavailablePreview: No preview available for content 10707, revision 31417
~~~

### How to reproduce

Need clarification about which file has preview that failed this way.

### Version information

- Tracim version: 3.0.X
- Preview_generator: 0.14

### original issue

from https://github.com/tracim/tracim/issues/3401 which previously combined 2 issues:
- the lock case issue (this one)
- a bug during the preview generation of simple pdf page preview.

**Comment by lebouquetin** [comment]
fixing this issue must include the addition of a log line showing the document file path.
