### ISSUE TITLE
WSGI error in Apache with default install/configuration

### ISSUE THREAD

**Issue by gehasia** [tracim/tracim#349]
Hi, i'm installing Tracim like doc says, fresh git clone, running it with mod_wsgi in Apache 2.4, python 3.5 (in Debian 9.1) and getting this error (i just changed the path to settings.ini in app.wsgi and point that config file in apache config instead of a copy aka productionapp.wsgi
```
[Mon Sep 11 19:51:56.671815 2017] [wsgi:info] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102] mod_wsgi (pid=13354, process='tracim', application='tracim.dev.local|'): Loading WSGI script '/var/www/tracimtest/tracim/app.wsgi'.
[Mon Sep 11 19:51:56.673926 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102] mod_wsgi (pid=13354): Target WSGI script '/var/www/tracimtest/tracim/app.wsgi' cannot be loaded as Python module.
[Mon Sep 11 19:51:56.674059 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102] mod_wsgi (pid=13354): Exception occurred processing WSGI script '/var/www/tracimtest/tracim/app.wsgi'.
[Mon Sep 11 19:51:56.676073 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102] Traceback (most recent call last):
[Mon Sep 11 19:51:56.676199 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]   File "/var/www/tracimtest/tracim/app.wsgi", line 11, in <module>
[Mon Sep 11 19:51:56.676213 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]     application = loadapp('config:%s' % APP_CONFIG)
[Mon Sep 11 19:51:56.676236 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]   File "/var/www/tracimtest/tg2env/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Mon Sep 11 19:51:56.676245 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]     return loadobj(APP, uri, name=name, **kw)
[Mon Sep 11 19:51:56.676260 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]   File "/var/www/tracimtest/tg2env/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
[Mon Sep 11 19:51:56.676268 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]     global_conf=global_conf)
[Mon Sep 11 19:51:56.676281 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]   File "/var/www/tracimtest/tg2env/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
[Mon Sep 11 19:51:56.676288 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]     global_conf=global_conf)
[Mon Sep 11 19:51:56.676301 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]   File "/var/www/tracimtest/tg2env/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 317, in _loadconfig
[Mon Sep 11 19:51:56.676308 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]     loader = ConfigLoader(path)
[Mon Sep 11 19:51:56.676320 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]   File "/var/www/tracimtest/tg2env/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 394, in __init__
[Mon Sep 11 19:51:56.676328 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]     self.parser.read_file(f)
[Mon Sep 11 19:51:56.676345 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]   File "/usr/lib/python3.5/configparser.py", line 715, in read_file
[Mon Sep 11 19:51:56.676353 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]     self._read(f, source)
[Mon Sep 11 19:51:56.676366 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]   File "/usr/lib/python3.5/configparser.py", line 1012, in _read
[Mon Sep 11 19:51:56.676374 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]     for lineno, line in enumerate(fp, start=1):
[Mon Sep 11 19:51:56.676386 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
[Mon Sep 11 19:51:56.676393 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102]     return codecs.ascii_decode(input, self.errors)[0]
[Mon Sep 11 19:51:56.676426 2017] [wsgi:error] [pid 13354:tid 140335633336064] [remote 172.16.254.254:56102] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1238: ordinal not in range(128)
```

This is app.wsgi, nothing fancy : 

```
# -*- coding: utf-8 -*-

APP_CONFIG = "/var/www/tracimtest/tracim/development.ini"

#Setup logging
# import logging
# logging.config.fileConfig(APP_CONFIG)

#Load the application
from paste.deploy import loadapp
application = loadapp('config:%s' % APP_CONFIG)
application.debug = False
```

Any clue on this ?

Other turbogears projects run fine (i tested a simple tg2 fresh project) in this environment

Thanks.

**Comment by algooapy** [comment]
Hi,
First of all, thanks for reporting this bug. Let us have on look on this to make you a proper answer.

**Comment by algooapy** [comment]
Is it possible for you to try the following two modifications in `tracim/development.ini` (and optionally `tracim/development.ini.base`) ?
- remove the comment on line 39 that include a weird "ALT GR+SPACE" character (that I typed, my bad...):
```
# preview generator cache directory
```
- edit wsgidav.config_path the line 228 to add `%(here)s/`:
```
wsgidav.config_path = %(here)s/wsgidav.conf 
```

**Comment by gehasia** [comment]
Everything is fine after those two modifications ! Thanks a lot for the good job.

**Comment by gehasia** [comment]
There was other invalid path for mako templates. I PR everything here  https://github.com/tracim/tracim/pull/352

**Comment by tracim** [comment]
Fixed by PR

**Comment by xandercagexxx** [comment]
Its working good with new documentation. 
New documentation is not enable for the moment.

**Comment by xandercagexxx** [comment]
Documentation available.
Verified.
