### ISSUE TITLE
Bug: Error at buildTimelineFromCommentAndRevision

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3518]
## Description and expectations

After making some tests of version 3.1.0. of Tracim, from time to time the document stops working completely, its content does not load.
In the browser console we have the following error:

![Capture d’écran de 2020-09-09 08-44-13](https://user-images.githubusercontent.com/35422692/92564000-c565c580-f278-11ea-8998-874425b555d4.png)

### How to reproduce

unknown

### Version information

- Tracim version: v.3.1.

________________________________________________

**Comment by raphj** [comment]
Here is the trace with a source-map enabled instance of Tracim:

```
Uncaught (in promise) TypeError: revisionList.map is not a function
    _temp tracim_frontend_lib.lib.js:31511
    _callee$ HtmlDocument.jsx:397
    u tracim_frontend_vendors.js:87
    _invoke tracim_frontend_vendors.js:87
    t tracim_frontend_vendors.js:87
    asyncGeneratorStep HtmlDocument.jsx:29
    _next HtmlDocument.jsx:31
```

On line `return revisionList.map(function (revision, i) {`, in function `buildTimelineFromCommentAndRevision`.

**Comment by raphj** [comment]
We get a 400 bad request on `GET /api/workspaces/30/html-documents/14996` and then on `/api/workspaces/30/html-documents/14996/revisions`, both with `message: "ContentTypeNotAllowed"`, `code: 2031`.

First, we would probably need to not do the second request if the first fails.

**Comment by raphj** [comment]
Backend trace:
```
2020-09-09 11:58:18 INFO  [tracim:45][waitress] [TracimRequest] GET /api/workspaces/30/html-documents/14996 from authenticated user 290
2020-09-09 11:58:18 INFO  [hapic:214][waitress] Exception ContentTypeNotAllowed occured, return 400 http_code : 
2020-09-09 11:58:18 DEBUG [hapic:217][waitress] Traceback (most recent call last):
  File "/tmp/tracim/backend/env/lib/python3.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/tmp/tracim/backend/env/lib/python3.7/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/tmp/tracim/backend/env/lib/python3.7/site-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/tmp/tracim/backend/env/lib/python3.7/site-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/tmp/tracim/backend/env/lib/python3.7/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/tmp/tracim/backend/env/lib/python3.7/site-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/tmp/tracim/backend/env/lib/python3.7/site-packages/hapic/hapic.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/tmp/tracim/backend/tracim_backend/lib/utils/authorization.py", line 317, in wrapper
    return func(self, context, request)
  File "/tmp/tracim/backend/tracim_backend/lib/utils/authorization.py", line 310, in wrapper
    authorization_checker.check(tracim_context=request)
  File "/tmp/tracim/backend/tracim_backend/lib/utils/authorization.py", line 179, in check
    raise ContentTypeNotAllowed()
tracim_backend.exceptions.ContentTypeNotAllowed
```

**Comment by raphj** [comment]
After looking in the database, this content is actually a comment and not an html-document, hence the problem. So we need to handle ContentTypeNotAllowed from the backend gracefully.

**Comment by raphj** [comment]
Putting back on to sort, the problem is not to be fixed for Tracim 3.1 since it was triggered by another bug, that is fixed in Tracim 3.1.

**Comment by lebouquetin** [comment]
What is the frontend behavior in case the API returns a HTTP 400? API errors should never end with frontend errors

**Comment by lebouquetin** [comment]
Backend and frontend must be mutually resilient

**Comment by raphj** [comment]
We reproduce again, by clicking randomly on the notification wall. It looks like the app html is always involved, to putting the relevant label. I'll look into this rapidly.

**Comment by gbonaspetti** [comment]
Tested on branch.
