### ISSUE TITLE
Bug: scrutinizer and coveralls not work with tracim repository

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3610]
## Description and expectations

In readme we show information from scrutinizer and coveralls but some information is not updated since more than one years.
Define if its necessary to save this tools on tracim repo, if yes debug is necessary, if no we can remove link from readme.

### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

## Screenshots

________________________________________________

**Comment by PhilippeAccorsi** [comment]
@lebouquetin Do you know if its necessary to use infromation from scrutinizer and coveralls in Tracim repository ? Or if another tool can be used ?

**Comment by PhilippeAccorsi** [comment]
Il y a en fait actuellement une erreur dans les test travis
~~~
$ coveralls
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.10/bin/coveralls", line 8, in <module>
    sys.exit(wear())
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/coveralls/__init__.py", line 78, in wear
    from coveralls.control import coveralls
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/coveralls/control.py", line 2, in <module>
    from coveralls.report import CoverallsReporter
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/coveralls/report.py", line 6, in <module>
    from coverage.report import Reporter
ImportError: cannot import name 'Reporter'
~~~

**Comment by PhilippeAccorsi** [comment]
This issue https://github.com/creare-com/podpac/issues/347 (whis other python version) is created in same period like us coveralls work for the last time.

**Comment by PhilippeAccorsi** [comment]
Do you think it can be a solution @inkhey ? https://github.com/creare-com/podpac/issues/347#issuecomment-683520501

**Comment by inkhey** [comment]
Just look at this, as far i understood:
- we do use package without fixed version for coverage, which is not nice, we should add a `requirements-coverage.txt` file with strict version
- we do install for travis both pytest-cov (plugin for pytest which simplify a by the use of coverage) and python-coveralls.
- The problem here is that python-coveralls is a library that is almost dead and that it does not support new version of coverage (an as we do install without any strict version of coverage, we do install use a 5+ version)

So to solve this, we should:
- add a `requirements-coverage.txt` with explicit working version and use it in travis if COVERAGE is true
- either forcing <5 version of coverage (easiest but less future proof) or take some more time to install https://github.com/coveralls-clients/coveralls-python instead, which seems to be the modern client for coveralls.
