### ISSUE TITLE
Bug: zope.interface==4.6.0 error

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3728]
## Description and expectations
related to #3727 about what I tried to do (install Tracim on Turris omnia with LXC container)

I have removed vtk from requierments.txt and now I have this error:
~~~
Collecting zope.interface==4.6.0
  Downloading zope.interface-4.6.0.tar.gz (150 kB)
     |████████████████████████████████| 150 kB 5.6 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /root/tracim/backend/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7v6gdevx/zope-interface/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7v6gdevx/zope-interface/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4h_8prqn
         cwd: /tmp/pip-install-7v6gdevx/zope-interface/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7v6gdevx/zope-interface/setup.py", line 26, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/root/tracim/backend/env/lib/python3.7/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
~~~

### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

Look here #3727

## Screenshots

________________________________________________

**Comment by PhilippeAccorsi** [comment]
I tried with changing setuptools to 50.3.2 but same error.

**Comment by inkhey** [comment]
You should probably try zope.interface > 4.7.2 . Problem is that zope.interface was containing old setuptools code https://github.com/zopefoundation/zope.interface/issues/30 .
Difficult to know if this will break something, we do not use it directly (see requirements.txt entry):
`zope.interface==4.6.0     # via pyramid, pyramid-retry, transaction, zope.sqlalchemy`
