### ISSUE TITLE
Bug: TLMs are sometimes broken after restarting the container

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3746]
## Description and expectations

After restarting the containers, TLMs sometimes stop being received, leading to pages not being updated anymore. Keep Alive TLMs (produced by Pushpin) are received but actual message never arrive.

## Workaround

Restating the container works around the issue, but causes #3745.

## Diagnostic

The related RQ worker (Redis) does not start. 

```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pk_messages"
DETAIL:  Key (receiver_id, event_id)=(290, 5146) already exists.

[SQL: INSERT INTO messages (receiver_id, event_id, sent, read) VALUES (%(receiver_id)s, %(event_id)s, %(sent)s, %(read)s)]
[parameters: ({'sent': datetime.datetime(2020, 10, 29, 9, 39, 35, 5205), 'read': None, 'event_id': 5146, 'receiver_id': 290}, {'sent': datetime.datetime(2020, 10, 29, 9, 39, 35, 5263), 'read': None, 'event_id': 5146, 'receiver_id': 3}, {'sent': datetime.datetime(2020, 10, 29, 9, 39, 35, 5289), 'read': None, 'event_id': 5146, 'receiver_id': 228}, {'sent': datetime.datetime(2020, 10, 29, 9, 39, 35, 5311), 'read': None, 'event_id': 5146, 'receiver_id': 261}, {'sent': datetime.datetime(2020, 10, 29, 9, 39, 35, 5332), 'read': None, 'event_id': 5146, 'receiver_id': 230}, {'sent': datetime.datetime(2020, 10, 29, 9, 39, 35, 5352), 'read': None, 'event_id': 5146, 'receiver_id': 291}, {'sent': datetime.datetime(2020, 10, 29, 9, 39, 35, 5371), 'read': None, 'event_id': 5146, 'receiver_id': 233}, {'sent': datetime.datetime(2020, 10, 29, 9, 39, 35, 5390), 'read': None, 'event_id': 5146, 'receiver_id': 234}  ... displaying 10 of 14 total bound parameter sets ...  {'sent': datetime.datetime(2020, 10, 29, 9, 39, 35, 5484), 'read': None, 'event_id': 5146, 'receiver_id': 281}, {'sent': datetime.datetime(2020, 10, 29, 9, 39, 35, 5503), 'read': None, 'event_id': 5146, 'receiver_id': 282})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
09:39:35 Moving job to 'failed' queue
09:39:35 Moving job to 'failed' queue
2020-10-29 09:39:35 WARNI [rq.worker:856][MainThread] Moving job to 'failed' queue
2020-10-29 09:39:42 WARNI [tracim:48][MainThread] [PluginManager] Cannot find plugin entry point 'register_tracim_plugin' in 'montracim' plugin
2020-10-29 09:39:42 INFO  [tracim:45][MainThread] [init_plugin_manager] Loaded and registered the following plugins: ('montracim', 'parent_access')
2020-10-29 09:39:42 WARNI [tracim:48][MainThread] [PluginManager] Cannot find plugin entry point 'register_tracim_plugin' in 'montracim' plugin
2020-10-29 09:39:42 INFO  [tracim:45][MainThread] [init_plugin_manager] Loaded and registered the following plugins: ('montracim', 'parent_access')
2020-10-29 09:40:19 WARNI [tracim:48][MainThread] [PluginManager] Cannot find plugin entry point 'register_tracim_plugin' in 'montracim' plugin
2020-10-29 09:40:19 INFO  [tracim:45][MainThread] [init_plugin_manager] Loaded and registered the following plugins: ('montracim', 'parent_access')
2020-10-29 09:45:32 DEBUG [tracim:39][MainThread] [CFG] CONFIG_PROCESS:1: load enabled apps
2020-10-29 09:45:32 INFO  [tracim:45][MainThread] [CFG] App Enabled config parameters:
```

(the sqlalchemy is caused by another issue and is probably irrelevant to this one)

**Comment by PhilippeAccorsi** [comment]
In Tracim container, with `ps aux` we need to see `/usr/bin/python3 /usr/local/bin/rq worker -q -w tracim_backend.lib.rq.worker.DatabaseWorker event`. If not, rq_worker is not started correctly, this error is visible in rq_worker log
~~~
2020-10-29 09:45:32 INFO  [tracim:45][MainThread] [CFG] LOADED_APP:ENABLED:gallery:Gallery
Traceback (most recent call last):
  File "/usr/local/bin/rq", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rq/cli/cli.py", line 75, in wrapper
    return ctx.invoke(func, cli_config, *args[1:], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rq/cli/cli.py", line 236, in worker
    worker.work(burst=burst, logging_level=logging_level)
  File "/tracim/backend/tracim_backend/lib/rq/worker.py", line 86, in work
    super().work(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 466, in work
    self.register_birth()
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 276, in register_birth
    raise ValueError(msg.format(self.name))
ValueError: There exists an active worker named '0018_preprod-algoo.200' already
~~~

**Comment by PhilippeAccorsi** [comment]
In container, you can try to start rq_worker with this command `supervisorctl start tracim_rq_worker`

**Comment by PhilippeAccorsi** [comment]
If we add sleep time (` && sleep 10 && `) between container stop and container start, rq seems to be working correctly all the time.

**Comment by inkhey** [comment]
Don't success to reproduce the issue with tracim 4.1.2.

**Comment by PhilippeAccorsi** [comment]
@inkhey i seen your answer. Do you have reproduce this error with older version of tracim ?
I use the sleep in bash command, but if it is no more necessary it is a good information ;)
