### ISSUE TITLE
Installation failes when reading the doc

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#378]
Current status : 

When following the documentation, I get an error when running python setup.py develop:

```
$ python setup.py develop
[...]
Installed /tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/six-1.11.0-py3.4.egg
Searching for py4j>=0.8
Reading https://pypi.python.org/simple/py4j/
Best match: py4j 0.10.6
Downloading https://pypi.python.org/packages/ac/26/6aced3634390aa7e49bd30c647a4890095b5d22fae940b4d3fd653368c3d/py4j-0.10.6.zip#md5=dfff2b4920d2e1114871e6df5673bd9c
Processing py4j-0.10.6.zip
Writing /tmp/easy_install-41i5a38p/py4j-0.10.6/setup.cfg
Running py4j-0.10.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-41i5a38p/py4j-0.10.6/egg-dist-tmp-ktyv8qem
zip_safe flag not set; analyzing archive contents...
py4j.tests.__pycache__.java_tls_test.cpython-34: module references __file__
py4j.tests.__pycache__.java_gateway_test.cpython-34: module references __file__
py4j.__pycache__.java_gateway.cpython-34: module references __file__
Adding py4j 0.10.6 to easy-install.pth file

Installed /tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/py4j-0.10.6-py3.4.egg
Searching for zope.interface
Reading https://pypi.python.org/simple/zope.interface/
Best match: zope.interface 4.4.3
Downloading https://pypi.python.org/packages/bd/d2/25349ed41f9dcff7b3baf87bd88a4c82396cf6e02f1f42bb68657a3132af/zope.interface-4.4.3.tar.gz#md5=8700a4f527c1203b34b10c2b4e7a6912
Processing zope.interface-4.4.3.tar.gz
Writing /tmp/easy_install-alcx62oe/zope.interface-4.4.3/setup.cfg
Running zope.interface-4.4.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-alcx62oe/zope.interface-4.4.3/egg-dist-tmp-synd9i7x
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
warning: no previously-included files matching 'appveyor.yml' found anywhere in distribution
no previously-included directories found matching 'docs/_build'
Traceback (most recent call last):
  File "setup.py", line 92, in <module>
    zip_safe=False,
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/command/develop.py", line 32, in run
    self.install_for_development()
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/command/develop.py", line 132, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 716, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/pkg_resources.py", line 631, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/pkg_resources.py", line 874, in best_match
    return self.obtain(req, installer)
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/pkg_resources.py", line 886, in obtain
    return installer(requirement)
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 636, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 666, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 856, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1063, in run_setup
    run_setup(setup_script, args)
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/sandbox.py", line 68, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/sandbox.py", line 114, in run
    return func()
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/sandbox.py", line 67, in runner
    _execfile(setup_script, ns)
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-alcx62oe/zope.interface-4.4.3/setup.py", line 142, in <module>
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/command/install_lib.py", line 22, in run
    self.build()
  File "/usr/lib/python3.4/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-alcx62oe/zope.interface-4.4.3/setup.py", line 41, in run
    'rq==0.7.1',
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/command/build_ext.py", line 54, in run
    _build_ext.run(self)
  File "/usr/lib/python3.4/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python3.4/distutils/command/build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "/tmp/easy_install-alcx62oe/zope.interface-4.4.3/setup.py", line 47, in build_extension
    name='tracim',
  File "/tmp/tt2/tracim/tg2env/lib/python3.4/site-packages/setuptools/command/build_ext.py", line 187, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.4/distutils/command/build_ext.py", line 503, in build_extension
    depends=ext.depends)
  File "/tmp/easy_install-p62iukwf/Pillow-4.3.0/mp_compile.py", line 41, in _mp_compile
  File "/usr/lib/python3.4/multiprocessing/context.py", line 116, in Pool
    from .pool import Pool
SystemError: Parent module 'multiprocessing' not loaded, cannot perform relative import
```

When running a second time the command, it passes.

**Comment by lebouquetin** [comment]
@buxx do you remember this bug ? You told me to test something like `python setup.py -e .` or something like that. Should we update the documentation ?

**Comment by buxx** [comment]
I juste remember it can be related with install strategies difference between pip and setup.py (easy_install / pip). But i'm not sure. Sorry it is not a big help.

**Comment by lebouquetin** [comment]
Actually, we _must_ have  a working install process. We did use setup.py in order to be more "pythonic" ; if it does not work we move all dependencies back to requirement.txt

**Comment by buxx** [comment]
I can take a look when you want : )

**Comment by algooapy** [comment]
not reproduced with python3.5

**Comment by algooapy** [comment]
not reproduced with python3.4 from jessie

**Comment by buxx** [comment]
Can reproduce on my computer too, AND on industracim/production tracim server i can with this steps:

* cd /tmp
* git clone https://github.com/tracim/tracim.git
* cd tracim
* virtualenv --no-site-packages -p /usr/bin/python3.4 venv3.4
* source venv3.4/bin/activate
* cd tracim/
* python setup.py develop

My computer versions:
* Python 3.4.2
* pip 1.5.6
* setuptools 5.5.1
* Linux Bastien 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux

**Comment by buxx** [comment]
> Can reproduce on my computer

After `pip install --upgrade pip setuptools`, did not reproduce ! pip and setuptools version look like to be the problem.

**Comment by tracim** [comment]
so maybe the install process should include this command in the documentation.
