### ISSUE TITLE
Bug: Empty mentions in contents generate a 500 error when saving

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3853]
:warning: already fixed by https://github.com/tracim/tracim/issues/4648

## Description and expectations

Some html documents cannot be saved as we get a 500 error from the backend.

The error is:
```
020-11-18 15:04:54 DEBUG [hapic:217][b'uWSGIWorker2Core2'] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/hapic/hapic.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "./tracim_backend/lib/utils/authorization.py", line 318, in wrapper
    return func(self, context, request)
  File "./tracim_backend/lib/utils/authorization.py", line 318, in wrapper
    return func(self, context, request)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "./tracim_backend/applications/content_html_document/controller.py", line 100, in update_html_document
    api.save(content)
  File "./tracim_backend/lib/core/content.py", line 2081, in save
    self._session.flush()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2628, in _flush
    self.dispatch.after_flush(self, flush_context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "./tracim_backend/lib/crud_hook/caller.py", line 62, in _call_hooks
    self._plugin_manager.hook.on_content_modified(content=obj, context=session.context)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "./tracim_backend/lib/core/mention.py", line 139, in on_content_modified
    mentions = parser.get_mentions(content.current_revision)
  File "./tracim_backend/lib/core/mention.py", line 72, in get_mentions
    return self.get_mentions_from_html(revision.description)
  File "./tracim_backend/lib/core/mention.py", line 88, in get_mentions_from_html
    recipient = mention_tag.string[1:]
TypeError: 'NoneType' object is not subscriptable
```

### How to reproduce

1. Create an html document with a mention inside
2. Edit the document by removing part of the inserted mention tag or add irrelevant text in this tag
3. Save the document

### Version information

- Tracim version: 3.2.1

## Screenshots

________________________________________________

## Diagnostic

The saved documents has several occurences of uncorrect mention tags, eg. `<span id="mention-uieuieu"></span>` or with not purely mentions: `<span id="mention-uieuieu">Fooo @bar</span>`

**Comment by inkhey** [comment]
This fix as already been fixed by https://github.com/tracim/tracim/issues/4648
