### ISSUE TITLE
Chore: some frontend unit tests trigger errors relative to http requests

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3880]
## Description and expectations

Some frontend unit tests trigger errors relative to http requests, probably due to missing mocks for the API.

In the collaborative app:

```
request to http://unit.test:6543/api/workspaces/1/files/1 failed, reason: getaddrinfo ENOTFOUND unit.test unit.test:6543
```

The test seems to actually query unit.test, which is potentially harmful; we should never attempt to send requests to hosts we don't control, especially in unit tests.

In the gallery app:

```
(node:14113) UnhandledPromiseRejectionWarning: FetchError: request to http://localhost:1337/api/workspaces/0/contents?parent_ids=0 failed, reason: Nock: No match for request {
  "method": "GET",
  "url": "http://localhost:1337/api/workspaces/0/contents?parent_ids=0",
  "headers": {
    "accept": [
      "application/json"
    ],
    "x-tracim-clienttoken": [
      "b95bde91-9fd9-4541-b5f5-c597f9a8193c"
    ],
    "content-type": [
      "application/json"
    ],
    "accept-encoding": [
      "gzip,deflate"
    ],
    "user-agent": [
      "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
    ],
    "connection": [
      "close"
    ]
  }
}
    at OverriddenClientRequest.<anonymous> (/home/raph/dl/tracim/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
    at OverriddenClientRequest.emit (events.js:198:13)
    at process.nextTick (/home/raph/dl/tracim/frontend_app_gallery/node_modules/nock/lib/intercepted_request_router.js:108:11)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:14113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14113) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

In app thread:

```
(node:16710) UnhandledPromiseRejectionWarning: FetchError: request to http://localhost:6543/system/workspace_access_types failed, reason: connect ECONNREFUSED 127.0.0.1:6543
    at ClientRequest.<anonymous> (/home/raph/dl/tracim/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:16710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16710) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

In workspace or workspace advanced:

```
(node:17022) UnhandledPromiseRejectionWarning: FetchError: request to http://unit.test:6543/api/workspaces/1/subscriptions failed, reason: Nock: No match for request {
  "method": "GET",
  "url": "http://unit.test:6543/api/workspaces/1/subscriptions",
  "headers": {
    "accept": [
      "application/json"
    ],
    "x-tracim-clienttoken": [
      "1eceb48f-1711-4eb6-b7d8-abee23096205"
    ],
    "content-type": [
      "application/json"
    ],
    "accept-encoding": [
      "gzip,deflate"
    ],
    "user-agent": [
      "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
    ],
    "connection": [
      "close"
    ]
  }
}
    at OverriddenClientRequest.<anonymous> (/home/raph/dl/tracim/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
    at OverriddenClientRequest.emit (events.js:198:13)
    at process.nextTick (/home/raph/dl/tracim/node_modules/nock/lib/intercepted_request_router.js:108:11)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:17022) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17022) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Skylsmoi** [comment]
Note that the `Nock: No match for request` message usually means that a endpoint has been mocked but might be called multiple times.

This is because mocking an endpoint works only once except if you add `.persists()` to the mock declaration. You can also use `.times(int)`.

Adding .persists() or .times() should not be the correct fix though, it might be better to mock the endpoint the right amount of time in the right tests
