### ISSUE TITLE
Bug: Error 500 on GET /api/workspaces/{workspace_id}/files/{content_id}/revisions/{revision_id}/raw/{filename} 

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4013]
## Description and expectations

I get an Error 500 when performing this request: `GET /api/workspaces/{workspace_id}/files/{content_id}/revisions/{revision_id}/raw/{filename} `

### How to reproduce

```
curl 'http://localhost:7999/api/workspaces/3/files/33/revisions/58/raw/hello.kanban' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0' -H 'Accept: application/json' -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'Referer: http://localhost:7999/ui/workspaces/3/contents/file/33?folder_open=&parent_id=null' -H 'X-Tracim-ClientToken: 3cf3911f-b8a4-43e0-ab41-aa6857c708da' -H 'Content-Type: application/json' -H 'Connection: keep-alive' -H 'Cookie: csrftoken=oeNfhiDc19WqhqDYPtPYpeob9J9yh4JIDJyvNqX9DAQivErFVGbgZJATw4XqWKe6; defaultLanguage=fr; session_key=811f3854b526fbed3beff4aa2d9019d9a4a19715455de9ece8064b659f3ba3976dde154a; lastConnection=1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
```

```
2021-01-05 11:51:49 INFO  [tracim:45][waitress] [TracimRequest] GET /api/workspaces/3/files/33/revisions/58/raw/hello.kanban from authenticated user 1
2021-01-05 11:51:49 INFO  [hapic:214][waitress] Exception TypeError occured, return 500 http_code : join() argument must be str or bytes, not 'NoneType'
2021-01-05 11:51:49 DEBUG [hapic:217][waitress] Traceback (most recent call last):
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/hapic/hapic.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/home/raph/dl/tracim/backend/tracim_backend/lib/utils/authorization.py", line 318, in wrapper
    return func(self, context, request)
  File "/home/raph/dl/tracim/backend/tracim_backend/lib/utils/authorization.py", line 318, in wrapper
    return func(self, context, request)
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/raph/dl/tracim/backend/tracim_backend/applications/content_file/controller.py", line 254, in download_revisions_file
    revision.depot_file
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/depot/io/local.py", line 81, in get
    local_file_path = self.__local_path(fileid)
  File "/home/raph/dl/tracim/backend/env/lib/python3.7/site-packages/depot/io/local.py", line 77, in __local_path
    return os.path.join(self.storage_path, fileid)
  File "/usr/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

### Version information

- Tracim version: v3.4

**Comment by lebouquetin** [comment]
@raphj is it related to *creation* revision or to empty file content?

**Comment by raphj** [comment]
@lebouquetin it is related to creation revision.

It should probably still fail, but with a proper 40X error. Actually, I expected to get an empty file after its creation so returning an empty file would be a fine behavior too for me. I guess the Tracim way of being extremely explicit would dictate to return an error though.

**Comment by lebouquetin** [comment]
How do you explain I also faced the issue with modification revisions also ?

How to reproduce:

- create a file through api
- do not push file content
- modify the file name or description
- try to download the raw content

**Comment by lebouquetin** [comment]
By the way the right way to reply should by HTTP 200 + empty file or HTTP 204, not 40X, I think

**Comment by raphj** [comment]
> By the way the right way to reply should by HTTP 200 + empty file or HTTP 204, not 40X, I think

I think so too. @inkhey ?

**Comment by raphj** [comment]
> How do you explain I also faced the issue with modification revisions also ?
> 
> How to reproduce:
> 
>     * create a file through api
> 
>     * do not push file content
> 
>     * modify the file name or description
> 
>     * try to download the raw content

I confirm I observed an error doing this yesterday

**Comment by inkhey** [comment]
> > By the way the right way to reply should by HTTP 200 + empty file or HTTP 204, not 40X, I think
> 
> I think so too. @inkhey ?

For this case yes, but we may want a different result if the file exist but is broken.

**Comment by inkhey** [comment]
> > By the way the right way to reply should by HTTP 200 + empty file or HTTP 204, not 40X, I think
> 
> I think so too. @inkhey ?

> By the way the right way to reply should by HTTP 200 + empty file or HTTP 204, not 40X, I think

Not sure about this one because it's can be confusing to have different result from similar endpoint.
For preview, we do solve the issue with has_jpeg_preview or has_pdf_preview, but for this one, i'm not sure.
