### ISSUE TITLE
Bug: i can't delete one user  whis tracimcli command

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4096]
## Description and expectations

I tried to delete one user but this error appear. I have deleted many other user on same Tracim instance without error.
~~~
2021-01-26 10:29:07 INFO  [tracim:45][MainThread] [CleanupLib] delete content 16019
2021-01-26 10:29:07 DEBUG [tracim:39][MainThread] [CleanupLib] delete <tracim_backend.models.data.Content object at 0x7f5c7efe7a90>
2021-01-26 10:29:07 ERROR [tracim:54][MainThread] [DeleteUserCommand] This user is not a member of this workspace: yannick
Traceback (most recent call last):
  File "/tracim/backend/tracim_backend/command/__init__.py", line 64, in take_action
    self.take_app_action(parsed_args, app_context)
  File "/tracim/backend/tracim_backend/command/cleanup.py", line 161, in take_app_action
    cleanup_lib=cleanup_lib,
  File "/tracim/backend/tracim_backend/command/cleanup.py", line 275, in _delete_user_database_info
    deleted_workspace_ids = cleanup_lib.delete_user_owned_workspace(user)
  File "/tracim/backend/tracim_backend/lib/cleanup/cleanup.py", line 317, in delete_user_owned_workspace
    self.delete_workspace(workspace)
  File "/tracim/backend/tracim_backend/lib/cleanup/cleanup.py", line 217, in delete_workspace
    self.delete_content(content)
  File "/tracim/backend/tracim_backend/lib/cleanup/cleanup.py", line 166, in delete_content
    self.delete_content(children)
  File "/tracim/backend/tracim_backend/lib/cleanup/cleanup.py", line 171, in delete_content
    self.delete_revision(revision, do_update_content_last_revision=False)
  File "/tracim/backend/tracim_backend/lib/cleanup/cleanup.py", line 124, in delete_revision
    for read_status in read_statuses:
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 3502, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 1617, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2628, in _flush
    self.dispatch.after_flush(self, flush_context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/tracim/backend/tracim_backend/lib/crud_hook/caller.py", line 62, in _call_hooks
    self._plugin_manager.hook.on_content_modified(content=obj, context=session.context)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/tracim/backend/tracim_backend/lib/core/mention.py", line 152, in on_content_modified
    self._create_mention_events(new_mentions, content, context)
  File "/tracim/backend/tracim_backend/lib/core/mention.py", line 187, in _create_mention_events
    "This user is not a member of this workspace: {}".format(mention.recipient)
tracim_backend.exceptions.UserNotMemberOfWorkspace: This user is not a member of this workspace: yannick
Something goes wrong during command: This user is not a member of this workspace: yannick
2021-01-26 10:29:07 ERROR [tracimcli:406][MainThread] This user is not a member of this workspace: yannick
~~~

### How to reproduce

Tracimcli command used `tracimcli user delete -c /etc/tracim/development.ini -d -b -l yannick.xxx@xxx.xx`

### Version information

- Tracim version: 3.4.3

## Screenshots

________________________________________________

**Comment by PhilippeAccorsi** [comment]
I have tried to anonymise this account and I can seen this in log

`tracimcli user delete -c /etc/tracim/development.ini -a -l yannick.xxxxxx@xxx.xx`
~~~
trying to delete user 291: "yannick.xxxxxx@xxx.xx"

1064 revision of user "291" in sharespaces found, deleting them, can cause inconsistent database.
2 workspace(s) of user "291" found, cannot delete user without deleting/changing ownership
user 291 anonymized to "Deleted user <anonymous_b17a93c291444c9a8bfc000818c89147@anonymous.local/None>".
~~~

**Comment by PhilippeAccorsi** [comment]
I have seen same error with an other list of user, and this message show a username but this user is not in the list of user I want to delete

`tracim_backend.exceptions.UserNotMemberOfWorkspace: This user is not a member of this workspace: guenael`

**Comment by PhilippeAccorsi** [comment]
The problematic seems to be tracimcli delete space and after tracimcli try to delete content of this space. But some other user exists so tracim try to create a notification for this user but user is not anymore in this deleted space.

Something is wrong in the process to delete space.

**Comment by inkhey** [comment]
@grignards maybe an autoflush issue (seems more logical to flush only at the end of the process , no ?): 

>   self.delete_revision(revision, do_update_content_last_revision=False)`
>   File "/tracim/backend/tracim_backend/lib/cleanup/cleanup.py", line 124, in delete_revision
>     for read_status in read_statuses:
>   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 3502, in __iter__
>     self.session._autoflush()
>   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 1617, in _autoflush
>     self.flush()
>   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2523, in flush
>     self._flush(objects)

I still don't understood how having both workspace role deletion and content_deletion in a same flush can lead to tlm be able to get old workspace user list for notification.
