### ISSUE TITLE
Bug: i can't add new member in some spaces but its working in another spaces

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4130]
## Description and expectations

I tried to add a new member in some spaces from admin space page. Its works for some space but for another, an error 500 appear in frontend.
~~~
{"message": "'access_type'", "details": {"error_detail": {}}, "code": null}
~~~

In backend I can seen :
~~~
2021-01-29 14:51:28 INFO  [tracim:45][b'uWSGIWorker4Core0'] [TracimRequest] POST /api/workspaces/97/members from authenticated user 311
[pid: 820|app: 0|req: 86483/518757] 172.18.0.1 () {64 vars in 999 bytes} [Fri Jan 29 14:51:30 2021] GET /api/contents/None => generated 112 bytes in 1 msecs (HTTP/1.1 400) 1 headers in 60 bytes (1 switches on core 0)
[pid: 828|app: 0|req: 100834/518758] 172.18.0.1 () {64 vars in 999 bytes} [Fri Jan 29 14:51:30 2021] GET /api/contents/None => generated 112 bytes in 1 msecs (HTTP/1.1 400) 1 headers in 60 bytes (1 switches on core 1)
[pid: 828|app: 0|req: 100835/518759] 172.18.0.1 () {64 vars in 995 bytes} [Fri Jan 29 14:51:30 2021] GET /api/contents/None => generated 112 bytes in 2 msecs (HTTP/1.1 400) 1 headers in 60 bytes (1 switches on core 3)
2021-01-29 14:51:30 INFO  [hapic:214][b'uWSGIWorker4Core0'] Exception KeyError occured, return 500 http_code : 'access_type'
2021-01-29 14:51:30 DEBUG [hapic:217][b'uWSGIWorker4Core0'] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/hapic/hapic.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "./tracim_backend/lib/utils/authorization.py", line 318, in wrapper
    return func(self, context, request)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "./tracim_backend/views/core_api/workspace_controller.py", line 417, in create_workspaces_members_role
    flush=True,
  File "./tracim_backend/lib/core/userworkspace.py", line 157, in create_one
    self._session.flush()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2628, in _flush
    self.dispatch.after_flush(self, flush_context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "./tracim_backend/lib/crud_hook/caller.py", line 36, in _call_hooks
    role=obj, context=session.context
  File "/usr/local/lib/python3.5/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "./tracim_backend/lib/core/event.py", line 583, in on_user_role_in_workspace_created
    self._create_workspace_historic_messages_for_current_user(role, context)
  File "./tracim_backend/lib/core/event.py", line 594, in _create_workspace_historic_messages_for_current_user
    max_messages_count=context.app_config.WORKSPACE__JOIN__MAX_MESSAGES_HISTORY_COUNT,
  File "./tracim_backend/lib/core/event.py", line 371, in create_messages_history_for_user
    event, session, self._config
  File "./tracim_backend/lib/core/event.py", line 751, in _get_workspace_event_receiver_ids
    if WorkspaceAccessType(event.workspace["access_type"]) in Workspace.ACCESSIBLE_TYPES:
KeyError: 'access_type'
~~~

### How to reproduce

I don't know. Maybe have create some space with open and on_request type and chnage this to confidential

### Version information

- Tracim version: 3.4.3

## Screenshots

________________________________________________

**Comment by PhilippeAccorsi** [comment]
A workaround for this bug is to set `workspace.join.max_messages_history_count = 0` in development.ini.

**Comment by grignards** [comment]
The bug reveals itself with version 3.3.0 and occurs with spaces created between the 3.0.0 and the 3.1.5 (inclusive).

**Comment by PhilippeAccorsi** [comment]
Tested on preprod.

**Comment by PhilippeAccorsi** [comment]
Done.
