### ISSUE TITLE
Bug: when we tried to translate Note if language of document is the same like language of user (visible if 2 language in same Note

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4237]
## Description and expectations

I seen an error 502 (error in devtool)
~~~
Translation service server error: Route not found for service: accountId: 602bd40a4842b12d61098f02, service: Translate_fr_fr, selectors: {profileId: 0, owner: !Systran, domain: Generic, size: L}
~~~ 
when I tried to translate this note
~~~
Une super note !


What is Tracim?

Tracim is a collaborative platform software intended for (not only technical) team collaboration. It is simple to use, offers a user-friendly interface and runs on every computer. It is very valuable for R&D teams, assocations, remote collaboration.

More information on the website: https://www.tracim.fr (in French)
~~~

My user language is English.
This is the log visible in tracim backend (uwsgi config => tracim_web.log)
~~~
[pid: 835|app: 0|req: 290/623] 172.18.0.1 () {70 vars in 1563 bytes} [Wed Mar  3 22:20:55 2021] GET /api/workspaces/2/html-documents/31/revisions/106/translated/content-31-en.html?target_language_code=en => generated 110 bytes in 180098 msecs (HTTP/1.1 502) 1 headers in 60 bytes (1 switches on core 3)
2021-03-03 22:24:52 INFO  [hapic:684][b'uWSGIWorker3Core0'] Exception TranslationServiceException occured, return 502 http_code : Unknown error when requesting translation server
2021-03-03 22:24:52 DEBUG [hapic:689][b'uWSGIWorker3Core0'] Traceback (most recent call last):
  File "./tracim_backend/lib/translate/services/systran.py", line 77, in _translate_file
    error = response.json()["error"]
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 661, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "./tracim_backend/lib/utils/authorization.py", line 371, in wrapper
    return func(self, context, request)
  File "./tracim_backend/lib/utils/authorization.py", line 371, in wrapper
    return func(self, context, request)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "./tracim_backend/applications/content_html_document/controller.py", line 194, in get_html_document_revision_translation
    binary_io=file,
  File "./tracim_backend/lib/translate/translator.py", line 41, in translate_file
    return self._translate_file(current_node, binary_io, mimetype, **options)
  File "./tracim_backend/lib/translate/services/systran.py", line 81, in _translate_file
    ) from exc
tracim_backend.lib.translate.translator.TranslationServiceException: Unknown error when requesting translation server

[pid: 831|app: 0|req: 136/624] 172.18.0.1 () {74 vars in 1616 bytes} [Wed Mar  3 22:21:52 2021] GET /api/workspaces/2/html-documents/31/revisions/106/translated/content-31-en.html?target_language_code=en => generated 110 bytes in 180053 msecs (HTTP/1.1 502) 1 headers in 60 bytes (1 switches on core 0)
~~~

### How to reproduce

- Prerequiste => use systran with config activated

- Create a Note with text visible in this issue
  - text in Note need to show 2 text in different language
- your user need to have the same language like the biggest text in the Note
- click on translate button
=> it's take too much time, near 2min, and after that an error is visible in devtool

=> if you chnage the user language for french, translation work
=> this bug appear also if you just have a line in french and try to translate in french

### Version information

- Tracim version: 3.5.0_build_039
- Web browser: Firefox
- Version: 78.7.0esr
- Device / System: Debian Buster

## Screenshots

________________________________________________

## Implemented solution

- [x] when getting a 500 error from systran, check the error message for the `Translate_xx_yy` string, if xx==yy==given output language, return the original document
- [x] added a configurable timeout for systran requests (`translation_service.timeout`).

**Comment by PhilippeAccorsi** [comment]
The error appear after 3min.
No error visible in frontend or I have miss the flash message.

**Comment by inkhey** [comment]
Checked manually. systran return 504 gateway timeout, seems like there is some kind of bug with the translation from english to english. in systran.

**Comment by inkhey** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
