### ISSUE TITLE
Bug: The creation of open spaces fails with a 500 error if the autoinvite plugin is enabled

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4631]
## Description and expectations

After enabling the `autoinvite` plugin and creating some users it is not possible to create a new open space.
In this case the backend returns a 500 error with the following backtrace:
```
2021-05-11 09:34:19 DEBUG [hapic:217][waitress] Traceback (most recent call last):
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1257, in _execute_context
    self.dialect.do_executemany(
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: messages.receiver_id, messages.event_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/pyramid_tm/__init__.py", line 76, in _finish
    finisher()
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/transaction/_manager.py", line 131, in commit
    return self.get().commit()
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/transaction/_transaction.py", line 311, in commit
    reraise(t, v, tb)
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/transaction/_compat.py", line 50, in reraise
    raise value
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/transaction/_transaction.py", line 302, in commit
    self._commitResources()
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/transaction/_transaction.py", line 447, in _commitResources
    reraise(t, v, tb)
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/transaction/_compat.py", line 50, in reraise
    raise value
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/transaction/_transaction.py", line 424, in _commitResources
    rm.tpc_vote(self)
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/zope/sqlalchemy/datamanager.py", line 111, in tpc_vote
    self.tx.commit()
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1083, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1257, in _execute_context
    self.dialect.do_executemany(
  File "/home/sebastien/.pyenv/versions/tracim/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: messages.receiver_id, messages.event_id
[SQL: INSERT INTO messages (receiver_id, event_id, sent, read) VALUES (?, ?, ?, ?)]
[parameters: ((2, 12, None, '2021-05-11 09:34:19.642469'), (2, 13, None, '2021-05-11 09:34:19.643241'), (1, 12, '2021-05-11 09:34:19.647473', None), (2, 12, '2021-05-11 09:34:19.647510', None), (1, 13, '2021-05-11 09:34:19.649098', None), (2, 13, '2021-05-11 09:34:19.649136', None))]
```

### How to reproduce

1. Enable `autoinvite`
2. Create some users
3. Try to create an open space.

### Version information

- Tracim version: build_044

**Comment by gbonaspetti** [comment]
Tested on branch
