### ISSUE TITLE
Bug: Possible 500 error when editing a comment

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4648]
## Description and expectations

Editing a comment containing a mention sometimes gives an error in the PUT request saving it.
Here is the backend traceback of such an error:
```
[TracimRequest] PUT /api/workspaces/198/contents/18071/comments/18072 from authenticated user 338
2021-05-12 14:31:01 INFO  [hapic:214][b'uWSGIWorker1Core1'] Exception TypeError occured, return 500 http_code : 'NoneType' object is not subscriptable
2021-05-12 14:31:01 DEBUG [hapic:217][b'uWSGIWorker1Core1'] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyramid_tm/__init__.py", line 76, in _finish
    finisher()
  File "/usr/local/lib/python3.5/dist-packages/transaction/_manager.py", line 131, in commit
    return self.get().commit()
  File "/usr/local/lib/python3.5/dist-packages/transaction/_transaction.py", line 311, in commit
    reraise(t, v, tb)
  File "/usr/local/lib/python3.5/dist-packages/transaction/_compat.py", line 50, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/transaction/_transaction.py", line 302, in commit
    self._commitResources()
  File "/usr/local/lib/python3.5/dist-packages/transaction/_transaction.py", line 447, in _commitResources
    reraise(t, v, tb)
  File "/usr/local/lib/python3.5/dist-packages/transaction/_compat.py", line 50, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/transaction/_transaction.py", line 419, in _commitResources
    rm.tpc_begin(self)
  File "/usr/local/lib/python3.5/dist-packages/zope/sqlalchemy/datamanager.py", line 98, in tpc_begin
    self.session.flush()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2628, in _flush
    self.dispatch.after_flush(self, flush_context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "./tracim_backend/lib/crud_hook/caller.py", line 68, in _call_hooks
    self._plugin_manager.hook.on_content_modified(content=obj, context=session.context)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "./tracim_backend/lib/core/mention.py", line 140, in on_content_modified
    mentions = parser.get_mentions(content.current_revision)
  File "./tracim_backend/lib/core/mention.py", line 73, in get_mentions
    return self.get_mentions_from_html(revision.raw_content)
  File "./tracim_backend/lib/core/mention.py", line 89, in get_mentions_from_html
    recipient = mention_tag.string[1:]
TypeError: 'NoneType' object is not subscriptable
```

### How to reproduce

1. Create a comment with a mention
2. Edit it and remove all the mention except the `@` character
3. Try to save the comment.

### Version information

- Tracim version: 3.8.1

## Screenshots

________________________________________________

## Implemented solution 

#5063
- Fix 500 error case with wrong user mention in comment edition
- Fix 500 error case with empty mention in comment and note.

**Comment by grignards** [comment]
> @grignards can you reproduce this issue ?

Yes, I tried again and detailed the method to reproduce it.

**Comment by inkhey** [comment]
I do solve two case in https://github.com/tracim/tracim/pull/5063.
- The fact we do not save explicitly cause 500 instead of 400 for wrong user mention. (the case you document to reproduce). this case exist only for updating comment
- When the mention as html tag exist but there is nothing inside (no @ ), (the case the error given came from). This error is fixed for post too.

**Comment by inkhey** [comment]
Also theses fix may fix similar issue for note too (need to check this).

**Comment by knodelle** [comment]
done
