### ISSUE TITLE
Bug: yarn installation is broken (tested when build docker images)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4830]
## Description and expectations

I tried to build a docker image for Tracim 3.9.1 and this error appear.

~~~
[12:51:05] $ Installing  yarn…
Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch Release
Get:5 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Hit:6 https://deb.nodesource.com/node_10.x stretch InRelease
Get:8 https://dl.yarnpkg.com/debian stable/main amd64 Packages [10.1 kB]
Get:9 https://dl.yarnpkg.com/debian stable/main all Packages [10.1 kB]
Fetched 37.2 kB in 0s (53.6 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  yarn
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 891 kB of archives.
After this operation, 5407 kB of additional disk space will be used.
Get:1 https://dl.yarnpkg.com/debian stable/main amd64 yarn all 1.22.5-1 [891 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 891 kB in 0s (3369 kB/s)
Selecting previously unselected package yarn.
(Reading database ... 39224 files and directories currently installed.)
Preparing to unpack .../archives/yarn_1.22.5-1_all.deb ...
Unpacking yarn (1.22.5-1) ...
Setting up yarn (1.22.5-1) ...

[12:51:08] $ Dependencies successfully installed.

[12:51:08] $ You have Yarn 1.22.5. Setting up Yarn 2 to version 2.1.1.
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /tracim/.yarn/releases/yarn-berry.cjs...
Updating /tracim/.yarnrc.yml...
Done!
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /tracim/.yarn/releases/yarn-berry.cjs:289:2658
    at Object.<anonymous> (/tracim/.yarn/releases/yarn-berry.cjs:586:2636)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /tracim/.yarn/releases/yarn-berry.cjs:289:2658
    at Object.<anonymous> (/tracim/.yarn/releases/yarn-berry.cjs:586:2636)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

[12:51:10] $ We expected Yarn 2 ≥ 2.0.0-rc.33, we got .
~~~

### How to reproduce

- git checkout release_03.09.01
- cd tools_docker/Debian_Uwsgi/
- docker build --no-cache --build-arg TAG=release_03.09.01 -t algoo/tracim:3.9.1 .

## Screenshots

________________________________________________

## Diagnostic

Yarn's [official installation procedure](https://yarnpkg.com/getting-started/install) is as follow:

- first install yarn version 1.x globally
- then upgrade to the latest yarn version using yarn 1 (which only allows to update to yarn `master` branch)
- then set the precise yarn version Tracim needs.

The problem is that the last yarn version (3.0.0) uses the `worker_threads` module which is not available with Tracim's node 10. Node 10 is EOL since some months, so yarn maintainers do not care about this version anymore, see their [changelog](https://github.com/yarnpkg/berry/blob/master/CHANGELOG.md#300).

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
