### ISSUE TITLE
npm run gulp-prod error

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#507]
At install process, command `npm run gulp-prod` produce error:

```
# npm run gulp-prod

> tracim@1.0.0 gulp-prod /data/tracim/releases/build_016
> gulp prod

[09:37:19] Using gulpfile /data/tracim/releases/build_016/gulpfile.js
[09:37:19] Starting 'css'...
[09:37:19] Starting 'js_hint'...
[09:37:19] Starting 'sync group0:0'...
[09:37:19] Starting 'js_transpiling'...
[09:37:19] ✓ PASS: tracim/tracim/public/assets/css/default_skin.css
[09:37:19] ✓ PASS: tracim/tracim/public/assets/js/main.js
[09:37:19] Tested 2 tests, 2 passes, 0 failures: PASS
[09:37:19] ✓ PASS: tracim/tracim/public/assets/css/bootstrap.css
[09:37:19] Finished 'js_hint' after 257 ms
[09:37:19] ✓ PASS: tracim/tracim/public/assets/font-awesome-4.2.0/css/font-awesome.css
[09:37:19] Finished 'js_transpiling' after 268 ms
[09:37:19] Finished 'sync group0:0' after 269 ms
[09:37:19] Starting 'sync group0:1'...
[09:37:19] Starting 'js_concat'...
[09:37:19] ✓ PASS: tracim/tracim/public/assets/select2-4.0.3/css/select2.min.css
[09:37:19] ✓ PASS: tracim/tracim/public/assets/select2-4.0.3/js/select2.min.js
[09:37:19] ✓ PASS: tracim/tracim/public/assets/css/dashboard.css
[09:37:19] Tested 6 tests, 6 passes, 0 failures: PASS
[09:37:19] ✓ PASS: tracim/tracim/public/assets/js/bootstrap.min.js
[09:37:19] ✓ PASS: tracim/tracim/public/assets/js/trad.js
[09:37:19] Finished 'css' after 319 ms
[09:37:19] Starting 'prod_css'...
[09:37:19] ✓ PASS: tracim/tracim/public/assets/js/main_es5.js
[09:37:19] Tested 5 tests, 5 passes, 0 failures: PASS
[09:37:19] ✓ PASS: tracim/tracim/public/assets/dist/all.css
[09:37:19] Tested 2 tests, 2 passes, 0 failures: PASS
[09:37:19] Finished 'js_concat' after 392 ms
[09:37:19] Finished 'sync group0:1' after 393 ms
[09:37:19] Starting 'js_sync'...
[09:37:19] Finished 'js_sync' after 29 μs
[09:37:19] Starting 'js'...
[09:37:19] Finished 'js' after 1.68 μs
[09:37:19] Starting 'prod_js'...
[09:37:19] Finished 'prod_css' after 360 ms
[09:37:19] ✓ PASS: tracim/tracim/public/assets/dist/all.js

events.js:163
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/data/tracim/releases/build_016/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/data/tracim/releases/build_016/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/data/tracim/releases/build_016/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/data/tracim/releases/build_016/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/data/tracim/releases/build_016/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at expr_atom (eval at <anonymous> (/data/tracim/releases/build_016/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2618:13)
    at maybe_unary (eval at <anonymous> (/data/tracim/releases/build_016/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/data/tracim/releases/build_016/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (/data/tracim/releases/build_016/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (/data/tracim/releases/build_016/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)
    at expression (eval at <anonymous> (/data/tracim/releases/build_016/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2875:20)

npm ERR! Linux 4.9.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "gulp-prod"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tracim@1.0.0 gulp-prod: `gulp prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tracim@1.0.0 gulp-prod script 'gulp prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tracim package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tracim
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tracim
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-12-06T08_37_19_905Z-debug.log
```

**Comment by Skylsmoi** [comment]
If the issue has the deprecated label, it's fine for now.

But yes, we don't use gulp anymore so it's clearly outdated
