### ISSUE TITLE
Bug: preview of odp file is broken since Tracim 4.0

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#5090]
## Description and expectations

The odp file is not previewed (Type: application/vnd.oasis.opendocument.presentation). I can seen this error:
~~~
2021-11-12 13:14:47 INFO  [tracim:45][uWSGIWorker3Core3] [TracimRequest] GET /api/workspaces/30/files/31931 from authenticated user 3
2021-11-12 13:14:47 INFO  [tracim:45][uWSGIWorker3Core1] [TracimRequest] GET /api/workspaces/30 from authenticated user 3
2021-11-12 13:14:47 INFO  [tracim:45][uWSGIWorker3Core3] [TracimRequest] GET /api/workspaces/30/files/31931 from authenticated user 3
[pid: 1738|app: 0|req: 118535/374640] 172.18.0.1 () {76 vars in 1425 bytes} [Fri Nov 12 13:14:47 2021] GET /api/workspaces/30 => generated 1215 bytes in 76 msecs (HTTP/1.1 200) 1 headers in 51 bytes (1 switches on core 1)
2021-11-12 13:14:47 INFO  [PreviewGenerator:22][uWSGIWorker3Core3] New Preview builder of class<class 'preview_generator.preview.builder.office__libreoffice.OfficePreviewBuilderLibreoffice'>
2021-11-12 13:14:47 INFO  [PreviewGenerator:22][uWSGIWorker3Core3] New Preview builder of class<class 'preview_generator.preview.builder.office__libreoffice.OfficePreviewBuilderLibreoffice'>
2021-11-12 13:14:47 INFO  [filelock:274][uWSGIWorker3Core3] Lock 139994447632176 acquired on /var/tracim/data/preview/311d3284ca6fb0bef7478e1a86c3dcce.lock
2021-11-12 13:14:47 INFO  [filelock:318][uWSGIWorker3Core3] Lock 139994447632176 released on /var/tracim/data/preview/311d3284ca6fb0bef7478e1a86c3dcce.lock
2021-11-12 13:14:47 WARNI [tracim:48][uWSGIWorker3Core3] [ContentApi] Unknown Preview_Generator Exception Occured
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/marshmallow/utils.py", line 349, in _get_value_for_key
    return obj[key]
TypeError: 'ContentInContext' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tracim_backend/lib/core/content.py", line 1655, in get_preview_page_nb
    nb_pages = self.preview_manager.get_page_nb(file_path, file_ext=file_extension)
  File "/usr/local/lib/python3.9/dist-packages/preview_generator/manager.py", line 143, in get_page_nb
    file_path = self.get_pdf_preview(file_path=file_path, file_ext=file_ext, force=False)
  File "/usr/local/lib/python3.9/dist-packages/preview_generator/manager.py", line 237, in get_pdf_preview
    preview_context.builder.build_pdf_preview(
  File "/usr/local/lib/python3.9/dist-packages/preview_generator/preview/builder/document_generic.py", line 104, in build_pdf_preview
    self._convert_to_pdf(
  File "/usr/local/lib/python3.9/dist-packages/preview_generator/preview/builder/office__libreoffice.py", line 92, in _convert_to_pdf
    return self.convert_office_document_to_pdf(
  File "/usr/local/lib/python3.9/dist-packages/preview_generator/preview/builder/office__libreoffice.py", line 118, in convert_office_document_to_pdf
    raise InputExtensionNotFound("unable to found input extension from mimetype")  # nopep8
preview_generator.exception.InputExtensionNotFound: unable to found input extension from mimetype
2021-11-12 13:14:47 INFO  [PreviewGenerator:22][uWSGIWorker3Core3] New Preview builder of class<class 'preview_generator.preview.builder.office__libreoffice.OfficePreviewBuilderLibreoffice'>
2021-11-12 13:14:47 INFO  [PreviewGenerator:22][uWSGIWorker3Core3] New Preview builder of class<class 'preview_generator.preview.builder.office__libreoffice.OfficePreviewBuilderLibreoffice'>
[pid: 1738|app: 0|req: 118535/374641] 172.18.0.1 () {76 vars in 1461 bytes} [Fri Nov 12 13:14:47 2021] GET /api/workspaces/30/files/31931 => generated 1086 bytes in 267 msecs (HTTP/1.1 200) 1 headers in 51 bytes (1 switches on core 3)
~~~

The log is also not user freindly.

### How to reproduce

- Add an odp file
- try to seen preview of this file

### Version information

- Tracim version: since 4.0
- Web browser: Firefox
- Version: 94
- Device / System: ubuntu 20.04

## Screenshots

________________________________________________

## Implemented solution 
https://github.com/tracim/tracim/pull/5099
- upgrade preview-generator to 0.27 that fix both odp preview and add better exception message

**Comment by PhilippeAccorsi** [comment]
@inkhey you can add information here. Maybe add issue in preview-generator repo about adding test for this use case.

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by MariePrandstetter** [comment]
done
