### ISSUE TITLE
Webdav - (Uwsgi - Apache2): problem with element after restore (with web access)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#520]
**At present:**

With webdav, you can move, create, rename or delete some element. If you delete one element and restore this element with web access of tracim, if after that, you tried to move or copy this element, nothing working good and one message appear: "Error 0x80070021" file is lock by an other part.
### 
==> /var/log/apache2/algoo-access.log <==
192.168.1.78 - - [29/Dec/2017:15:38:48 +0100] "LOCK /webdav/windows10/test/Algoo%20Slack%20export%20Dec%2014%202017.zip%20-%20deleted%20the%2029-12-2017%20at%2015%E2%88%B634.zip HTTP/1.1" 401 481 "-" "Microsoft-WebDAV-MiniRedir/10.0.16299"

==> algoo.trac.im.log <==
<140425989785344> [15:38:48.253] wsgidav:  ErrorPrinter: caught Exception
Traceback (most recent call last):
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/wsgidav/error_printer.py", line 55, in __call__
    for v in app_iter:
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/wsgidav/request_resolver.py", line 206, in __call__
    for v in app_iter:
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/wsgidav/request_server.py", line 127, in __call__
    app_iter = provider.customRequestHandler(environ, start_response, method)
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/wsgidav/dav_provider.py", line 1473, in customRequestHandler
    return defaultHandler(environ, start_response)
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/wsgidav/request_server.py", line 1230, in doLOCK
    lockdiscoveryEL = res.getPropertyValue("{DAV:}lockdiscovery")
AttributeError: 'FakeFileStream' object has no attribute 'getPropertyValue'
AttributeError("'FakeFileStream' object has no attribute 'getPropertyValue'",)
Traceback (most recent call last):
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1068, in communicate
    req.respond()
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 856, in respond
    self.server.gateway(self).respond()
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1960, in respond
    for chunk in response:
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/wsgidav/wsgidav_app.py", line 435, in __call__
    for v in app_iter:
  File "./tracim/lib/webdav/utils.py", line 176, in __call__
    for v in app_iter:
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/wsgidav/error_printer.py", line 55, in __call__
    for v in app_iter:
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/wsgidav/request_resolver.py", line 206, in __call__
    for v in app_iter:
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/wsgidav/request_server.py", line 127, in __call__
    app_iter = provider.customRequestHandler(environ, start_response, method)
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/wsgidav/dav_provider.py", line 1473, in customRequestHandler
    return defaultHandler(environ, start_response)
  File "/home/testalgoo/tracim/tg2env/lib/python3.5/site-packages/wsgidav/request_server.py", line 1230, in doLOCK
    lockdiscoveryEL = res.getPropertyValue("{DAV:}lockdiscovery")
AttributeError: 'FakeFileStream' object has no attribute 'getPropertyValue'

==> /var/log/apache2/algoo-access.log <==
192.168.1.78 - - [29/Dec/2017:15:38:48 +0100] "LOCK /webdav/windows10/test/Algoo%20Slack%20export%20Dec%2014%202017.zip%20-%20deleted%20the%2029-12-2017%20at%2015%E2%88%B634.zip HTTP/1.1" 500 171 "-" "Microsoft-WebDAV-MiniRedir/10.0.16299

**Expected:**

After restoration, it is possible to perform the same operations as before the deletion.

**Comment by inkhey** [comment]
#545 fix should be test on this bug. Same case error fixed, but without similar error log as far i go.
