### ISSUE TITLE
Bug: Impossible to create an account of the community instance

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#5253]
## Description and expectations

When a user tries to register on the community (https://community.tracim.fr) instance a 500 error is generated by the backend and the registration fails.

### How to reproduce

1. Go to the community site
2. Register a new account

### Version information

- Tracim version: 4.0.3
- Web browser: Any

### Screenshots

________________________________________________

## Diagnostic

The backend error log:

```
2022-01-06 21:20:58 INFO  [hapic:212][uWSGIWorker1Core2] Exception TypeError occured, return 500 http_code : 'NoneType' object is not subscriptable
2022-01-06 21:20:58 DEBUG [hapic:217][uWSGIWorker1Core2] Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyramid_tm/__init__.py", line 83, in _finish
    finisher()
  File "/usr/local/lib/python3.9/dist-packages/transaction/_manager.py", line 134, in commit
    return self.get().commit()
  File "/usr/local/lib/python3.9/dist-packages/transaction/_transaction.py", line 282, in commit
    reraise(t, v, tb)
  File "/usr/local/lib/python3.9/dist-packages/transaction/_compat.py", line 49, in reraise
    raise value
  File "/usr/local/lib/python3.9/dist-packages/transaction/_transaction.py", line 273, in commit
    self._commitResources()
  File "/usr/local/lib/python3.9/dist-packages/transaction/_transaction.py", line 456, in _commitResources
    reraise(t, v, tb)
  File "/usr/local/lib/python3.9/dist-packages/transaction/_compat.py", line 49, in reraise
    raise value
  File "/usr/local/lib/python3.9/dist-packages/transaction/_transaction.py", line 428, in _commitResources
    rm.tpc_begin(self)
  File "/usr/local/lib/python3.9/dist-packages/zope/sqlalchemy/datamanager.py", line 127, in tpc_begin
    self.session.flush()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2646, in _flush
    self.dispatch.after_flush(self, flush_context)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "./tracim_backend/lib/crud_hook/caller.py", line 40, in _call_hooks
    self._plugin_manager.hook.on_user_role_in_workspace_created(
  File "/usr/local/lib/python3.9/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/local/lib/python3.9/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.9/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "./tracim_backend/lib/core/event.py", line 584, in on_user_role_in_workspace_created
    self._create_workspace_historic_messages_for_current_user(role, context)
  File "./tracim_backend/lib/core/event.py", line 592, in _create_workspace_historic_messages_for_current_user
    event_api.create_messages_history_for_user(
  File "./tracim_backend/lib/core/event.py", line 385, in create_messages_history_for_user
    receiver_ids = BaseLiveMessageBuilder.get_receiver_ids(event, session, self._config)
  File "./tracim_backend/lib/core/event.py", line 987, in get_receiver_ids
    return get_receiver_ids(event, session, config)
  File "./tracim_backend/lib/core/event.py", line 899, in _get_members_and_administrators_ids
    event_user_id = get_event_user_id(session, event)
  File "./tracim_backend/lib/core/event.py", line 871, in get_event_user_id
    return session.query(User.user_id).filter(User.user_id == event.user["user_id"]).scalar()
TypeError: 'NoneType' object is not subscriptable

2022-01-06 21:20:58 DEBUG [tracim:39][uWSGIWorker1Core2] [TracimPyramidContext] Transaction not active, status : "Commit failed", cannot be doomed
[pid: 11095|app: 0|req: 2055/19071] 172.18.0.1 () {84 vars in 1393 bytes} [Thu Jan  6 21:20:53 2022] POST /api/users/register => generated 100 bytes in 5036 msecs (HTTP/1.1 500) 5 headers in 274 bytes (1 switches on core 2)

==> /data/tracimv2/0057_community/var/logs/apache2-access.log <==
172.18.0.1 - - [06/Jan/2022:21:20:53 +0000] "POST /api/users/register HTTP/1.1" 500 485 "https://community.tracim.fr/ui/login" "Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"

```

It seems to (again) be an interaction with the auto-invite plugin.

## Implemented solution 
#5258 
- Explicit support of None user case making it possible to create account with similar data in database.
- add a Try/catch for all exception to be more resilient from future case of similar error, permitting to not broke the registration/add user to workspace feature, in case there are issues with existing event history.

**Comment by inkhey** [comment]
The problem is related to some existing event that doesn't look correct

```python
<Event(
event_id=18416, 
type='workspace_member.deleted', 
created_date=datetime.datetime(2021, 6, 22, 8, 25, 11, 880836), 
fields={'member': {'do_notify': True, 'role': 'reader'}, 
'author': None,
'workspace': {'public_download_enabled': True, 'workspace_id': 145, 'default_user_role': 'reader', 
  'owner': {'has_avatar': True, 'public_name': '*************', 'username': '********', 'has_cover': False, 'user_id': 233}, 
  'slug': '2-0', 
  'sidebar_entries': [{'hexcolor': '#fdfdfd', 'label': 'Dashboard', 'slug': 'dashboard', 'route': '/ui/workspaces/145/dashboard', 'fa_icon':  'fas fa-tachometer-alt'}, {'hexcolor': '#bbbbbb', 'label': 'Contents', 'slug': 'contents/all', 'route': '/ui/workspaces/145/contents', 'fa_icon': 'fas fa-th'}, {'hexcolor': '#999999', 'label': 'Gallery', 'slug': 'gallery', 'route': '/ui/workspaces/145/gallery', 'fa_icon': 'far fa-image'}],
   'is_deleted': False,
   'public_upload_enabled': True,
   'created': '2021-03-24T14:35:05Z',
   'access_type': 'open', 'parent_id': 97, 'label': '2.0', 
  'publication_enabled': False, 
  'agenda_enabled': False
}, 
'user': None,
 'client_token': None})>
```

**Comment by inkhey** [comment]
After some search, it seems that in 4.0.3, 
- the TLM are properly created with the user (manually tested) during user deletion process through tracimcli
- It was not always the case: https://github.com/tracim/tracim/commit/21d30becb14b002496da3f69aafef19a0b0387be#diff-72c6b7755d934424817a53b0ea38ecd8a5810b71100d853bfb361363a73d0e13

So the issue is related to buggy existing data in the event table.

**Comment by lebouquetin** [comment]
@grignards @inkhey : what is expected for `develop`? It looks like you work on a maintenance release (which is good), but do you planned to report this into `develop` for Tracim 4.1 which will be release next week?

**Comment by grignards** [comment]
Yes we discussed it with @inkhey, the fix will be merged into develop as soon as the corresponding maintenance version (4.0.6) is released.

**Comment by PhilippeAccorsi** [comment]
Done
