### ISSUE TITLE
MemoryError while copy big file with webdav (v1)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#534]
At present:

I tried to copy a big file (near 500MB) with webdav access, but one error appear in uwsgi log:

`==> /var/log/apache2/algoo-access.log <==
192.168.1.78 - - [26/Jan/2018:10:16:44 +0100] "HEAD /webdav/exf/test/DockerToolbox.zip HTTP/1.1" 401 361 "-" "Microsoft-WebDAV-MiniRedir/10.0.16299"

==> /var/log/apache2/algoo-error.log <==
[Fri Jan 26 10:16:44.020897 2018] [proxy:warn] [pid 8604:tid 140591635547904] AH03408: HTTP: reusable backend connection is not empty: forcibly closed

==> /var/log/uwsgi/app/tracim.log <==
<139818608609024> 127.0.0.1 - admin@admin.admin - [2018-01-26 09:16:44] "HEAD /exf/test/DockerToolbox.zip" depth=0, elap=0.186sec -> 200 OK

==> /var/log/apache2/algoo-access.log <==
192.168.1.78 - - [26/Jan/2018:10:16:44 +0100] "HEAD /webdav/exf/test/DockerToolbox.zip HTTP/1.1" 200 239 "-" "Microsoft-WebDAV-MiniRedir/10.0.16299"

==> /var/log/uwsgi/app/tracim.log <==
<139818608609024> 127.0.0.1 - (anonymous) - [2018-01-26 09:16:44] "PUT /exf/test/DockerToolbox.zip" length=604076684, elap=0.001sec -> 401 Not Authorized
MemoryError()
Traceback (most recent call last):
  File "/var/www/tracim/tg2env/lib/python3.5/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1068, in communicate
    req.respond()
  File "/var/www/tracim/tg2env/lib/python3.5/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 856, in respond
    self.server.gateway(self).respond()
  File "/var/www/tracim/tg2env/lib/python3.5/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1970, in respond
    self.write(chunk)
  File "/var/www/tracim/tg2env/lib/python3.5/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 2040, in write
    self.req.send_headers()
  File "/var/www/tracim/tg2env/lib/python3.5/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 958, in send_headers
    self.rfile.read(remaining)
  File "/var/www/tracim/tg2env/lib/python3.5/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 331, in read
    data = self.rfile.read(size)
  File "/usr/lib/python3.5/_pyio.py", line 1000, in read
    return self._read_unlocked(size)
  File "/usr/lib/python3.5/_pyio.py", line 1040, in _read_unlocked
    chunk = self.raw.read(wanted)
MemoryError

==> /var/log/apache2/algoo-error.log <==
[Fri Jan 26 10:16:44.289005 2018] [proxy:error] [pid 8604:tid 140591618762496] (104)Connection reset by peer: [client 192.168.1.78:50101] AH01084: pass request body failed to 127.0.0.1:3030 (127.0.0.1)
[Fri Jan 26 10:16:44.290082 2018] [proxy_http:error] [pid 8604:tid 140591618762496] [client 192.168.1.78:50101] AH01097: pass request body failed to 127.0.0.1:3030 (127.0.0.1) from 192.168.1.78 ()

==> /var/log/uwsgi/app/tracim.log <==
INFO:root:OPTIONS request at /user/ received
INFO:root:PROPFIND request at /user/ received
INFO:root:OPTIONS request at /user/ received
INFO:root:PROPFIND request at /user/ received
INFO:root:OPTIONS request at /workspace/ received
INFO:root:PROPFIND request at /workspace/ received
INFO:root:OPTIONS request at /workspace/ received
INFO:root:PROPFIND request at /workspace/ received

==> /var/log/apache2/algoo-access.log <==
192.168.1.78 - - [26/Jan/2018:10:16:44 +0100] "PUT /webdav/exf/test/DockerToolbox.zip HTTP/1.1" 502 522 "-" "Microsoft-WebDAV-MiniRedir/10.0.16299"

==> /var/log/uwsgi/app/tracim.log <==
<139818591823616> 127.0.0.1 - (anonymous) - [2018-01-26 09:17:15] "PROPFIND /exf/test" length=0, depth=0, elap=0.000sec -> 401 Not Authorized`

Its not possible to copy this big file. **With file near 250MB, no error appear.**

Expected:

Its possible to copy big file and inform user about max size of file its possible to copy.

**Comment by PhilippeAccorsi** [comment]
This is not limitation about file size but limitation about memory size (RAM).

If my server run with 512MB or 1GB of ram memory, when I tried to copy big file (590MB), i have the MemoryError.

If my server run with 4GB of ram, copy is working good.

So I think the problem is: copy use ram first, before write on disk; and If this ram is not so big, copy is not possible.

Expected:

Find option to copy correctly a big file.
