### ISSUE TITLE
Misc: frontend unit tests fail on Node 16+ 

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#5352]
## Description and expectations

Frontend unit tests currently succeed on Node 12 and possibly 14. However, they issue a lot of warning related to unhandled exceptions and promise rejections.

These unhandled errors make the unit test fail.

The fact tests work on previous versions of Node is a bit concerning and I wonder is everything indeed tested or some things just fail silently. I think things are indeed tested but that needs to be checked so we might as well fix things. 

Related to https://github.com/tracim/tracim/issues/4981 which asks for fixing the warnings we are seeing (that are fatal errors now). 

### How to reproduce

1. Use node 16
2. `cd frontend; yarn test:quick`

### Version information

- Tracim version: 3.X, 4.1, 4.2 to be released
- Node 16

### Console output

```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
[BABEL] Note: The code generator has deoptimised the styling of /home/raphael/dl/tracim/frontend_lib/dist/tracim_frontend_lib.lib.standalone.js as it exceeds the max of 500KB.
This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills
This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: I18n
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: t
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(Translate(PersonalData)), Provider
Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(Translate(PersonalData))
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    in a (created by LinkAnchor)
    in LinkAnchor (created by Context.Consumer)
    in Link
    in bf
    in t
    in Translate(bf) (created by TimedEvent)
    in div (created by TimedEvent)
    in div (created by TimedEvent)
    in TimedEvent (created by I18n)
    in I18n (created by Translate(TimedEvent))
    in Translate(TimedEvent) (created by AdvancedSearchContentList)
    in div (created by AdvancedSearchContentList)
    in a (created by LinkAnchor)
    in LinkAnchor (created by Context.Consumer)
    in Link (created by AdvancedSearchContentList)
    in div
    in k_ (created by AdvancedSearchContentList)
    in div (created by AdvancedSearchContentList)
    in AdvancedSearchContentList (created by I18n)
    in I18n (created by Translate(AdvancedSearchContentList))
    in Translate(AdvancedSearchContentList) (created by AdvancedSearch)
    in div (created by AdvancedSearch)
    in div (created by AdvancedSearch)
    in div
    in Xh (created by AdvancedSearch)
    in div
    in e_ (created by AdvancedSearch)
    in div (created by AdvancedSearch)
    in div (created by AdvancedSearch)
    in AdvancedSearch (created by withRouterMock)
    in withRouterMock
    in Router (created by MemoryRouter)
    in MemoryRouter
    in Provider (created by WrapperComponent)
    in WrapperComponent
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(Translate(SearchFilterMenu))
Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(Translate(SearchFilterMenu))
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(Translate(_temp))
Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(Translate(_temp))
TypeError: Cannot read properties of undefined (reading 'userId')
    at _callee4$ (/home/raphael/dl/tracim/frontend/src/container/withActivity.jsx:241:22)
    at tryCatch (/home/raphael/dl/tracim/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/raphael/dl/tracim/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/home/raphael/dl/tracim/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/raphael/dl/tracim/frontend/src/container/withActivity.jsx:26:103)
    at _next (/home/raphael/dl/tracim/frontend/src/container/withActivity.jsx:28:194)
    at /home/raphael/dl/tracim/frontend/src/container/withActivity.jsx:28:364
    at new Promise (<anonymous>)
    at _temp.<anonymous> (/home/raphael/dl/tracim/frontend/src/container/withActivity.jsx:28:97)
    at _temp.loadActivitiesBatch (/home/raphael/dl/tracim/frontend/src/container/withActivity.jsx:61:25)
    at _callee3$ (/home/raphael/dl/tracim/frontend/src/container/withActivity.jsx:169:16)
    at tryCatch (/home/raphael/dl/tracim/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/raphael/dl/tracim/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/home/raphael/dl/tracim/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/raphael/dl/tracim/frontend/src/container/withActivity.jsx:26:103)
    at _next (/home/raphael/dl/tracim/frontend/src/container/withActivity.jsx:28:194)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:15697) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node16 --trace-deprecation ...` to show where the warning was created)

  1) Uncaught error outside test suite

  0 passing (5ms)
  1 failing

  1) Uncaught error outside test suite:
     Uncaught TypeError: Cannot read properties of undefined (reading 'status')
      at _callee4$ (src/component/Account/UserSpacesConfig.jsx:97:39)
      at tryCatch (/home/raphael/dl/tracim/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (/home/raphael/dl/tracim/node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (/home/raphael/dl/tracim/node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (src/component/Account/UserSpacesConfig.jsx:44:103)
      at _next (src/component/Account/UserSpacesConfig.jsx:46:194)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)



/home/raphael/dl/tracim/node_modules/mocha/lib/runner.js:911
    throw err;
    ^

TypeError: props.dispatch is not a function
    at _callee2$ (/home/raphael/dl/tracim/frontend/src/container/PublicProfile.jsx:198:38)
    at tryCatch (/home/raphael/dl/tracim/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/raphael/dl/tracim/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/home/raphael/dl/tracim/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/raphael/dl/tracim/frontend/src/container/PublicProfile.jsx:52:103)
    at _next (/home/raphael/dl/tracim/frontend/src/container/PublicProfile.jsx:54:194)
    at /home/raphael/dl/tracim/frontend/src/container/PublicProfile.jsx:54:364
    at new Promise (<anonymous>)
    at PublicProfile.getUser (/home/raphael/dl/tracim/frontend/src/container/PublicProfile.jsx:54:97)
    at PublicProfile.componentDidMount (/home/raphael/dl/tracim/frontend/src/container/PublicProfile.jsx:156:10)
    at fn (/home/raphael/dl/tracim/frontend/node_modules/enzyme/src/ShallowWrapper.js:415:22)
    at Object.batchedUpdates (/home/raphael/dl/tracim/frontend/node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:722:16)
    at new ShallowWrapper (/home/raphael/dl/tracim/frontend/node_modules/enzyme/src/ShallowWrapper.js:414:26)
    at shallow (/home/raphael/dl/tracim/frontend/node_modules/enzyme/src/shallow.js:10:10)
    at Suite.<anonymous> (/home/raphael/dl/tracim/frontend/test/src/container/PublicProfile.spec.js:20:19)
    at Object.create (/home/raphael/dl/tracim/node_modules/mocha/lib/interfaces/common.js:141:19)
    at describe (/home/raphael/dl/tracim/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/home/raphael/dl/tracim/frontend/test/src/container/PublicProfile.spec.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/home/raphael/dl/tracim/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/home/raphael/dl/tracim/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImport (/home/raphael/dl/tracim/node_modules/mocha/lib/esm-utils.js:15:12)
    at Object.exports.loadFilesAsync (/home/raphael/dl/tracim/node_modules/mocha/lib/esm-utils.js:28:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at singleRun (/home/raphael/dl/tracim/node_modules/mocha/lib/cli/run-helpers.js:149:3)
    at exports.runMocha (/home/raphael/dl/tracim/node_modules/mocha/lib/cli/run-helpers.js:186:5)
    at Object.exports.handler (/home/raphael/dl/tracim/node_modules/mocha/lib/cli/run.js:319:5)
```

### Diagnostic

 - api mocks are missing
 - properties when mounting components are missing
 - some HOCs might be missing (for instance some errors are related to `props.dispatch` not being there

**Comment by Skylsmoi** [comment]
fixed by https://github.com/tracim/tracim/pull/6701
