### ISSUE TITLE
Davfs 2 compat

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#557]
Currently:

Copy and add file from webdav mounted by davfs2 is not possible.

Expected:

Copy and add file from webdav davfs should work.

**Comment by inkhey** [comment]
https://github.com/tracim/tracim/pull/558/commits/f2476d9462ca911fb2539c5af0b46029d693312c fix this issue partially, .

As davfs2 do, instead of erasing, creating temp file , delete source, move.
Move part cause some trouble when trying to erase new file :
```
[Traceback (most recent call last):
  File "/home/guenael/tracim/tg2env/lib/python3.5/site-packages/wsgidav/request_server.py", line 1007, in _copyOrMove
    errorList = srcRes.moveRecursive(destPath)
  File "/home/guenael/tracim/tracim/tracim/lib/webdav/sql_resources.py", line 937, in moveRecursive
    self.move_file(destpath)
  File "/home/guenael/tracim/tracim/tracim/lib/webdav/sql_resources.py", line 956, in move_file
    workspace = self.content.workspace
  File "/home/guenael/tracim/tg2env/lib/python3.5/site-packages/sqlalchemy/ext/hybrid.py", line 742, in __get__
    return self.fget(instance)
  File "/home/guenael/tracim/tracim/tracim/model/data.py", line 1016, in workspace
    return self.revision.workspace
  File "/home/guenael/tracim/tg2env/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/guenael/tracim/tg2env/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 583, in get
    value = self.callable_(state, passive)
  File "/home/guenael/tracim/tg2env/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 505, in _load_for_state
    (orm_util.state_str(state), self.key)
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <ContentRevisionRO at 0x7f565802ccc0> is not bound to a Session; lazy load operation of attribute 'workspace' cannot proceed](url)
```

**Comment by inkhey** [comment]
Move part trouble is related to  #560, it is not davfs2 specific and probably not Lock related. It's a different problem than LOCK issue solve in  #558
