### ISSUE TITLE
acceptance of the publication of a file without the said file

### ISSUE THREAD

**Issue by ghost** [tracim/tracim#568]
Tracim accepts to publish a file even though it does not contain any and it then returns on an error page

**Comment by buxx** [comment]
To reproduce:

1. Create workspace (or use existing)
2. Create folder
3. Add file content
4. Validate form with filename but don't select file

Stacktrace example:

```
Traceback (most recent call last):
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/wsgiapp.py", line 122, in __call__
    response = self.wrapped_dispatch(controller, environ, context)
  File "/data/tracim/releases/build_021/tracim/tracim/lib/utils.py", line 100, in __call__
    return super().__call__(controller, environ, context)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/errorpage.py", line 56, in __call__
    resp = self.next_handler(controller, environ, context)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/transaction_manager.py", line 107, in __call__
    reraise(*exc_info)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/_compat.py", line 81, in reraise
    raise value
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/transaction_manager.py", line 83, in __call__
    response = self.next_handler(controller, environ, context)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/caching.py", line 54, in __call__
    return self.next_handler(controller, environ, context)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/session.py", line 71, in __call__
    response = self.next_handler(controller, environ, context)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/identity.py", line 75, in __call__
    return self.next_handler(controller, environ, context)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/appwrappers/i18n.py", line 71, in __call__
    return self.next_handler(controller, environ, context)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/wsgiapp.py", line 295, in dispatch
    return controller(environ, context)
  File "/data/tracim/releases/build_021/tracim/tracim/lib/base.py", line 32, in __call__
    return TGController.__call__(self, environ, context)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/controllers/dispatcher.py", line 128, in __call__
    response = self._perform_call(context)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/controllers/dispatcher.py", line 109, in _perform_call
    r = self._call(func, params, remainder=remainder, context=context)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/controllers/decoratedcontroller.py", line 121, in _call
    output = controller_caller(context_config, bound_controller_callable, remainder, params)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/decorators.py", line 44, in _decorated_controller_caller
    return application_controller_caller(tg_config, controller, remainder, params)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/tgext/pluggable/i18n.py", line 22, in _add_pluggable_translations
    return next_caller(config, controller, remainder, params)
  File "/data/tracim/releases/build_021/venv/lib/python3.5/site-packages/TurboGears2-2.3.7-py3.5.egg/tg/configuration/app_config.py", line 127, in call_controller
    return controller(*remainder, **params)
  File "/data/tracim/releases/build_021/tracim/tracim/controllers/content.py", line 353, in post
    file_data.filename,
AttributeError: 'bytes' object has no attribute 'filename' 
```

**Comment by Quiwy** [comment]
@buxx : does this bug still present? I can't manage to add a file without content. Maybe this changed in recent tracim versions?

**Comment by buxx** [comment]
@Quiwy It is outdated, I close it :)
