### ISSUE TITLE
🐛 Bug: connection with LDAP seems not working with Synology LDAP plugin

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#6319]
### Tracim version

4.7.0 arm docker images builded locally

### Issue description

I used my own LDAP server on my Synology DS214play (version : DSM 7.1.1-42962 Update 5) and I tried to use it with tracim.

On tracim login page I set email and password and after validation I seen this error:

- tracim popup

```
Erreur
Erreur inattendue, veuillez contacter un administrateur
Détail de l'erreur
```

- In devtools

```
{
	"message": "character '\"' not allowed in attribute type",
	"details": {
		"error_detail": {}
	},
	"code": null
}
```

- In tracim log

```
[pid: 1153|app: 0|req: 2/4] 172.18.0.1 () {76 vars in 1307 bytes} [Sat Dec  9 12:25:44 2023] GET /api/system/config => generated 31551 bytes in 152 msecs (HTTP/1.1 200) 2 headers in 76 bytes (1 switches on core 3)
tracim  | 2023-12-09 12:26:15 INFO  [hapic:212][uWSGIWorker4Core2] Exception LDAPInvalidDnError occured, return 500 http_code : character '"' not allowed in attribute type
tracim  | 2023-12-09 12:26:15 DEBUG [hapic:217][uWSGIWorker4Core2] Traceback (most recent call last):
tracim  |   File "/usr/local/lib/python3.9/dist-packages/pyramid/tweens.py", line 41, in excview_tween
tracim  |     response = handler(request)
tracim  |   File "/usr/local/lib/python3.9/dist-packages/pyramid/router.py", line 143, in handle_request
tracim  |     response = _call_view(
tracim  |   File "/usr/local/lib/python3.9/dist-packages/pyramid/view.py", line 674, in _call_view
tracim  |     response = view_callable(context, request)
tracim  |   File "/usr/local/lib/python3.9/dist-packages/pyramid/viewderivers.py", line 319, in secured_view
tracim  |     return view(context, request)
tracim  |   File "/usr/local/lib/python3.9/dist-packages/pyramid/viewderivers.py", line 392, in viewresult_to_response
tracim  |     result = view(context, request)
tracim  |   File "/usr/local/lib/python3.9/dist-packages/pyramid/viewderivers.py", line 92, in mapped_view
tracim  |     return _mapped_view(context, request)
tracim  |   File "/usr/local/lib/python3.9/dist-packages/hapic/hapic.py", line 175, in wrapper
tracim  |     return func(*args, **kwargs)
tracim  |   File "/usr/local/lib/python3.9/dist-packages/hapic/decorator.py", line 126, in wrapper
tracim  |     response = self._execute_wrapped_function(func, args, kwargs)
tracim  |   File "/usr/local/lib/python3.9/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
tracim  |     return func(*func_args, **func_kwargs)
tracim  |   File "/usr/local/lib/python3.9/dist-packages/hapic/decorator.py", line 126, in wrapper
tracim  |     response = self._execute_wrapped_function(func, args, kwargs)
tracim  |   File "/usr/local/lib/python3.9/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
tracim  |     return func(*func_args, **func_kwargs)
tracim  |   File "/usr/local/lib/python3.9/dist-packages/hapic/decorator.py", line 126, in wrapper
tracim  |     response = self._execute_wrapped_function(func, args, kwargs)
tracim  |   File "/usr/local/lib/python3.9/dist-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
tracim  |     return func(*func_args, **func_kwargs)
tracim  |   File "./tracim_backend/views/core_api/session_controller.py", line 49, in login
tracim  |     user = uapi.authenticate(
tracim  |   File "./tracim_backend/lib/core/user.py", line 760, in authenticate
tracim  |     return self._authenticate(
tracim  |   File "./tracim_backend/lib/core/user.py", line 868, in _authenticate
tracim  |     return self._ldap_authenticate(user, login, password, ldap_connector)
tracim  |   File "./tracim_backend/lib/core/user.py", line 561, in _ldap_authenticate
tracim  |     data = ldap_connector.authenticate(login, password)
tracim  |   File "/usr/local/lib/python3.9/dist-packages/pyramid_ldap3/__init__.py", line 208, in authenticate
tracim  |     result = search.execute(
tracim  |   File "/usr/local/lib/python3.9/dist-packages/pyramid_ldap3/__init__.py", line 85, in execute
tracim  |     ret = conn.search(
tracim  |   File "/usr/local/lib/python3.9/dist-packages/ldap3/core/connection.py", line 796, in search
tracim  |     search_base = safe_dn(search_base)
tracim  |   File "/usr/local/lib/python3.9/dist-packages/ldap3/utils/dn.py", line 353, in safe_dn
tracim  |     for component in parse_dn(dn, escape=True):
tracim  |   File "/usr/local/lib/python3.9/dist-packages/ldap3/utils/dn.py", line 315, in parse_dn
tracim  |     if not _validate_attribute_type(attribute_type):
tracim  |   File "/usr/local/lib/python3.9/dist-packages/ldap3/utils/dn.py", line 179, in _validate_attribute_type
tracim  |     raise LDAPInvalidDnError('character \'' + c + '\' not allowed in attribute type')
tracim  | ldap3.core.exceptions.LDAPInvalidDnError: character '"' not allowed in attribute type
tracim  |
tracim  | [pid: 1153|app: 0|req: 3/5] 172.18.0.1 () {80 vars in 1362 bytes} [Sat Dec  9 12:26:15 2023] POST /api/auth/login => generated 106 bytes in 83 msecs (HTTP/1.1 500) 6 headers in 300 bytes (1 switches on core 2)
```

- This is what I set in my docker-compose.yml file

```
version: "3"
...
      - TRACIM_AUTH_TYPES=ldap,internal
      - TRACIM_LDAP_URL=ldap://192.168.1.45:389
      - TRACIM_LDAP_BIND_DN="uid=root,cn=users,dc=ldap,dc=myname,dc=fr"
      - TRACIM_LDAP_BIND_ANONYMOUS=True
      - TRACIM_LDAP_TLS=False
      - TRACIM_LDAP_USER_BASE_DN="dc=ldap,dc=myname,dc=fr"
      - TRACIM_LDAP_MAIL_ATTRIBUTE=email
      - TRACIM_LDAP_USERNAME_ATTRIBUTE=displayname
```

I don't understand what is wrong and error message is not explicit.

### How to reproduce

- add LDAP server in Synology NAS
- create a user
- set config in tracim docker-compose file
- start tracim
- try to connect with ldap user

### What browsers are you seeing the problem on?

Firefox

### What devices are you seeing the problem on?

Desktop

**Comment by PhilippeAccorsi** [comment]
If i try this command in my terminal, i can seen user information from ldap
`ldapsearch -x -LLL -H ldap://192.168.1.45:389 -b "dc=ldap,dc=myname,dc=fr"`

**Comment by PhilippeAccorsi** [comment]
After fix this, I also can't login with ldap user. Credential result indicate wrong credential.
I don't understand what is wrong and documentation is not explicit (no real config example to understand what I need to do).

**Comment by PhilippeAccorsi** [comment]
I find one first problem. The parameter `TRACIM_LDAP_USERNAME_ATTRIBUTE` need to be set with ldap key used to authenticate (username here is for `Identifiant :` in login page). 
If you want to authenticate with an email, you need to set `TRACIM_LDAP_USERNAME_ATTRIBUTE=mail` (This parameter is not for auth `TRACIM_LDAP_MAIL_ATTRIBUTE=mail`. This is used to take mail value and set tracim with this value).

**Comment by PhilippeAccorsi** [comment]
With new tracim config, I can seen email appear in ldap log, but auth not working. I not seen explicit error with journalctl in my Synology:
```
Dec 09 15:40:18 NASNAME slapd[12933]: [search.c:219] conn=6135 op=1 SRCH base="dc=ldap,dc=myname,dc=fr" scope=1 deref=3 filter="(mail={value_from_login_page})"
Dec 09 15:40:18 NASNAME slapd[12933]: [search.c:242] conn=6135 op=1 SRCH attr=*
Dec 09 15:40:18 NASNAME slapd[12933]: [filterindex.c:746] <= bdb_equality_candidates: (mail) not indexed
Dec 09 15:40:18 NASNAME slapd[12933]: [result.c:866] conn=6135 op=1 SEARCH RESULT tag=101 err=0 nentries=0 text=
`````
