### ISSUE TITLE
🐛 Bug: Installing cypress on ubuntu 23.10

### ISSUE THREAD

**Issue by HenraL** [tracim/tracim#6352]
### Tracim version

latest, as of 11/02/2024

### Issue description

Pip installer fails to find a version that satisfies pyyaml when on python version 3.11.6

### How to reproduce

1. Install ubuntu server 23.10
2. clone the 7223a9b8e07aa165c3ea329bbd5f3e833a45ece2 version of the repository
3. Install npm
4. Enter the repository
5. run the ./setup_default_backend.sh and let it run it's course until it breaks

### Screenshots

![image](https://github.com/tracim/tracim/assets/37299738/20f3217b-dc99-4103-8897-a12526d6698a)

Here is the log:

[14:16:37] $ Checking whether npm is installed

[14:16:38] $ npm 9.2.0 is installed

[14:16:38] $ Installing Tracim font in system...

[14:16:41] $ Installing system package dependencies for the backend...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 http://security.ubuntu.com/ubuntu mantic-security InRelease
Hit:2 http://fr.archive.ubuntu.com/ubuntu mantic InRelease
Hit:3 http://fr.archive.ubuntu.com/ubuntu mantic-updates InRelease
Hit:4 http://fr.archive.ubuntu.com/ubuntu mantic-backports InRelease
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.

[14:16:43] $ add optional preview dependencies to the list of package to install...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.10ubuntu1).
libjpeg-dev is already the newest version (8c-2ubuntu11).
libmagickwand-dev is already the newest version (8:6.9.11.60+dfsg-1.6ubuntu1).
libpq-dev is already the newest version (15.5-0ubuntu0.23.10.1).
python3-dev is already the newest version (3.11.4-5).
python3-venv is already the newest version (3.11.4-5).
ghostscript is already the newest version (10.01.2~dfsg1-0ubuntu2.2).
git is already the newest version (1:2.40.1-1ubuntu1).
imagemagick is already the newest version (8:6.9.11.60+dfsg-1.6ubuntu1).
libmagickcore-6.q16-6-extra is already the newest version (8:6.9.11.60+dfsg-1.6ubuntu1).
iproute2 is already the newest version (6.1.0-1ubuntu2).
libfile-mimeinfo-perl is already the newest version (0.33-1).
libimage-exiftool-perl is already the newest version (12.65+dfsg-1).
webp is already the newest version (1.2.4-0.3).
libmagic1 is already the newest version (1:5.44-3).
locales is already the newest version (2.38-1ubuntu6.1).
poppler-utils is already the newest version (23.08.0-2ubuntu1).
python3 is already the newest version (3.11.4-5).
python3-pip is already the newest version (23.2+dfsg-1ubuntu0.1).
pandoc is already the newest version (2.17.1.1-3ubuntu1).
libpango-1.0-0 is already the newest version (1.51.0+ds-2).
libpangoft2-1.0-0 is already the newest version (1.51.0+ds-2).
fonts-noto-color-emoji is already the newest version (2.042-0ubuntu0.23.10.1).
cron is already the newest version (3.0pl1-163ubuntu1).
xmlsec1 is already the newest version (1.2.37-2).
ffmpeg is already the newest version (7:6.0-6ubuntu1).
xvfb is already the newest version (2:21.1.7-3ubuntu2.7).
inkscape is already the newest version (1.2.2-2ubuntu4).
libreoffice is already the newest version (4:7.6.4-0ubuntu0.23.10.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

[14:16:43] $  correctly installed

[14:16:43] $ Setting up the python3 virtual environment...

[14:16:47] $ Successfully created the python3 virtual environment

[14:16:47] $ python3 env activated

[14:16:47] $ Installing pip and setuptools...
Collecting pip==21.1.3 (from -r requirements-build.txt (line 3))
  Downloading pip-21.1.3-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 24.1 MB/s eta 0:00:00
Collecting setuptools==57.0.0 (from -r requirements-build.txt (line 4))
  Downloading setuptools-57.0.0-py3-none-any.whl (821 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 821.7/821.7 kB 32.3 MB/s eta 0:00:00
Requirement already satisfied: wheel==0.36.2 in ./env/lib/python3.11/site-packages (from -r requirements-build.txt (line 5)) (0.36.2)
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 68.1.2
    Uninstalling setuptools-68.1.2:
      Successfully uninstalled setuptools-68.1.2
  Attempting uninstall: pip
    Found existing installation: pip 23.2
    Uninstalling pip-23.2:
      Successfully uninstalled pip-23.2
Successfully installed pip-21.1.3 setuptools-57.0.0

[14:16:50] $ Successfully installed pip and setuptools

[14:16:50] $ Installing dependencies from requirements.txt...
Collecting webpreview@ git+https://github.com/algoo/webpreview@v1.6.0+algoo
  Cloning https://github.com/algoo/webpreview (to revision v1.6.0+algoo) to /tmp/pip-install-ox2cghqz/webpreview_8a92e4cc3b274944b3c477b95bf9fc41
  Running command git clone -q https://github.com/algoo/webpreview /tmp/pip-install-ox2cghqz/webpreview_8a92e4cc3b274944b3c477b95bf9fc41
  Running command git checkout -q 58b1640b7f8bd89ee787b218d701e5e62204291f
Collecting alembic==1.6.5
  Downloading alembic-1.6.5-py2.py3-none-any.whl (164 kB)
Collecting anyascii==0.2.0
  Downloading anyascii-0.2.0-py3-none-any.whl (283 kB)
Collecting apispec==2.0.2
  Downloading apispec-2.0.2-py2.py3-none-any.whl (24 kB)
Collecting apispec-marshmallow-advanced==0.4
  Downloading apispec_marshmallow_advanced-0.4-py3-none-any.whl (5.1 kB)
Collecting attrs==21.4.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting babel==2.9.1
  Downloading Babel-2.9.1-py2.py3-none-any.whl (8.8 MB)
Collecting beaker==1.10.1
  Downloading Beaker-1.10.1.tar.gz (40 kB)
Collecting beautifulsoup4==4.9.3
  Downloading beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting cairocffi==1.3.0
  Downloading cairocffi-1.3.0.tar.gz (88 kB)
Collecting cairosvg==2.5.2
  Downloading CairoSVG-2.5.2-py3-none-any.whl (45 kB)
Collecting caldav==0.8.0
  Downloading caldav-0.8.0-py3-none-any.whl (50 kB)
Collecting certifi==2021.5.30
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting cffi==1.15.0
  Downloading cffi-1.15.0.tar.gz (484 kB)
Collecting chardet==4.0.0
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting click==8.0.1
  Downloading click-8.0.1-py3-none-any.whl (97 kB)
Collecting cliff==3.8.0
  Downloading cliff-3.8.0-py3-none-any.whl (80 kB)
Collecting cmd2==2.1.1
  Downloading cmd2-2.1.1-py3-none-any.whl (140 kB)
Collecting colorama==0.4.5
  Downloading colorama-0.4.5-py2.py3-none-any.whl (16 kB)
Collecting colorlog==5.0.1
  Downloading colorlog-5.0.1-py2.py3-none-any.whl (10 kB)
Collecting colour==0.1.5
  Downloading colour-0.1.5-py2.py3-none-any.whl (23 kB)
Collecting cssselect2==0.6.0
  Downloading cssselect2-0.6.0-py3-none-any.whl (15 kB)
Collecting defusedxml==0.7.1
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting elasticsearch==7.13.1
  Downloading elasticsearch-7.13.1-py2.py3-none-any.whl (354 kB)
Collecting elasticsearch-dsl==7.3.0
  Downloading elasticsearch_dsl-7.3.0-py2.py3-none-any.whl (62 kB)
Collecting email-reply-parser==0.5.12
  Downloading email_reply_parser-0.5.12-py3-none-any.whl (4.1 kB)
Collecting filedepot==0.8.0
  Downloading filedepot-0.8.0.tar.gz (23 kB)
Collecting filelock==3.0.12
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting gitdb==4.0.7
  Downloading gitdb-4.0.7-py3-none-any.whl (63 kB)
Collecting gitpython==3.1.18
  Downloading GitPython-3.1.18-py3-none-any.whl (170 kB)
Collecting gripcontrol==4.1.0
  Downloading gripcontrol-4.1.0.tar.gz (10 kB)
Collecting hapic[marshmallow]==0.95
  Downloading hapic-0.95.tar.gz (612 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting html2text==2020.1.16
  Downloading html2text-2020.1.16-py3-none-any.whl (32 kB)
Collecting html5lib==1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Collecting humanize==3.9.0
  Downloading humanize-3.9.0-py3-none-any.whl (84 kB)
Collecting hupper==1.10.3
  Downloading hupper-1.10.3-py2.py3-none-any.whl (26 kB)
Collecting idna==2.10
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting imapclient==2.3.1
  Downloading IMAPClient-2.3.1-py2.py3-none-any.whl (181 kB)
Collecting importlib-metadata==4.6.0
  Downloading importlib_metadata-4.6.0-py3-none-any.whl (17 kB)
Collecting jsmin==2.2.2
  Downloading jsmin-2.2.2.tar.gz (12 kB)
Collecting jsonschema==3.2.0
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting ldap3==2.9
  Downloading ldap3-2.9-py2.py3-none-any.whl (430 kB)
Collecting lxml==4.9.1
  Downloading lxml-4.9.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.0 MB)
Collecting mako==1.2.2
  Downloading Mako-1.2.2-py3-none-any.whl (78 kB)
Collecting markdown==3.3.4
  Downloading Markdown-3.3.4-py3-none-any.whl (97 kB)
Collecting markupsafe==2.0.1
  Downloading MarkupSafe-2.0.1.tar.gz (18 kB)
Collecting marshmallow==2.21.0
  Downloading marshmallow-2.21.0-py2.py3-none-any.whl (50 kB)
Collecting multidict==5.2.0
  Downloading multidict-5.2.0.tar.gz (49 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting packaging==22.0
  Downloading packaging-22.0-py3-none-any.whl (42 kB)
Collecting passlib==1.7.4
  Downloading passlib-1.7.4-py2.py3-none-any.whl (525 kB)
Collecting pastedeploy==2.1.1
  Downloading PasteDeploy-2.1.1-py2.py3-none-any.whl (17 kB)
Collecting pbr==5.6.0
  Downloading pbr-5.6.0-py2.py3-none-any.whl (111 kB)
Collecting pillow==9.1.1
  Downloading Pillow-9.1.1.tar.gz (49.8 MB)
Collecting plaster==1.0
  Downloading plaster-1.0-py2.py3-none-any.whl (14 kB)
Collecting plaster-pastedeploy==0.7
  Downloading plaster_pastedeploy-0.7-py2.py3-none-any.whl (7.8 kB)
Collecting pluggy==0.13.1
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting prettytable==2.1.0
  Downloading prettytable-2.1.0-py3-none-any.whl (22 kB)
Collecting preview-generator==0.29
  Downloading preview_generator-0.29.tar.gz (57 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting pubcontrol==3.2.0
  Downloading pubcontrol-3.2.0.tar.gz (16 kB)
Collecting pyasn1==0.4.8
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting pycparser==2.21
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting pyexifinfo==0.4.0
  Downloading pyexifinfo-0.4.0.tar.gz (3.6 kB)
Collecting pygments==2.9.0
  Downloading Pygments-2.9.0-py3-none-any.whl (1.0 MB)
Collecting pyjwt==2.4.0
  Downloading PyJWT-2.4.0-py3-none-any.whl (18 kB)
Collecting pypandoc==1.8.1
  Downloading pypandoc-1.8.1-py3-none-any.whl (20 kB)
Collecting pyparsing==2.4.7
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting pyperclip==1.8.2
  Downloading pyperclip-1.8.2.tar.gz (20 kB)
Collecting pyphen==0.12.0
  Downloading pyphen-0.12.0-py3-none-any.whl (2.0 MB)
Collecting pyramid==2.0
  Downloading pyramid-2.0-py3-none-any.whl (246 kB)
Collecting pyramid-beaker==0.8
  Downloading pyramid_beaker-0.8.tar.gz (21 kB)
Collecting pyramid-debugtoolbar==4.9
  Downloading pyramid_debugtoolbar-4.9-py2.py3-none-any.whl (351 kB)
Collecting pyramid-ldap3==0.4.2
  Downloading pyramid_ldap3-0.4.2-py2.py3-none-any.whl (8.3 kB)
Collecting pyramid-mako==1.1.0
  Downloading pyramid_mako-1.1.0-py2.py3-none-any.whl (14 kB)
Collecting pyramid-tm==2.4
  Downloading pyramid_tm-2.4-py2.py3-none-any.whl (15 kB)
Collecting pyrsistent==0.18.0
  Downloading pyrsistent-0.18.0.tar.gz (104 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting python-dateutil==2.8.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting python-editor==1.0.4
  Downloading python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Collecting python-magic==0.4.24
  Downloading python_magic-0.4.24-py2.py3-none-any.whl (12 kB)
Collecting python-slugify==5.0.2
  Downloading python_slugify-5.0.2-py2.py3-none-any.whl (6.7 kB)
Collecting pytz==2021.1
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting pyyaml==5.4.1
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/hhh/tracim/tracim/backend/env/bin/python3 /home/hhh/tracim/tracim/backend/env/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp6ts4x1kf
       cwd: /tmp/pip-install-ox2cghqz/pyyaml_ae355aadb6be426f88fd46240d1feeee
  Complete output (54 lines):
  running egg_info
  writing lib3/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib3/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/home/hhh/tracim/tracim/backend/env/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/home/hhh/tracim/tracim/backend/env/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/hhh/tracim/tracim/backend/env/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run
      self.find_sources()
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
      mm.run()
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
      self.add_defaults()
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
      sdist.add_defaults(self)
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
      super().add_defaults()
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 201, in get_source_files
    File "/tmp/pip-build-env-mbrbbg6l/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b029991d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz#sha256=607774cbba28732bfa802b54baa7484215f530991055bb562efbed5b2f20a45e (from https://pypi.org/simple/pyyaml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*). Command errored out with exit status 1: /home/hhh/tracim/tracim/backend/env/bin/python3 /home/hhh/tracim/tracim/backend/env/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp6ts4x1kf Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyyaml==5.4.1 (from versions: 3.10, 3.11, 3.12, 3.13b1, 3.13rc1, 3.13, 4.2b1, 4.2b2, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.1, 5.1.1, 5.1.2, 5.2b1, 5.2, 5.3b1, 5.3, 5.3.1, 5.4b1, 5.4b2, 5.4, 5.4.1, 6.0b1, 6.0, 6.0.1)
ERROR: No matching distribution found for pyyaml==5.4.1
WARNING: You are using pip version 21.1.3; however, version 24.0 is available.
You should consider upgrading via the '/home/hhh/tracim/tracim/backend/env/bin/python3 -m pip install --upgrade pip' command.

[14:17:22] $ Failed to install dependencies in requirements.txt

### What devices are you seeing the problem on?

Desktop

**Comment by Skylsmoi** [comment]
Hi, it seems that the issue isn't related to Cypess but to an incompatibility with python 3.11.x

I'm updating the title of the issue.
A backend dev will give you a more detailed technical answer.

**Comment by HenraL** [comment]
By the way, just thought I'd point it out, but the default python installed in Ubuntu (server) 22.04.3. LTS is python 3.10.12
so if you need a specific version of python, maibe install that using the script (or ask the user to do so in the tutorial)
because python 3.10.12 does not work either, maybe try and update your requirements, pyyaml seems to always be the problem

Please do also think to update the way you install npm, your current way raises a big warning for outdated installation method. (just installing npm nowadays is enough to install the latest version of node)

I am going to try the solution you provided, hope it works this time (with an LTS version of ubuntu)

Downgrading to python 3.9.18 fixed the package issue

Got the error : 
```bash
[00:19:15] $ Generating dev certificate for SAML
./setup_default_backend.sh: line 196: pushd: backend: No such file or directory
.+..+......+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.........+......+.+.....+.......+..+....+..+.............+..+...+.+.....+...+.......+........+...+...+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+...+...+........+.......+..+......+.........+......+....+...........+....+..+.+.....+.............+..+.............+......+...+...+..............+.+...+............+........................+.........+.....+......+.+.........+........+..........+...+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.........+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+.+...+........+...+...................+........+...+....+.....+.+.....+......+.........+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.............+.....+......+.......+......+..............+...+............+.+..+.......+..+...+......+.+.........+.....+.+...+..+......+.........+....+.........+...+.....+....+.....................+..+...+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
./setup_default_backend.sh: line 198: popd: directory stack empty
```
Are these errors to be worried about?

**Comment by buxx** [comment]
Thanks for these reports @HenraL . We have a work to do on the deps update and build environment check.

@Skylsmoi Can you check the OS version in our CI ?
@Millefeuille42 This SAML error is a problem (for non SAML users) ?

**Comment by Skylsmoi** [comment]
The ci only runs on debian bullseye
tracim is supposed to run on ubuntu but our production environment is debian

**Comment by buxx** [comment]
Okay thanks, @HenraL I was wrong, we test Tracim on debian bullseye not on ubuntu LTS :s

**Comment by HenraL** [comment]
In the tutorial, the front-end section, can you please specify that you need node v14 or + is required?
Could you maybe provide a link (or build it into your tutorial) on how to satisfy the node requirements for the front-end?
Here is a good link from the authors themselves: [https://github.com/nodejs/node/blob/main/BUILDING.md#building-nodejs-on-supported-platforms](https://github.com/nodejs/node/blob/main/BUILDING.md#building-nodejs-on-supported-platforms)

**Comment by HenraL** [comment]
I just thought I'd let you know that I managed to deploy a partially functionnal yet extremely broken cloud (I could not sign out, could barely create anything) after 4+ hours (3 of which were used to compile and deploy nodejs LTS from scratch).

I did not easaly understand the transition between [building tracim (https://github.com/tracim/tracim/blob/develop/doc/BUILD.md)](https://github.com/tracim/tracim/blob/develop/doc/BUILD.md) and [production (https://github.com/tracim/tracim/blob/develop/doc/PRODUCTION.md)](https://github.com/tracim/tracim/blob/develop/doc/PRODUCTION.md)

If I am not mistaken the aim of production is to have a cloud that could be accessed from outside the machine?
thus, if it is the case, why isn't the first part of the production markdown a guide on how to change from local to public (and, thus which ip's to change)?

if the production section aims for a cloud accessible from the exterior, why isn't there an example to launch all the required services from one command line window, this could be very useful for ubuntu server users for example, they only have one window (if connecting a screen directly to the system)

A bit of explanation would be of great help
Thank you in advance for your answers

**Comment by PhilippeAccorsi** [comment]
Hi,
For production, you have two solution: 

- use docker image (https://hub.docker.com/r/algoo/tracim) : the docker image we make, is the better solution if you don't want to create all necessary configuration file/service and make relation between services.
  - With docker image, you can set all feature from a docker-compose.yml and use variable available [here](https://github.com/tracim/tracim/blob/develop/tools_docker/README.md) and [here](https://github.com/tracim/tracim/blob/develop/doc/backend/env_settings.md) to set and activate what you need
- create all configuration file and service you need and install what you want on one server or multiple server (ex: you can run backend on one server and frontend in another one)
  - on production, without docker, it is possible to set different server for each part of tracim. Or set each configuration you want (ex: if you don't need webdav, you not need to configure uwsgi config for this feature). You can find all necessary document to make your own server [here](https://github.com/tracim/tracim/tree/develop/doc/backend)

For production, not use develop branch. Its better to use stable tag available here https://github.com/tracim/tracim/releases

About documentation: we have make some change last year in organization of documentation and we not have time for the moment to make this clear. Version supported are visible here [https://github.com/tracim/tracim/blob/develop/doc/BUILD.md#compatibility](https://github.com/tracim/tracim/blob/develop/doc/BUILD.md#compatibility)

Regards,
Philippe

**Comment by PhilippeAccorsi** [comment]
> If I am not mistaken the aim of production is to have a cloud that could be accessed from outside the machine?
thus, if it is the case, why isn't the first part of the production markdown a guide on how to change from local to public (and, thus which ip's to change)?

For production you not use same installation like you use for development. You need to set some services to make server ready for production (ex: you not use `pserve` for backend but `uwsgi`). So you not just need to change  some IP address ;)

> if the production section aims for a cloud accessible from the exterior, why isn't there an example to launch all the required services from one command line window, this could be very useful for ubuntu server users for example, they only have one window (if connecting a screen directly to the system)

Documentation here is to deploy tracim in standalone. If you have some request to deploy on production, I think it is better to contact tracim company directly to discuss about support offers. Documentation here is not the best, we can seen to improve that, but it is not us priority for the moment.

Regards,
