### ISSUE TITLE
Use Hapic for File Streaming for Upload

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#696]
File content currently use pyramid way to deal with file, use hapic way.

**Comment by inkhey** [comment]
Download part is already done in tracim 2.0 with https://github.com/tracim/tracim/issues/903

**Comment by lebouquetin** [comment]
Way to test this:

1. run tracim on a VM with 500Mo of RAM and **NO SWAP**
2. from computer upload a 8Go file to the API.
3. The file must be fully uploaded, make a MD5 checksum to be sure the content is ok.

Note: be aware of uwsgi limitation (by default it is 1GB if I remember correctly)

**Comment by inkhey** [comment]
Uploading itself seems to work correctly if server and proxy correctly configured (we may need to configure apache/waitress/uwsgi to allow big file) as we can push full file without error but code can failed after upload itself due to memory issues.

I currently see 3 possible origin of memory issues using tracim:
- At upload of file : Hapic related
- During saving of file to depot/database
- completely unrelated to upload: at preview generation.

I will do deeper search to found it.

**Comment by inkhey** [comment]
One traceback found related to memory issue:
```
13:33:46 DEBUG [hapic:201][waitress] Traceback (most recent call last):
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/pyramid/viewderivers.py", line 95, in mapped_view
    return _mapped_view(context, request)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/hapic.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/home/user/Public/tracim/backend/tracim_backend/lib/utils/authorization.py", line 288, in wrapper
    return func(self, context, request)
  File "/home/user/Public/tracim/backend/tracim_backend/lib/utils/authorization.py", line 288, in wrapper
    return func(self, context, request)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/decorator.py", line 126, in wrapper
    response = self._execute_wrapped_function(func, args, kwargs)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/decorator.py", line 657, in _execute_wrapped_function
    return super()._execute_wrapped_function(func, func_args, func_kwargs)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/decorator.py", line 133, in _execute_wrapped_function
    return func(*func_args, **func_kwargs)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/decorator.py", line 122, in wrapper
    replacement_response = self.before_wrapped_func(args, kwargs)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/decorator.py", line 148, in before_wrapped_func
    request_parameters = self.get_request_parameters(func_args, func_kwargs)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/decorator.py", line 170, in get_request_parameters
    return self.context.get_request_parameters(*func_args, **func_kwargs)
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/hapic/ext/pyramid/context.py", line 53, in get_request_parameters
    if req.body and req.content_type in ("application/json", "application/json-rpc"):
  File "/home/user/Public/tracim/env3.6/lib/python3.6/site-packages/webob/request.py", line 694, in body
    r = self.body_file.read(self.content_length)
MemoryError
```

**Comment by inkhey** [comment]
using mprof (need some dependencies):
`
 mprof run ../env3.6/bin/pserve development.ini  # should be adapt according to venv
mprof plot -o image.jpg
`

small file:
![image2](https://user-images.githubusercontent.com/7851652/58957199-704b2200-87a0-11e9-8c74-9a0f785739ef.png)

big file:
![image3](https://user-images.githubusercontent.com/7851652/58957200-704b2200-87a0-11e9-8794-527d434ec376.png)

There seems to be multiples issue with loading file.

**Comment by inkhey** [comment]
Found 2 source of issue:
1.in  hapic pyramid context,  get_request_parameters() do a "if req.body" which call read() method (webob mecanism).
2. Somewhere during saving of new content body. Most probably related to those lines:
```
    with session.no_autoflush:
        try:
            if force_create_new_revision or inspect(content.revision).has_identity:
                content.new_revision()
            RevisionsIntegrity.add_to_updatable(content.revision)
            yield content
```
in new_revision context_manager (`/models/revision_protection.py`)

**Comment by inkhey** [comment]
After check, i fixed memory issue during upload for web view.
This does not fix issue for webdav context as the problem is complex.
This does not fix either memory issue with preview load (found by checking this).

**Comment by inkhey** [comment]
@PhilippeAccorsi to test the behavior of #1899 is correct, you should : 
- Make test with limited memory docker.
But be carefull because there is other memory issue that this issue doesn't fix:
- Memory high usage during preview_generation -> do not test with previewable content (issue #1901 )
- Webdav context -> test only through web app ( issue #1900 )

Also there is one other potential memory issue : 
- Potential memory issue linked to research through elasticsearch, as we ingest of all content_type now, if you test with elasticsearch + ingest mode.

**Comment by buxx** [comment]
> Potential memory issue linked to research through elasticsearch, as we ingest of all content_type now, if you test with elasticsearch + ingest mode.

@inkhey Does exist an issue about that ? If no, can you create one ?

**Comment by inkhey** [comment]
> > Potential memory issue linked to research through elasticsearch, as we ingest of all content_type now, if you test with elasticsearch + ingest mode.
> 
> @inkhey Does exist an issue about that ? If no, can you create one ?

We have issue about b64 encoding : https://github.com/tracim/tracim/issues/1877, as we do b64, That's almost certain we will have memory issue during file sending.

**Comment by inkhey** [comment]
Verified
