### ISSUE TITLE
WebDAV Note: user require login before use webdav

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#92]
Si on ne s'est pas loggé au moins une fois avant d'utiliser webdav: 

```
Traceback (most recent call last):
  File "/opt/algoo.trac.im/tracim/tg2env/src/wsgidav/wsgidav/server/cherrypy/wsgiserver/wsgiserver3.py", line 1032, in communicate
    req.respond()
  File "/opt/algoo.trac.im/tracim/tg2env/src/wsgidav/wsgidav/server/cherrypy/wsgiserver/wsgiserver3.py", line 828, in respond
    self.server.gateway(self).respond()
  File "/opt/algoo.trac.im/tracim/tg2env/src/wsgidav/wsgidav/server/cherrypy/wsgiserver/wsgiserver3.py", line 1841, in respond
    for chunk in response:
  File "/opt/algoo.trac.im/tracim/tg2env/src/wsgidav/wsgidav/wsgidav_app.py", line 407, in __call__
    for v in app_iter:
  File "/opt/algoo.trac.im/tracim/tg2env/src/wsgidav/wsgidav/debug_filter.py", line 158, in __call__
    for v in app_iter:
  File "/opt/algoo.trac.im/tracim/tg2env/src/wsgidav/wsgidav/error_printer.py", line 45, in __call__
    app_iter = self._application(environ, sub_app_start_response)
  File "/opt/algoo.trac.im/tracim/tg2env/src/wsgidav/wsgidav/http_authenticator.py", line 193, in __call__
    return self.authDigestAuthRequest(environ, start_response)
  File "/opt/algoo.trac.im/tracim/tracim/tracim/lib/webdav/tracim_http_authenticator.py", line 118, in authDigestAuthRequest
    req_cnonce, req_qop, req_nc)
  File "/opt/algoo.trac.im/tracim/tracim/tracim/lib/webdav/tracim_http_authenticator.py", line 140, in tracim_compute_digest_response
    digestresp = self.md5kd(left_digest_response_hash, nonce + ":" + nc + ":" + cnonce + ":" + qop + ":" + self.md5h(A2))
  File "/opt/algoo.trac.im/tracim/tg2env/src/wsgidav/wsgidav/http_authenticator.py", line 406, in md5kd
    return self.md5h(secret + ":" + data)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by tracim** [comment]
Buxx, quel comportement serait approprié ?

**Comment by buxx** [comment]
Pas de solutions pour les utilisateur existant déjà avant la migration vers beta 1.0.

Vérifier et écrire les cas de tests pour:
* Création d'un user (mot de passe généré et choisis)
* Maj mot de passe
* Réinitialisation mot de passe

**Comment by buxx** [comment]
TODO: Vérifier et écrire les tests pour le cas où il y a un changement d'email: Si le digest n'est pas re-calculé, il ne sera pas valide dans ce cas de figure.

**Comment by buxx** [comment]
>TODO: Vérifier et écrire les tests pour le cas où il y a un changement d'email (depuis compte utilisateur et depuis l'admin): Si le digest n'est pas re-calculé, il ne sera pas valide dans ce cas de figure.

@lebouquetin Ca pose un problème: On en peut mettre à jour le digest webdav quand on change le mail d'un utilisateur car on ne connait pas le mot de passe à ce moment là. Lors du changement de son propre email, on peux re-demander le mot de passe. Mais pour changer l'email d'un utilisateur en admin c'est impossible. A moins de mettre en place une procédure invitant l'utilisateur concerné à venir le saisir.

**Comment by tracim** [comment]
@buxx effectivement c'est un cas un peu particulier. Je pense que la solution c'est de mettre un message d'avertissement dans l'interface lorsqu'on change l'adresse email.

Du coup, ce qu'il faut : 
- faire les tests pour les cas normaux de changement de mot de passe (déjà fait si j'ai bien compris)
- clore le ticket
- en créer un indiquant que le token devient invalide lorsqu'on change l'adresse email (on verra plus tard comme on le corrige/contourne)

**Comment by buxx** [comment]
Nouvelle issue: #127.
