### ISSUE TITLE
beaker session may broke update

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#922]
Beaker store session and session_lock. in few case, updating tracim may give inconsistent data, and make endpoint return 500 error.

Traceback with global 500 error not catched by hapic : 

```
14:46:52 ERROR [waitress:341][waitress] Exception when serving /
Traceback (most recent call last):
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/pyramid_retry/__init__.py", line 134, in retry_policy
    return request.invoke_exception_view(reraise=True)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/pyramid/view.py", line 755, in invoke_exception_view
    reraise_(*exc_info)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/pyramid_retry/__init__.py", line 114, in retry_policy
    response = router.invoke_request(request)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/pyramid_tm/__init__.py", line 128, in tm_tween
    userid = request.unauthenticated_userid
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/pyramid/security.py", line 388, in unauthenticated_userid
    return policy.unauthenticated_userid(self)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/pyramid_multiauth/__init__.py", line 100, in unauthenticated_userid
    userid = policy.unauthenticated_userid(request)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/pyramid/authentication.py", line 1044, in unauthenticated_userid
    return request.session.get(self.userid_key)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/beaker/session.py", line 771, in __getattr__
    return getattr(self._session(), attr)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/beaker/session.py", line 767, in _session
    self.__dict__['_sess'] = session_cls(req, **params)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/beaker/session.py", line 221, in __init__
    self.load()
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/beaker/session.py", line 391, in load
    self.namespace.acquire_read_lock()
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/beaker/container.py", line 208, in acquire_read_lock
    self.open('r', checkcount=True)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/beaker/container.py", line 240, in open
    self.do_open(flags, replace)
  File "/root/tracim_v2/backend/env/lib/python3.5/site-packages/beaker/container.py", line 673, in do_open
    self.hash = pickle.load(fh)
EOFError: Ran out of input
```

Workaround : 
- Clear beaker session data whenever tracim update happened. (session.data_dir and session.lock_dir param in backend ini config)

**Comment by PhilippeAccorsi** [comment]
Add delete folder "sessions_data" and "sessions_lock" in setup_default_backend.sh to solved this problem after discussion with @inkhey .

**Comment by PhilippeAccorsi** [comment]
Verified.
