### ISSUE TITLE
Calendar task internal error

### ISSUE THREAD

**Issue by mranderson56** [tracim/tracim#944]
**Describe the bug**
It's impossible to create a task in the calendar. There is an internal error message.

**To Reproduce**
1. Go to 'Calendar'
2. Click on 'Task'
3. Create a task

**Screenshots**
The error in debug mode : 

Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/tracim/tg2env/lib/python3.5/site-packages/radicale/__init__.py", line 332, in __call__
    user)
  File "/tracim/tg2env/lib/python3.5/site-packages/radicale/__init__.py", line 588, in do_PUT
    xmlutils.put(environ["PATH_INFO"], content, collection)
  File "/tracim/tg2env/lib/python3.5/site-packages/radicale/xmlutils.py", line 453, in put
    collection.append(name, ical_request)
  File "/tracim/tracim/tracim/lib/radicale/storage.py", line 66, in append
    self._add_tracim_event(name, text)
  File "/tracim/tracim/tracim/lib/radicale/storage.py", line 82, in _add_tracim_event
    owner=Auth.current_user
  File "/tracim/tracim/tracim/lib/calendar.py", line 207, in add_event
    event_name
  File "/tracim/tracim/tracim/lib/calendar.py", line 303, in populate_content_with_event
    content.label = event.get('summary')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by PhilippeAccorsi** [comment]
Hi, 

Can you explain how you have installed tracim?
