### ISSUE TITLE
authentification error: if url of confENV.json is not the same like we have in development.ini

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#988]
at present:

if you don't have same url in /frontend/confENV.json and in /backend/development.ini (line: website.base_url = "") you have this error (if you don't use cookies before):

~~~
12:33:48 INFO  [sqlalchemy.engine.base.Engine:1154][waitress] ('admin@admin.admin',)
12:33:48 INFO  [sqlalchemy.engine.base.Engine:1151][waitress] SELECT groups.group_id AS groups_group_id, groups.group_name AS groups_group_name, groups.display_name AS groups_display_name, groups.created AS groups_created 
FROM groups, user_group 
WHERE ? = user_group.user_id AND groups.group_id = user_group.group_id
12:33:48 INFO  [sqlalchemy.engine.base.Engine:1154][waitress] (1,)
12:33:48 INFO  [sqlalchemy.engine.base.Engine:702][waitress] ROLLBACK
12:33:49 INFO  [hapic:235][waitress] Exception NotAuthenticated occured, return 401 http_code : User None not found
12:33:49 INFO  [hapic:235][waitress] Exception NotAuthenticated occured, return 401 http_code : User None not found
12:33:49 DEBUG [hapic:237][waitress] Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/request.py", line 328, in _get_auth_safe_user
    raise UserNotFoundInTracimRequest('You request a current user but the context not permit to found one')  # nopep8
tracim_backend.exceptions.UserNotFoundInTracimRequest: You request a current user but the context not permit to found one

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 301, in secured_view
    return view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 107, in mapped_view
    return _mapped_view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/hapic.py", line 127, in wrapper
    return func(*args, **kwargs)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/authorization.py", line 64, in wrapper
    auth_user = request.current_user
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/request.py", line 102, in current_user
    self.current_user = self._get_auth_safe_user(self)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/request.py", line 333, in _get_auth_safe_user
    raise NotAuthenticated('User {} not found'.format(login)) from exc
tracim_backend.exceptions.NotAuthenticated: User None not found

12:33:49 DEBUG [hapic:237][waitress] Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/request.py", line 328, in _get_auth_safe_user
    raise UserNotFoundInTracimRequest('You request a current user but the context not permit to found one')  # nopep8
tracim_backend.exceptions.UserNotFoundInTracimRequest: You request a current user but the context not permit to found one

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 301, in secured_view
    return view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 107, in mapped_view
    return _mapped_view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/hapic.py", line 127, in wrapper
    return func(*args, **kwargs)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/authorization.py", line 85, in wrapper
    user = request.current_user
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/request.py", line 102, in current_user
    self.current_user = self._get_auth_safe_user(self)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/request.py", line 333, in _get_auth_safe_user
    raise NotAuthenticated('User {} not found'.format(login)) from exc
tracim_backend.exceptions.NotAuthenticated: User None not found

12:33:49 INFO  [hapic:235][waitress] Exception NotAuthenticated occured, return 401 http_code : User None not found
12:33:49 DEBUG [hapic:237][waitress] Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/request.py", line 328, in _get_auth_safe_user
    raise UserNotFoundInTracimRequest('You request a current user but the context not permit to found one')  # nopep8
tracim_backend.exceptions.UserNotFoundInTracimRequest: You request a current user but the context not permit to found one

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 301, in secured_view
    return view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 107, in mapped_view
    return _mapped_view(context, request)
  File "/home/algoo/repo/tracim_v2/backend/env/lib/python3.6/site-packages/hapic/hapic.py", line 127, in wrapper
    return func(*args, **kwargs)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/authorization.py", line 85, in wrapper
    user = request.current_user
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/request.py", line 102, in current_user
    self.current_user = self._get_auth_safe_user(self)
  File "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/utils/request.py", line 333, in _get_auth_safe_user
    raise NotAuthenticated('User {} not found'.format(login)) from exc
tracim_backend.exceptions.NotAuthenticated: User None not found
~~~

Expected

if you don't have same url, please log this in traceback.
Put this issue information in FAQ.

**Comment by PhilippeAccorsi** [comment]
Its working good.
