### ISSUE TITLE
In docker container, localhost host produce a bug

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#995]
**Describe the bug**
When run `pserve development.ini` in docker container, following error happen:

``` bash
Traceback (most recent call last):
  File "/tracim/backend/env/bin/pserve", line 11, in <module>
    sys.exit(main())
  File "/tracim/backend/env/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/tracim/backend/env/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 239, in run
    server(app)
  File "/tracim/backend/env/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 189, in server_wrapper
    **context.local_conf)
  File "/tracim/backend/env/lib/python3.5/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/tracim/backend/env/lib/python3.5/site-packages/waitress/__init__.py", line 20, in serve_paste
    serve(app, **kw)
  File "/tracim/backend/env/lib/python3.5/site-packages/waitress/__init__.py", line 11, in serve
    server = _server(app, **kw)
  File "/tracim/backend/env/lib/python3.5/site-packages/waitress/server.py", line 85, in create_server
    sockinfo=sockinfo)
  File "/tracim/backend/env/lib/python3.5/site-packages/waitress/server.py", line 182, in __init__
    self.bind_server_socket()
  File "/tracim/backend/env/lib/python3.5/site-packages/waitress/server.py", line 294, in bind_server_socket
    self.bind(sockaddr)
  File "/usr/lib/python3.5/asyncore.py", line 329, in bind
    return self.socket.bind(addr)
OSError: [Errno 99] Cannot assign requested address
```

**To Reproduce**

1. Install tracim in a debian:9 docker container
2. Ensure line `listen = localhost:6543` is present in `[server:main]`  section
3. Run `pserve development.ini`

**Expected behavior**

Tracim should start without error. Maybe it is not solvable (docker things ...). But it can be added to an FAQ. Note: "127.0.0.1" in `listen = ` work.

**Comment by Sarah-Pelle** [comment]
Outdated
